import type { LeaderNoId } from '../../app/data/types';
import { leanings } from '../../app/data/types';

export const source = `https://en.wikipedia.org/wiki/List_of_heads_of_state_of_Argentina`;

const countryId = 20;

export const argentina: LeaderNoId[] = [
	{
		countryId,
		name: `Bartolomé Mitre`,
		party: `Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `12 December 1861`,
		leftOffice: `12 October 1868`,
	},
	{
		countryId,
		name: `Domingo Faustino Sarmiento`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `12 October 1868`,
		leftOffice: `12 October 1874`,
	},
	{
		countryId,
		name: `Nicolás Avellaneda`,
		party: `National Autonomist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `12 October 1874`,
		leftOffice: `12 October 1880`,
	},
	{
		countryId,
		name: `Alejo Julio Argentino Roca`,
		party: `National Autonomist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `12 October 1880`,
		leftOffice: `12 October 1886`,
	},
	{
		countryId,
		name: `Miguel Ángel Juárez Celman`,
		party: `National Autonomist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `12 October 1886`,
		leftOffice: `6 August 1890`,
	},
	{
		countryId,
		name: `Carlos Pellegrini`,
		party: `National Autonomist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `6 August 1890`,
		leftOffice: `12 October 1892`,
	},
	{
		countryId,
		name: `Luis Sáenz Peña`,
		party: `National Autonomist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `12 October 1892`,
		leftOffice: `22 January 1895`,
	},
	{
		countryId,
		name: `José Evaristo Uriburu`,
		party: `National Autonomist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `22 January 1895`,
		leftOffice: `12 October 1898`,
	},
	{
		countryId,
		name: `Julio Argentino Roca`,
		party: `National Autonomist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `12 October 1898`,
		leftOffice: `12 October 1904`,
	},
	{
		countryId,
		name: `Manuel Quintana`,
		party: `National Autonomist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `12 October 1904`,
		leftOffice: `12 March 1906`,
	},
	{
		countryId,
		name: `José Figueroa Alcorta`,
		party: `National Autonomist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `12 March 1906`,
		leftOffice: `12 October 1910`,
	},
	{
		countryId,
		name: `Roque Sáenz Peña`,
		party: `National Autonomist Party (Modernist)`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `12 October 1910`,
		leftOffice: `9 August 1914`,
	},
	{
		countryId,
		name: `Victorino de la Plaza`,
		party: `National Autonomist Party (Modernist)`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `9 August 1914`,
		leftOffice: `12 October 1916`,
	},
	{
		countryId,
		name: `Hipólito Yrigoyen`,
		party: `Radical Civic Union`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `12 October 1916`,
		leftOffice: `12 October 1922`,
	},
	{
		countryId,
		name: `Marcelo Torcuato de Alvear`,
		party: `Radical Civic Union`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `12 October 1922`,
		leftOffice: `12 October 1928`,
	},
	{
		countryId,
		name: `Hipólito Yrigoyen`,
		party: `Radical Civic Union`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `12 October 1928`,
		leftOffice: `6 September 1930`,
	},
	{
		countryId,
		name: `José Félix Uriburu`,
		party: `Argentine Armed Forces`,
		leaning: leanings.RIGHT,
		tookOffice: `6 September 1930`,
		leftOffice: `20 February 1932`,
	},
	{
		countryId,
		name: `Agustín Pedro Justo`,
		party: `Radical Civic Union (Concordancia)`,
		leaning: leanings.RIGHT,
		tookOffice: `20 February 1932`,
		leftOffice: `20 February 1938`,
	},
	{
		countryId,
		name: `Roberto María Ortiz`,
		party: `Radical Civic Union (Concordancia)`,
		leaning: leanings.RIGHT,
		tookOffice: `20 February 1938`,
		leftOffice: `27 June 1942`,
	},
	{
		countryId,
		name: `Ramón Castillo`,
		party: `National Democratic Party (Concordancia)`,
		leaning: leanings.RIGHT,
		tookOffice: `27 June 1942`,
		leftOffice: `4 June 1943`,
	},
	{
		countryId,
		name: `Arturo Franklin Rawson`,
		party: `Argentine Armed Forces`,
		leaning: leanings.RIGHT,
		tookOffice: `4 June 1943`,
		leftOffice: `7 June 1943`,
	},
	{
		countryId,
		name: `Pedro Pablo Ramírez`,
		party: `Argentine Armed Forces`,
		leaning: leanings.RIGHT,
		tookOffice: `7 June 1943`,
		leftOffice: `9 March 1944`,
	},
	{
		countryId,
		name: `Edelmiro Julián Farrell`,
		party: `Argentine Armed Forces`,
		leaning: leanings.RIGHT,
		tookOffice: `9 March 1944`,
		leftOffice: `4 June 1946`,
	},
	{
		countryId,
		name: `Juan Perón`,
		party: `Justicialist Party / Peronist`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `4 June 1946`,
		leftOffice: `19 September 1955`,
	},
	{
		countryId,
		name: `Eduardo Lonardi`,
		party: `Argentine Armed Forces`,
		leaning: leanings.RIGHT,
		tookOffice: `19 September 1955`,
		leftOffice: `13 November 1955`,
	},

	{
		countryId,
		name: `Pedro Eugenio Aramburu`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `13 November 1955`,
		leftOffice: `1 May 1958`,
	},
	{
		countryId,
		name: `Arturo Frondizi`,
		party: `Intransigent Radical Civic Union`,
		leaning: leanings.LEFT,
		tookOffice: `1 May 1958`,
		leftOffice: `29 March 1962`,
	},
	{
		countryId,
		name: `José María Guido`,
		party: `Intransigent Radical Civic Union`,
		leaning: leanings.LEFT,
		tookOffice: `29 March 1962`,
		leftOffice: `12 October 1963`,
	},
	{
		countryId,
		name: `Arturo Umberto Illia`,
		party: `People's Radical Civic Union`,
		leaning: leanings.CENTRIST,
		tookOffice: `12 October 1963`,
		leftOffice: `28 June 1966`,
	},
	{
		countryId,
		name: `Junta of Commanders of the Armed Forces - Pascual Pistarini, Benigno Ignacio Varela, Adolfo Teodoro Álvarez`,
		party: `Argentine Armed Forces`,
		leaning: leanings.RIGHT,
		tookOffice: `28 June 1966`,
		leftOffice: `29 June 1966`,
	},
	{
		countryId,
		name: `Juan Carlos Onganía`,
		party: `Argentine Armed Forces`,
		leaning: leanings.RIGHT,
		tookOffice: `29 June 1966`,
		leftOffice: `8 June 1970`,
	},
	{
		countryId,
		name: `Junta of Commanders of the Armed Forces - Pedro Alberto José Gnavi, Alejandro Agustín Lanusse, Carlos Alberto Rey`,
		party: `Argentine Armed Forces`,
		leaning: leanings.RIGHT,
		tookOffice: `8 June 1970`,
		leftOffice: `18 June 1970`,
	},
	{
		countryId,
		name: `Roberto M. Levingston`,
		party: `Argentine Armed Forces`,
		leaning: leanings.RIGHT,
		tookOffice: `18 June 1970`,
		leftOffice: `23 March 1971`,
	},
	{
		countryId,
		name: `Junta of Commanders of the Armed Forces - Alejandro Agustín Lanusse, Pedro Alberto José Gnavi, Carlos Alberto Rey`,
		party: `Argentine Armed Forces`,
		leaning: leanings.RIGHT,
		tookOffice: `23 March 1971`,
		leftOffice: `26 March 1971`,
	},
	{
		countryId,
		name: `Alejandro Agustín Lanusse`,
		party: `Argentine Armed Forces`,
		leaning: leanings.RIGHT,
		tookOffice: `26 March 1971`,
		leftOffice: `25 May 1973`,
	},
	{
		countryId,
		name: `Héctor José Cámpora`,
		party: `Justicialist Party / Peronist`,
		leaning: leanings.LEFT,
		tookOffice: `25 May 1973`,
		leftOffice: `13 July 1973`,
	},
	{
		countryId,
		name: `Raúl Alberto Lastiri`,
		party: `Justicialist Party / Peronist`,
		leaning: leanings.LEFT,
		tookOffice: `13 July 1973`,
		leftOffice: `12 October 1973`,
	},
	{
		countryId,
		name: `Juan Perón`,
		party: `Justicialist Party / Peronist`,
		leaning: leanings.RIGHT,
		tookOffice: `12 October 1973`,
		leftOffice: `1 July 1974`,
	},
	{
		countryId,
		name: `Isabel Perón`,
		party: `Justicialist Party / Peronist`,
		leaning: leanings.RIGHT,
		tookOffice: `29 June 1974`,
		leftOffice: `24 March 1976`,
	},
	{
		countryId,
		name: `Military Junta - Jorge Rafael Videla, Emilio Eduardo Massera, Orlando Ramón Agosti`,
		party: `Argentine Armed Forces`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `24 March 1976`,
		leftOffice: `29 March 1976`,
	},
	{
		countryId,
		name: `Jorge Rafael Videla`,
		party: `Argentine Armed Forces`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `29 March 1976`,
		leftOffice: `29 March 1981`,
	},
	{
		countryId,
		name: `Roberto Eduardo Viola`,
		party: `Argentine Armed Forces`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `29 March 1981`,
		leftOffice: `21 November 1981`,
	},
	{
		countryId,
		name: `Horacio Tomás Liendo`,
		party: `Argentine Armed Forces`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `21 November 1981`,
		leftOffice: `11 December 1981`,
	},
	{
		countryId,
		name: `Carlos Lacoste`,
		party: `Argentine Armed Forces`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `11 December 1981`,
		leftOffice: `22 December 1981`,
	},
	{
		countryId,
		name: `Leopoldo Galtieri`,
		party: `Argentine Armed Forces`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `22 December 1981`,
		leftOffice: `18 June 1982`,
	},
	{
		countryId,
		name: `Alfredo Oscar Saint Jean`,
		party: `Argentine Armed Forces`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `18 June 1982`,
		leftOffice: `1 July 1982`,
	},
	{
		countryId,
		name: `Reynaldo Bignone`,
		party: `Argentine Armed Forces`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `1 July 1982`,
		leftOffice: `10 December 1983`,
	},
	{
		countryId,
		name: `Raúl Alfonsín`,
		party: `Radical Civic Union`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `10 December 1983`,
		leftOffice: `8 July 1989`,
	},
	{
		countryId,
		name: `Carlos Saúl Menem Akil`,
		party: `Justicialist Party / Peronist`,
		leaning: leanings.RIGHT,
		tookOffice: `8 July 1989`,
		leftOffice: `10 December 1999`,
	},
	{
		countryId,
		name: `Fernando de la Rúa`,
		party: `Alliance for Work, Justice and Education`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `10 December 1999`,
		leftOffice: `20 December 2001`,
	},
	{
		countryId,
		name: `Ramón Puerta`,
		party: `Justicialist Party / Peronist`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `20 December 2001`,
		leftOffice: `22 December 2001`,
	},
	{
		countryId,
		name: `Adolfo Rodríguez Saá`,
		party: `Justicialist Party / Peronist`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `22 December 2001`,
		leftOffice: `30 December 2001`,
	},
	{
		countryId,
		name: `Eduardo Camaño`,
		party: `Justicialist Party / Peronist`,
		leaning: leanings.CENTRIST,
		tookOffice: `30 December 2001`,
		leftOffice: `2 January 2002`,
	},
	{
		countryId,
		name: `Eduardo Duhalde`,
		party: `Justicialist Party / Peronist`,
		leaning: leanings.LEFT,
		tookOffice: `2 January 2002`,
		leftOffice: `25 May 2003`,
	},
	{
		countryId,
		name: `Néstor Kirchner`,
		party: `Justicialist Party / Peronist`,
		leaning: leanings.LEFT,
		tookOffice: `25 May 2003`,
		leftOffice: `10 December 2007`,
	},
	{
		countryId,
		name: `Cristina Fernández de Kirchner`,
		party: `Justicialist Party / Peronist`,
		leaning: leanings.LEFT,
		tookOffice: `10 December 2007`,
		leftOffice: `10 December 2015`,
	},
	{
		countryId,
		name: `Mauricio Macri`,
		party: `Republican Proposal`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `10 December 2015`,
		leftOffice: `10 December 2019`,
	},
	{
		countryId,
		name: `Alberto Fernández`,
		party: `Justicialist Party / Peronist`,
		leaning: leanings.LEFT,
		tookOffice: `10 December 2019`,
		leftOffice: null,
	},
];
