import type { LeaderNoId } from '../../app/data/types';
import { leanings } from '../../app/data/types';

export const source = `https://en.wikipedia.org/wiki/List_of_presidents_of_Bolivia`;

const countryId = 17;

export const bolivia: LeaderNoId[] = [
	{
		countryId,
		name: 'Viceroyalty of the Río de la Plata',
		party: 'Spanish Empire',
		leaning: leanings.MONARCHY,
		tookOffice: '1 August 1776',
		leftOffice: '12 August 1825',
	},
	{
		countryId,
		name: 'Simón Bolívar',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '12 August 1825',
		leftOffice: '29 December 1825',
	},
	{
		countryId,
		name: 'Antonio José de Sucre',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '29 December 1825',
		leftOffice: '25 May 1826',
	},
	{
		countryId,
		name: 'Antonio José de Sucre',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '25 May 1826',
		leftOffice: '18 April 1828',
	},
	{
		countryId,
		name: 'José María Pérez de Urdininea',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '18 April 1828',
		leftOffice: '12 August 1828',
	},
	{
		countryId,
		name: 'José Miguel de Velasco',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '2 August 1828',
		leftOffice: '18 December 1828',
	},
	{
		countryId,
		name: 'Pedro Blanco Soto',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '26 December 1828',
		leftOffice: '1 January 1829',
	},
	{
		countryId,
		name: 'José Miguel de Velasco',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '1 January 1829',
		leftOffice: '24 May 1829',
	},
	{
		countryId,
		name: 'Andrés de Santa Cruz',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '24 May 1829',
		leftOffice: '17 February 1839',
	},
	{
		countryId,
		name: 'José Miguel de Velasco',
		party: 'Military',
		leaning: leanings.CENTRIST,
		tookOffice: '22 February 1839',
		leftOffice: '10 June 1841',
	},
	{
		countryId,
		name: 'Sebastián Ágreda',
		party: 'Military',
		leaning: leanings.CENTRIST,
		tookOffice: '10 June 1841',
		leftOffice: '9 July 1841',
	},
	{
		countryId,
		name: 'Mariano Enrique Calvo',
		party: 'Military',
		leaning: leanings.CENTRIST,
		tookOffice: '9 July 1841',
		leftOffice: '22 September 1841',
	},
	{
		countryId,
		name: 'José Ballivián',
		party: 'Military',
		leaning: leanings.CENTRIST,
		tookOffice: '27 September 1841',
		leftOffice: '23 December 1847',
	},
	{
		countryId,
		name: 'Eusebio Guilarte',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '23 December 1847',
		leftOffice: '2 January 1848',
	},
	{
		countryId,
		name: 'José Miguel de Velasco',
		party: 'Military',
		leaning: leanings.CENTRIST,
		tookOffice: '18 January 1848',
		leftOffice: '6 December 1848',
	},
	{
		countryId,
		name: 'Manuel Isidoro Belzu',
		party: 'Military',
		leaning: leanings.LEFT,
		tookOffice: '6 December 1848',
		leftOffice: '15 August 1855',
	},
	{
		countryId,
		name: 'Jorge Córdova',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '15 August 1855',
		leftOffice: '9 September 1857',
	},
	{
		countryId,
		name: 'José María Linares',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '9 September 1857',
		leftOffice: '14 January 1861',
	},
	{
		countryId,
		name: 'José María de Achá',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '4 May 1861',
		leftOffice: '28 December 1864',
	},
	{
		countryId,
		name: 'Mariano Melgarejo',
		party: 'Military',
		leaning: leanings.FAR_RIGHT,
		tookOffice: '28 December 1864',
		leftOffice: '15 January 1871',
	},
	{
		countryId,
		name: 'Agustín Morales',
		party: 'Military',
		leaning: leanings.FAR_RIGHT,
		tookOffice: '15 January 1871',
		leftOffice: '27 November 1872',
	},
	{
		countryId,
		name: 'Tomás Frías',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '28 November 1872',
		leftOffice: '9 May 1873',
	},
	{
		countryId,
		name: 'Adolfo Ballivián',
		party: 'The Red Party',
		leaning: leanings.CENTRIST,
		tookOffice: '9 May 1873',
		leftOffice: '14 February 1874',
	},
	{
		countryId,
		name: 'Tomás Frías',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '14 February 1874',
		leftOffice: '4 May 1876',
	},
	{
		countryId,
		name: 'Hilarión Daza',
		party: 'Military',
		leaning: leanings.CENTRIST,
		tookOffice: '4 May 1876',
		leftOffice: '28 December 1879',
	},
	{
		countryId,
		name: 'Narciso Campero',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '19 January 1880',
		leftOffice: '4 September 1884',
	},
	{
		countryId,
		name: 'Gregorio Pacheco',
		party: 'Conservative Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '4 September 1884',
		leftOffice: '15 August 1888',
	},
	{
		countryId,
		name: 'Aniceto Arce',
		party: 'Conservative Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '15 August 1888',
		leftOffice: '11 August 1892',
	},
	{
		countryId,
		name: 'Mariano Baptista',
		party: 'Conservative Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '11 August 1892',
		leftOffice: '19 August 1896',
	},
	{
		countryId,
		name: 'Severo Fernández',
		party: 'Conservative Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '19 August 1896',
		leftOffice: '12 April 1899',
	},
	{
		countryId,
		name: 'Government Junta',
		party: 'Bolivian Civil War',
		leaning: leanings.CENTER_LEFT,
		tookOffice: '12 April 1899',
		leftOffice: '25 October 1899',
	},
	{
		countryId,
		name: `José Manuel Pando`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `25 October 1899`,
		leftOffice: `14 August 1904`,
	},
	{
		countryId,
		name: `Ismael Montes`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `14 August 1904`,
		leftOffice: `12 August 1909`,
	},
	{
		countryId,
		name: `Eliodoro Villazón`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `12 August 1909`,
		leftOffice: `14 August 1913`,
	},
	{
		countryId,
		name: `Ismael Montes II`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `14 August 1913`,
		leftOffice: `15 August 1917`,
	},
	{
		countryId,
		name: `José Gutiérrez Guerra`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `15 August 1917`,
		leftOffice: `12 July 1920`,
	},
	{
		countryId,
		name: `Military Junta - Bautista Saavedra, José María Escalier, José Manuel Ramírez`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: `13 July 1920`,
		leftOffice: `16 July 1921`,
	},
	{
		countryId,
		name: `Military Junta - Bautista Saavedra, José María Escalier, José Manuel Ramírez, Juan José Fernández`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: `16 July 1920`,
		leftOffice: `28 January 1921`,
	},
	{
		countryId,
		name: `Bautista Saavedra`,
		party: `Republican Party`,
		leaning: leanings.RIGHT,
		tookOffice: `28 January 1921`,
		leftOffice: `3 September 1925`,
	},
	{
		countryId,
		name: `Felipe Segundo Guzmán`,
		party: `Republican Party`,
		leaning: leanings.RIGHT,
		tookOffice: `3 September 1925`,
		leftOffice: `10 January 1926`,
	},
	{
		countryId,
		name: `Hernando Siles Reyes`,
		party: `Republican Party`,
		leaning: leanings.RIGHT,
		tookOffice: `10 January 1926`,
		leftOffice: `28 May 1930`,
	},
	{
		countryId,
		name: `Council of Ministers`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `28 May 1930`,
		leftOffice: `28 June 1930`,
	},
	{
		countryId,
		name: `Carlos Blanco Galindo`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: `28 June 1930`,
		leftOffice: `5 March 1931`,
	},
	{
		countryId,
		name: `Daniel Salamanca`,
		party: `Genuine Republican Party`,
		leaning: leanings.RIGHT,
		tookOffice: `5 March 1931`,
		leftOffice: `28 November 1934`,
	},
	{
		countryId,
		name: `José Luis Tejada Sorzano`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `28 November 1934`,
		leftOffice: `17 May 1936`,
	},
	{
		countryId,
		name: `Germán Busch`,
		party: `Armed Forces of Bolivia - Socialist`,
		leaning: leanings.RIGHT,
		tookOffice: `17 May 1936`,
		leftOffice: `22 May 1936`,
	},
	{
		countryId,
		name: `David Toro`,
		party: `Armed Forces of Bolivia - Socialist`,
		leaning: leanings.RIGHT,
		tookOffice: `22 May 1936`,
		leftOffice: `13 July 1937`,
	},
	{
		countryId,
		name: `Germán Busch`,
		party: `Armed Forces of Bolivia - Socialist`,
		leaning: leanings.RIGHT,
		tookOffice: `13 July 1937`,
		leftOffice: `23 August 1939`,
	},
	{
		countryId,
		name: `Carlos Quintanilla`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: `23 August 1939`,
		leftOffice: `15 April 1940`,
	},
	{
		countryId,
		name: `Enrique Peñaranda`,
		party: `Concordance Party`,
		leaning: leanings.RIGHT,
		tookOffice: `15 April 1940`,
		leftOffice: `20 December 1943`,
	},
	{
		countryId,
		name: `Gualberto Villarroel`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: `20 December 1943`,
		leftOffice: `21 July 1946`,
	},
	{
		countryId,
		name: `Dámaso Arenas`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: `21 July 1946`,
		leftOffice: `21 July 1946`,
	},
	{
		countryId,
		name: `Néstor Guillén`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `21 July 1946`,
		leftOffice: `17 August 1946`,
	},
	{
		countryId,
		name: `Tomás Monje`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `17 August 1946`,
		leftOffice: `10 March 1947`,
	},
	{
		countryId,
		name: `Enrique Hertzog`,
		party: `Republican Socialist Unity Party`,
		leaning: leanings.RIGHT,
		tookOffice: `10 March 1947`,
		leftOffice: `7 May 1949`,
	},
	{
		countryId,
		name: `Mamerto Urriolagoitía`,
		party: `Republican Socialist Unity Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 May 1949`,
		leftOffice: `16 May 1951`,
	},
	{
		countryId,
		name: `Hugo Ballivián`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: `16 May 1951`,
		leftOffice: `11 April 1952`,
	},
	{
		countryId,
		name: `Hernán Siles Zuazo`,
		party: `Revolutionary Nationalist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `11 April 1952`,
		leftOffice: `15 April 1952`,
	},
	{
		countryId,
		name: `Víctor Paz Estenssoro I`,
		party: `Revolutionary Nationalist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `15 April 1952`,
		leftOffice: `6 August 1956`,
	},
	{
		countryId,
		name: `Hernán Siles Zuazo`,
		party: `Revolutionary Nationalist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `6 August 1956`,
		leftOffice: `6 August 1960`,
	},
	{
		countryId,
		name: `Víctor Paz Estenssoro II`,
		party: `Revolutionary Nationalist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `6 August 1960`,
		leftOffice: `4 November 1964`,
	},
	{
		countryId,
		name: `Military Junta - René Barrientos, Alfredo Ovando Candía, René Barrientos, Alfredo Ovando Candía`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: `4 November 1964`,
		leftOffice: `5 November 1964`,
	},
	{
		countryId,
		name: `René Barrientos`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: `5 November 1964`,
		leftOffice: `2 January 1966`,
	},
	{
		countryId,
		name: `Alfredo Ovando Candía`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: `2 January 1966`,
		leftOffice: `6 August 1966`,
	},
	{
		countryId,
		name: `René Barrientos`,
		party: `Armed Forces of Bolivia - Popular Christian`,
		leaning: leanings.RIGHT,
		tookOffice: `6 August 1966`,
		leftOffice: `27 April 1969`,
	},
	{
		countryId,
		name: `Luis Adolfo Siles Salinas`,
		party: `Social Democratic Party`,
		leaning: leanings.RIGHT,
		tookOffice: `27 April 1969`,
		leftOffice: `26 September 1969`,
	},
	{
		countryId,
		name: `Alfredo Ovando Candía`,
		party: `Armed Forces of Bolivia - Nationalist`,
		leaning: leanings.RIGHT,
		tookOffice: `26 September 1969`,
		leftOffice: `6 October 1970`,
	},
	{
		countryId,
		name: `Rogelio Miranda`,
		party: `Armed Forces of Bolivia - Nationalist`,
		leaning: leanings.RIGHT,
		tookOffice: `6 October 1970`,
		leftOffice: `6 October 1970`,
	},
	{
		countryId,
		name: `Military Junta - Efraín Guachalla, Alberto Albarracín, Fernando Sattori`,
		party: `Armed Forces of Bolivia - Nationalist`,
		leaning: leanings.RIGHT,
		tookOffice: `6 October 1970`,
		leftOffice: `7 October 1970`,
	},
	{
		countryId,
		name: `Juan José Torres`,
		party: `Armed Forces of Bolivia - Nationalist`,
		leaning: leanings.RIGHT,
		tookOffice: `7 October 1970`,
		leftOffice: `21 August 1971`,
	},
	{
		countryId,
		name: `Military Junta - Hugo Banzer, Andrés Selich Chop, Jaime Florentino Mendieta`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: `21 August 1971`,
		leftOffice: `22 August 1971`,
	},
	{
		countryId,
		name: `Hugo Banzer I`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: `22 August 1971`,
		leftOffice: `20 July 1978`,
	},
	{
		countryId,
		name: `Military Junta - Víctor González Fuentes, Gutenberg Barroso, Alfonso Villalpando`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: `21 July 1978`,
		leftOffice: `21 July 1978`,
	},
	{
		countryId,
		name: `Juan Pereda`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: `22 July 1978`,
		leftOffice: `24 November 1978`,
	},
	{
		countryId,
		name: `David Padilla`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: `24 November 1978`,
		leftOffice: `8 August 1979`,
	},
	{
		countryId,
		name: `Wálter Guevara`,
		party: `Authentic Revolutionary Party`,
		leaning: leanings.RIGHT,
		tookOffice: `8 August 1979`,
		leftOffice: `1 November 1979`,
	},
	{
		countryId,
		name: `Alberto Natusch`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: `1 November 1979`,
		leftOffice: `16 November 1979`,
	},
	{
		countryId,
		name: `Lidia Gueiler`,
		party: `Revolutionary Party of the Nationalist Left`,
		leaning: leanings.LEFT,
		tookOffice: `16 November 1979`,
		leftOffice: `17 July 1980`,
	},
	{
		countryId,
		name: `Military Junta - Luis García Meza, Ramiro Terrazas Rodríguez, Waldo Bernal Pereira`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: `17 July 1980`,
		leftOffice: `18 July 1980`,
	},
	{
		countryId,
		name: `Luis García Meza`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: `18 July 1980`,
		leftOffice: `4 August 1981`,
	},
	{
		countryId,
		name: `Military Junta - Celso Torrelio, Óscar Pammo Rodríguez, Waldo Bernal Pereira`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: `4 August 1981`,
		leftOffice: `4 September 1981`,
	},
	{
		countryId,
		name: `Celso Torrelio`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: `4 September 1981`,
		leftOffice: `19 July 1982`,
	},
	{
		countryId,
		name: `Military Junta - Ángel Mariscal, Natalio Morales, Óscar Pammo Rodríguez`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: `19 July 1981`,
		leftOffice: `21 July 1981`,
	},
	{
		countryId,
		name: `Guido Vildoso`,
		party: `Armed Forces of Bolivia`,
		leaning: leanings.RIGHT,
		tookOffice: `21 July 1982`,
		leftOffice: `10 October 1982`,
	},
	{
		countryId,
		name: `Hernán Siles Zuazo`,
		party: `Leftwing Revolutionary Nationalist Movement`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `10 October 1982`,
		leftOffice: `6 August 1985`,
	},
	{
		countryId,
		name: `Víctor Paz Estenssoro III`,
		party: `Revolutionary Nationalist Movement`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `6 August 1985`,
		leftOffice: `6 August 1989`,
	},
	{
		countryId,
		name: `Jaime Paz Zamora`,
		party: `Leftwing Revolutionary Nationalist Movement`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `6 August 1989`,
		leftOffice: `6 August 1993`,
	},
	{
		countryId,
		name: `Gonzalo Sánchez de Lozada I`,
		party: `Revolutionary Nationalist Movement`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `6 August 1993`,
		leftOffice: `6 August 1997`,
	},
	{
		countryId,
		name: `Hugo Banzer`,
		party: `Nationalist Democratic Action Party`,
		leaning: leanings.RIGHT,
		tookOffice: `6 August 1997`,
		leftOffice: `7 August 2001`,
	},
	{
		countryId,
		name: `Jorge Quiroga`,
		party: `Nationalist Democratic Action Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 2001`,
		leftOffice: `6 August 2002`,
	},
	{
		countryId,
		name: `Gonzalo Sánchez de Lozada II`,
		party: `Revolutionary Nationalist Movement`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `6 August 2002`,
		leftOffice: `17 October 2003`,
	},
	{
		countryId,
		name: `Carlos Diego Mesa Gisbert`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `17 October 2003`,
		leftOffice: `9 June 2005`,
	},
	{
		countryId,
		name: `Eduardo Rodríguez Veltzé`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `9 June 2005`,
		leftOffice: `22 January 2006`,
	},
	{
		countryId,
		name: `Evo Morales`,
		party: `Movement for Socialism`,
		leaning: leanings.FAR_LEFT,
		tookOffice: `22 January 2006`,
		leftOffice: `12 November 2019`,
	},
	{
		countryId,
		name: `Jeanine Áñez`,
		party: `Social Democratic Movement`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `12 November 2019`,
		leftOffice: `8 November 2020`,
	},
	{
		countryId,
		name: `Luis Arce`,
		party: `Movement for Socialism`,
		leaning: leanings.FAR_LEFT,
		tookOffice: `8 November 2020`,
		leftOffice: null,
	},
];
