import type { LeaderNoId } from '../../app/data/types';
import { leanings } from '../../app/data/types';

export const source = `https://en.wikipedia.org/wiki/List_of_presidents_of_Brazil`;

const countryId = 19;

export const brazil: LeaderNoId[] = [
	{
		countryId,
		name: `Colonial Brazil`,
		party: `Portuguese Empire`,
		leaning: leanings.MONARCHY,
		tookOffice: `1 April 1500`,
		leftOffice: `12 October 1822`,
	},
	{
		countryId,
		name: `Dom Pedro I`,
		party: `Empire of Brazil`,
		leaning: leanings.MONARCHY,
		tookOffice: `12 October 1822`,
		leftOffice: `7 April 1831`,
	},
	{
		countryId,
		name: `Dom Pedro II`,
		party: `Empire of Brazil`,
		leaning: leanings.MONARCHY,
		tookOffice: `7 April 1831`,
		leftOffice: `15 November 1889`,
	},
	{
		countryId,
		name: `Deodoro da Fonseca`,
		party: `Brazilian Armed Forces`,
		leaning: leanings.RIGHT,
		tookOffice: `15 November 1889`,
		leftOffice: `23 November 1891`,
	},
	{
		countryId,
		name: `Floriano Peixoto`,
		party: `Brazilian Armed Forces`,
		leaning: leanings.RIGHT,
		tookOffice: `23 November 1891`,
		leftOffice: `14 November 1894`,
	},
	{
		countryId,
		name: `Prudente de Morais`,
		party: `Federal Republican Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `15 November 1894`,
		leftOffice: `14 November 1898`,
	},
	{
		countryId,
		name: `Manuel Ferraz de Campos Sales`,
		party: `Paulista Republican Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `15 November 1898`,
		leftOffice: `14 November 1902`,
	},
	{
		countryId,
		name: `Francisco de Paula Rodrigues Alves`,
		party: `Paulista Republican Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `15 November 1902`,
		leftOffice: `14 November 1906`,
	},
	{
		countryId,
		name: `Afonso Pena`,
		party: `Minas Republican Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `15 November 1906`,
		leftOffice: `14 June 1909`,
	},
	{
		countryId,
		name: `Nilo Peçanha`,
		party: `Fluminense Republican Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `14 June 1909`,
		leftOffice: `14 November 1910`,
	},
	{
		countryId,
		name: `Hermes da Fonseca`,
		party: `Conservative Republican Party`,
		leaning: leanings.RIGHT,
		tookOffice: `15 November 1910`,
		leftOffice: `14 November 1914`,
	},
	{
		countryId,
		name: `Venceslau Brás`,
		party: `Minas Republican Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `15 November 1914`,
		leftOffice: `14 November 1918`,
	},
	{
		countryId,
		name: `Delfim Moreira`,
		party: `Minas Republican Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `15 November 1918`,
		leftOffice: `28 July 1919`,
	},
	{
		countryId,
		name: `Epitacio Pessoa`,
		party: `Minas Republican Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `28 July 1919`,
		leftOffice: `14 November 1922`,
	},
	{
		countryId,
		name: `Artur Bernardes`,
		party: `Minas Republican Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `15 November 1922`,
		leftOffice: `14 November 1926`,
	},
	{
		countryId,
		name: `Washington Luís`,
		party: `Paulista Republican Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `15 November 1926`,
		leftOffice: `24 October 1930`,
	},
	{
		countryId,
		name: `Augusto Tasso Fragoso, Isaías de Noronha, João de Deus Mena Barreto`,
		party: `Brazilian Military Junta of 1930`,
		leaning: leanings.RIGHT,
		tookOffice: `24 October 1930`,
		leftOffice: `3 November 1930`,
	},
	{
		countryId,
		name: `Getúlio Vargas`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `3 November 1930`,
		leftOffice: `10 November 1937`,
	},
	{
		countryId,
		name: `Getúlio Vargas`,
		party: `Estado Novo`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `10 November 1937`,
		leftOffice: `29 October 1945`,
	},
	{
		countryId,
		name: `José Linhares`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `29 October 1945`,
		leftOffice: `30 January 1946`,
	},
	{
		countryId,
		name: `Eurico Gaspar Dutra`,
		party: `Social Democratic Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `31 January 1946`,
		leftOffice: `30 January 1951`,
	},
	{
		countryId,
		name: `Getúlio Vargas`,
		party: `Brazilian Labour Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `31 January 1951`,
		leftOffice: `24 August 1954`,
	},
	{
		countryId,
		name: `João Café Filho`,
		party: `Social Progressive Party`,
		leaning: leanings.RIGHT,
		tookOffice: `24 August 1954`,
		leftOffice: `8 November 1955`,
	},
	{
		countryId,
		name: `Carlos Luz`,
		party: `Social Democratic Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 November 1955`,
		leftOffice: `11 November 1955`,
	},
	{
		countryId,
		name: `Nereu Ramos`,
		party: `Social Democratic Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `11 November 1955`,
		leftOffice: `30 January 1956`,
	},
	{
		countryId,
		name: `Juscelino Kubitschek`,
		party: `Social Democratic Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `31 January 1956`,
		leftOffice: `30 January 1961`,
	},
	{
		countryId,
		name: `Jânio Quadros`,
		party: `National Labour Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `31 January 1961`,
		leftOffice: `25 August 1961`,
	},
	{
		countryId,
		name: `Pascoal Ranieri Mazzilli`,
		party: `Social Democratic Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `25 August 1961`,
		leftOffice: `7 September 1961`,
	},
	{
		countryId,
		name: `João Goulart`,
		party: `Brazilian Labour Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `7 September 1961`,
		leftOffice: `1 April 1964`,
	},
	{
		countryId,
		name: `Pascoal Ranieri Mazzilli`,
		party: `Social Democratic Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 April 1964`,
		leftOffice: `15 April 1964`,
	},
	{
		countryId,
		name: `Alencar Castelo Branco`,
		party: `National Renewal Alliance`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `15 April 1964`,
		leftOffice: `15 March 1967`,
	},
	{
		countryId,
		name: `Artur da Costa e Silva`,
		party: `National Renewal Alliance`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `15 March 1967`,
		leftOffice: `31 August 1969`,
	},
	{
		countryId,
		name: `Augusto Hamann Rademaker Grünewald, Aurélio de Lira Tavares, Márcio Melo`,
		party: `Brazilian Military Junta of 1969`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `31 August 1969`,
		leftOffice: `30 October 1969`,
	},
	{
		countryId,
		name: `Emílio Garrastazu Médici`,
		party: `National Renewal Alliance`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `30 October 1969`,
		leftOffice: `15 March 1974`,
	},
	{
		countryId,
		name: `Ernesto Geisel`,
		party: `National Renewal Alliance`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `15 March 1974`,
		leftOffice: `15 March 1979`,
	},
	{
		countryId,
		name: `João Figueiredo`,
		party: `Democratic Social Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `15 March 1979`,
		leftOffice: `15 March 1985`,
	},
	{
		countryId,
		name: `José Sarney`,
		party: `Brazilian Democratic Movement`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `15 March 1985`,
		leftOffice: `15 March 1990`,
	},
	{
		countryId,
		name: `Fernando Collor de Mello`,
		party: `Christian Labour Party`,
		leaning: leanings.RIGHT,
		tookOffice: `15 March 1990`,
		leftOffice: `2 October 1992`,
	},
	{
		countryId,
		name: `Itamar Augusto Cautiero Franco`,
		party: `Brazilian Democratic Movement`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `2 October 1992`,
		leftOffice: `1 January 1995`,
	},
	{
		countryId,
		name: `Fernando Henrique Cardoso`,
		party: `Brazilian Social Democracy Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 January 1995`,
		leftOffice: `31 December 2002`,
	},
	{
		countryId,
		name: `Luiz Inácio Lula da Silva`,
		party: `Workers' Party`,
		leaning: leanings.LEFT,
		tookOffice: `1 January 2003`,
		leftOffice: `31 December 2010`,
	},
	{
		countryId,
		name: `Dilma Rousseff`,
		party: `Workers' Party`,
		leaning: leanings.LEFT,
		tookOffice: `1 January 2011`,
		leftOffice: `12 May 2016`,
	},
	{
		countryId,
		name: `Michel Temer`,
		party: `Brazilian Democratic Movement`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `12 May 2016`,
		leftOffice: `1 January 2019`,
	},
	{
		countryId,
		name: `Jair Bolsonaro`,
		party: `Social Liberal Party Brazil, Independent, Liberal Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `1 January 2019`,
		leftOffice: `1 January 2023`,
	},
	{
		countryId,
		name: `uiz Inácio Lula da Silva`,
		party: `Workers' Party`,
		leaning: leanings.LEFT,
		tookOffice: `1 January 2023`,
		leftOffice: null,
	},
];
