import type { LeaderNoId } from '../../app/data/types';
import { leanings } from '../../app/data/types';

export const source = `https://en.wikipedia.org/wiki/List_of_presidents_of_Chile`;

const countryId = 22;

export const chile: LeaderNoId[] = [
	{
		name: 'Mateo de Toro y Zambrano',
		party: null,
		leaning: null,
		tookOffice: '18 September 1810',
		leftOffice: '26 February 1811',
	},
	{
		name: 'Juan Martínez de Rozas',
		party: null,
		leaning: null,
		tookOffice: '27 February 1811',
		leftOffice: '2 April 1811',
	},
	{
		name: 'Fernando Márquez de la Plata',
		party: null,
		leaning: null,
		tookOffice: '2 April 1811',
		leftOffice: '4 July 1811',
	},
	{
		name: 'Juan Antonio Ovalle',
		party: null,
		leaning: null,
		tookOffice: '4 July 1811',
		leftOffice: '20 July 1811',
	},
	{
		name: 'Martín Calvo Encalada',
		party: null,
		leaning: null,
		tookOffice: '20 July 1811',
		leftOffice: '4 September 1811',
	},
	{
		name: 'Juan Enrique Rosales ',
		party: null,
		leaning: null,
		tookOffice: '4 September 1811',
		leftOffice: '16 November 1811',
	},
	{
		name: 'José Miguel Carrera',
		party: null,
		leaning: null,
		tookOffice: '16 November 1811',
		leftOffice: '8 April 1812',
	},
	{
		name: 'José Santiago Portales y Larraín',
		party: null,
		leaning: null,
		tookOffice: '8 April 1812',
		leftOffice: '6 August 1812',
	},
	{
		name: 'Pedro José Prado Jaraquemada',
		party: null,
		leaning: null,
		tookOffice: '6 August 1812',
		leftOffice: '6 December 1812',
	},
	{
		name: 'José Miguel Carrera',
		party: null,
		leaning: null,
		tookOffice: '6 December 1812',
		leftOffice: '30 March 1813',
	},
	{
		name: 'Juan José Carrera',
		party: null,
		leaning: null,
		tookOffice: '30 March 1813',
		leftOffice: '13 April 1813',
	},
	{
		name: 'Francisco Antonio Pérez',
		party: null,
		leaning: null,
		tookOffice: '13 April 1813',
		leftOffice: '23 August 1813',
	},
	{
		name: 'José Miguel Infante',
		party: null,
		leaning: null,
		tookOffice: '23 August 1813',
		leftOffice: '11 January 1814',
	},
	{
		name: 'Agustín Eyzaguirre',
		party: null,
		leaning: null,
		tookOffice: '11 January 1814',
		leftOffice: '7 March 1814',
	},
	{
		name: 'Antonio José de Irisarri',
		party: null,
		leaning: null,
		tookOffice: '7 March 1814',
		leftOffice: '14 March 1814',
	},
	{
		name: 'Francisco de la Lastra',
		party: null,
		leaning: null,
		tookOffice: '14 March 1814',
		leftOffice: '23 July 1814',
	},
	{
		name: 'José Miguel Carrera',
		party: null,
		leaning: null,
		tookOffice: '23 July 1814',
		leftOffice: '2 October 1814',
	},
	{
		name: 'Mariano Osorio',
		party: null,
		leaning: null,
		tookOffice: '3 October 1814',
		leftOffice: '26 December 1815',
	},
	{
		name: 'Casimiro Marcó del Pont',
		party: null,
		leaning: null,
		tookOffice: '26 December 1815',
		leftOffice: '12 February 1817',
	},
	{
		name: "Bernardo O'Higgins",
		party: null,
		leaning: null,
		tookOffice: '16 February 1817',
		leftOffice: '28 January 1823',
	},
	{
		name: 'Agustín Eyzaguirre',
		party: null,
		leaning: null,
		tookOffice: '28 January 1823',
		leftOffice: '4 April 1823',
	},
	{
		name: 'Ramón Freire',
		party: null,
		leaning: null,
		tookOffice: '4 April 1823',
		leftOffice: '9 July 1826',
	},
	{
		name: 'Manuel Blanco Encalada',
		party: 'Independent',
		leaning: null,
		tookOffice: '9 July 1826',
		leftOffice: '9 September 1826',
	},
	{
		name: 'Agustín Eyzaguirre',
		party: 'Independent',
		leaning: null,
		tookOffice: '9 September 1826',
		leftOffice: '25 January 1827',
	},
	{
		name: 'Ramón Freire',
		party: 'Pipiolos',
		leaning: null,
		tookOffice: '25 January 1827',
		leftOffice: '15 February 1827',
	},
	{
		name: 'Francisco Antonio Pinto',
		party: 'Pipiolos',
		leaning: null,
		tookOffice: '8 May 1827',
		leftOffice: '16 July 1829',
	},
	{
		name: 'Francisco Ramón Vicuña',
		party: 'Pipiolos',
		leaning: null,
		tookOffice: '16 July 1829',
		leftOffice: '19 October 1829',
	},
	{
		name: 'Francisco Antonio Pinto',
		party: 'Pipiolos',
		leaning: null,
		tookOffice: '19 October 1829',
		leftOffice: '2 November 1829',
	},
	{
		name: 'Francisco Ramón Vicuña',
		party: 'Pipiolos',
		leaning: null,
		tookOffice: '2 November 1829',
		leftOffice: '7 November 1829',
	},
	{
		name: 'Ramón Freire',
		party: 'Pipiolos',
		leaning: null,
		tookOffice: '7 November 1829',
		leftOffice: '8 November 1829',
	},
	{
		name: 'Francisco Ramón Vicuña',
		party: 'Pipiolos',
		leaning: null,
		tookOffice: '8 November 1829',
		leftOffice: '7 December 1829',
	},
	{
		name: 'José Tomás Ovalle y Bezanilla',
		party: 'Pelucones',
		leaning: null,
		tookOffice: '24 December 1829',
		leftOffice: '18 February 1830',
	},
	{
		name: 'Francisco Ruiz-Tagle Portales',
		party: 'Pelucones',
		leaning: null,
		tookOffice: '18 February 1830',
		leftOffice: '1 April 1830',
	},
	{
		name: 'José Tomás Ovalle y Bezanilla',
		party: 'Pelucones',
		leaning: null,
		tookOffice: '1 April 1830',
		leftOffice: '8 March 1831',
	},
	{
		name: 'Fernando Errázuriz Aldunate',
		party: 'Pelucones',
		leaning: null,
		tookOffice: '8 March 1831',
		leftOffice: '18 September 1831',
	},
	{
		name: 'Joaquín Prieto',
		party: 'Pelucones',
		leaning: null,
		tookOffice: '18 September 1831',
		leftOffice: '18 September 1836',
	},
	{
		name: 'Joaquín Prieto',
		party: 'Conservative party',
		leaning: 'Centre-right',
		tookOffice: '18 September 1836',
		leftOffice: '18 September 1841',
	},
	{
		name: 'Manuel Bulnes',
		party: 'Conservative party',
		leaning: 'Centre-right',
		tookOffice: '18 September 1841',
		leftOffice: '18 September 1851',
	},
	{
		name: 'Manuel Montt',
		party: 'Conservative party',
		leaning: 'Centre-right',
		tookOffice: '18 September 1851',
		leftOffice: '18 September 1856',
	},
	{
		name: 'Manuel Montt',
		party: 'National party',
		leaning: 'Centre-right',
		tookOffice: '18 September 1856',
		leftOffice: '18 September 1861',
	},
	{
		name: 'José Joaquín Pérez',
		party: 'National party',
		leaning: 'Centre-right',
		tookOffice: '18 September 1861',
		leftOffice: '18 September 1871',
	},
	{
		name: 'Federico Errázuriz Zañartu',
		party: 'Liberal party',
		leaning: null,
		tookOffice: '18 September 1871',
		leftOffice: '18 September 1876',
	},
	{
		name: 'Aníbal Pinto',
		party: 'Liberal party',
		leaning: null,
		tookOffice: '18 September 1876',
		leftOffice: '18 September 1881',
	},
	{
		name: 'Domingo Santa María',
		party: 'Liberal party',
		leaning: null,
		tookOffice: '18 September 1881',
		leftOffice: '18 September 1886',
	},
	{
		name: 'José Manuel Balmaceda',
		party: 'Liberal party',
		leaning: null,
		tookOffice: '18 September 1886',
		leftOffice: '29 August 1891',
	},
	{
		name: 'Claudio Vicuña Guerrero',
		party: 'Liberal party',
		leaning: null,
		tookOffice: '29 August 1891',
		leftOffice: '29 August 1891',
	},
	{
		name: 'Manuel Baquedano',
		party: 'Military',
		leaning: null,
		tookOffice: '29 August 1891',
		leftOffice: '31 August 1891',
	},
	{
		name: 'Jorge Montt',
		party: 'Military',
		leaning: null,
		tookOffice: '31 August 1891',
		leftOffice: '26 December 1891',
	},
	{
		name: 'Jorge Montt',
		party: 'Independent',
		leaning: null,
		tookOffice: '26 December 1891',
		leftOffice: '18 September 1896',
	},
	{
		name: 'Federico Errázuriz Echaurren',
		party: 'Liberal party',
		leaning: null,
		tookOffice: '18 September 1896',
		leftOffice: '12 July 1901',
	},
	{
		name: 'Aníbal Zañartu',
		party: 'Liberal party',
		leaning: null,
		tookOffice: '12 July 1901',
		leftOffice: '18 September 1901',
	},
	{
		name: 'Germán Riesco',
		party: 'Liberal party',
		leaning: null,
		tookOffice: '18 September 1901',
		leftOffice: '18 September 1906',
	},
	{
		name: 'Pedro Montt',
		party: 'National party',
		leaning: 'Centre-right',
		tookOffice: '18 September 1906',
		leftOffice: '16 August 1910',
	},
	{
		name: 'Elías Fernández Albano',
		party: 'National party',
		leaning: 'Centre-right',
		tookOffice: '16 August 1910',
		leftOffice: '6 September 1910',
	},
	{
		name: 'Emiliano Figueroa',
		party: 'Liberal Democratic party',
		leaning: 'Centre',
		tookOffice: '6 September 1910',
		leftOffice: '23 December 1910',
	},
	{
		name: 'Ramón Barros Luco',
		party: 'Liberal party',
		leaning: null,
		tookOffice: '23 December 1910',
		leftOffice: '23 December 1915',
	},
	{
		name: 'Juan Luis Sanfuentes',
		party: 'Liberal Democratic party',
		leaning: 'Centre',
		tookOffice: '23 December 1915',
		leftOffice: '23 December 1920',
	},
	{
		name: 'Arturo Alessandri',
		party: 'Liberal party',
		leaning: null,
		tookOffice: '23 December 1920',
		leftOffice: '12 September 1924',
	},
	{
		name: 'Luis Altamirano',
		party: 'Military',
		leaning: null,
		tookOffice: '12 September 1924',
		leftOffice: '23 January 1925',
	},
	{
		name: 'Pedro Dartnell',
		party: 'Military',
		leaning: null,
		tookOffice: '23 January 1925',
		leftOffice: '27 January 1925',
	},
	{
		name: 'Emilio Bello Codesido',
		party: 'Liberal Democratic party',
		leaning: 'Centre',
		tookOffice: '27 January 1925',
		leftOffice: '12 March 1925',
	},
	{
		name: 'Arturo Alessandri',
		party: 'Liberal party',
		leaning: null,
		tookOffice: '12 March 1925',
		leftOffice: '1 October 1925',
	},
	{
		name: 'Luis Barros Borgoño',
		party: 'Liberal party',
		leaning: null,
		tookOffice: '1 October 1925',
		leftOffice: '23 December 1925',
	},
	{
		name: 'Emiliano Figueroa',
		party: 'Liberal Democratic party',
		leaning: 'Centre',
		tookOffice: '23 December 1925',
		leftOffice: '10 May 1927',
	},
	{
		name: 'Carlos Ibáñez del Campo',
		party: 'Independent',
		leaning: null,
		tookOffice: '10 May 1927',
		leftOffice: '26 July 1931',
	},
	{
		name: 'Pedro Opaso',
		party: 'Liberal Democratic party',
		leaning: 'Centre',
		tookOffice: '26 July 1931',
		leftOffice: '27 July 1931',
	},
	{
		name: 'Juan Esteban Montero',
		party: 'Radical party of Chile',
		leaning: 'Centre-left',
		tookOffice: '27 July 1931',
		leftOffice: '20 August 1931',
	},
	{
		name: 'Manuel Trucco',
		party: 'Radical party of Chile',
		leaning: 'Centre-left',
		tookOffice: '20 August 1931',
		leftOffice: '15 November 1931',
	},
	{
		name: 'Juan Esteban Montero',
		party: 'Radical party of Chile',
		leaning: 'Centre-left',
		tookOffice: '15 November 1931',
		leftOffice: '4 June 1932',
	},
	{
		name: 'Arturo Puga',
		party: 'Military',
		leaning: null,
		tookOffice: '4 June 1932',
		leftOffice: '16 June 1932',
	},
	{
		name: 'Carlos Dávila',
		party: 'Socialist party of Chile',
		leaning: 'Centre-left',
		tookOffice: '16 June 1932',
		leftOffice: '13 September 1932',
	},
	{
		name: 'Bartolomé Blanche',
		party: 'Military',
		leaning: null,
		tookOffice: '13 September 1932',
		leftOffice: '2 October 1932',
	},
	{
		name: 'Abraham Oyanedel',
		party: 'Independent',
		leaning: null,
		tookOffice: '2 October 1932',
		leftOffice: '24 December 1932',
	},
	{
		countryId,
		name: `Bartolomé Blanche`,
		party: `Military of Chile`,
		leaning: leanings.RIGHT,
		tookOffice: `13 September 1932`,
		leftOffice: `2 October 1932`,
	},
	{
		countryId,
		name: `Abraham Oyanedel`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `2 October 1932`,
		leftOffice: `24 December 1932`,
	},
	{
		countryId,
		name: `Arturo Alessandri`,
		party: `Liberal Party of Chile`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `24 December 1932`,
		leftOffice: `24 December 1938`,
	},
	{
		countryId,
		name: `Pedro Aguirre Cerda`,
		party: `Radical Party of Chile`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `24 December 1938`,
		leftOffice: `25 November 1941`,
	},
	{
		countryId,
		name: `Jerónimo Méndez`,
		party: `Radical Party of Chile`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `25 November 1941`,
		leftOffice: `2 April 1942`,
	},
	{
		countryId,
		name: `Juan Antonio Ríos`,
		party: `Radical Party of Chile`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `2 April 1942`,
		leftOffice: `27 June 1946`,
	},
	{
		countryId,
		name: `Alfredo Duhalde`,
		party: `Radical Party of Chile`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `27 June 1946`,
		leftOffice: `3 August 1946`,
	},
	{
		countryId,
		name: `Vicente Merino`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `3 August 1946`,
		leftOffice: `13 August 1946`,
	},
	{
		countryId,
		name: `Alfredo Duhalde`,
		party: `Radical Party of Chile`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `13 August 1946`,
		leftOffice: `17 October 1946`,
	},
	{
		countryId,
		name: `Juan Antonio Iribarren`,
		party: `Radical Party of Chile`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `17 October 1946`,
		leftOffice: `3 November 1946`,
	},
	{
		countryId,
		name: `Gabriel González Videla`,
		party: `Radical Party of Chile`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `3 November 1946`,
		leftOffice: `3 November 1952`,
	},
	{
		countryId,
		name: `Carlos Ibáñez del Campo`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `3 November 1952`,
		leftOffice: `3 November 1958`,
	},
	{
		countryId,
		name: `Jorge Alessandri`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `3 November 1958`,
		leftOffice: `3 November 1964`,
	},
	{
		countryId,
		name: `Eduardo Frei Montalva`,
		party: `Christian Democratic Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `3 November 1964`,
		leftOffice: `3 November 1970`,
	},
	{
		countryId,
		name: `Salvador Allende`,
		party: `Socialist Party`,
		leaning: leanings.LEFT,
		tookOffice: `3 November 1970`,
		leftOffice: `11 September 1973`,
	},
	{
		countryId,
		name: `Augusto Pinochet`,
		party: `Military of Chile`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `11 September 1973`,
		leftOffice: `11 March 1990`,
	},
	{
		countryId,
		name: `Patricio Aylwin`,
		party: `Christian Democratic Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `11 March 1990`,
		leftOffice: `11 March 1994`,
	},
	{
		countryId,
		name: `Eduardo Frei Ruiz-Tagle`,
		party: `Christian Democratic Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `11 March 1994`,
		leftOffice: `11 March 2000`,
	},
	{
		countryId,
		name: `Ricardo Lagos`,
		party: `Party for Democracy`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `11 March 2000`,
		leftOffice: `11 March 2006`,
	},
	{
		countryId,
		name: `Michelle Bachelet`,
		party: `Socialist Party`,
		leaning: leanings.LEFT,
		tookOffice: `11 March 2006`,
		leftOffice: `11 March 2010`,
	},
	{
		countryId,
		name: `Sebastián Piñera`,
		party: `National Renewal`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `11 March 2010`,
		leftOffice: `11 March 2014`,
	},
	{
		countryId,
		name: `Michelle Bachelet`,
		party: `Socialist Party`,
		leaning: leanings.LEFT,
		tookOffice: `11 March 2014`,
		leftOffice: `11 March 2018`,
	},
	{
		countryId,
		name: `Sebastián Piñera`,
		party: `Chile Vamos`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `11 March 2018`,
		leftOffice: `11 March 2022`,
	},
	{
		countryId,
		name: `Gabriel Boric`,
		party: `Social Convergence`,
		leaning: leanings.LEFT,
		tookOffice: `11 March 2022`,
		leftOffice: null,
	},
];
