import type { LeaderNoId } from '../../app/data/types';
import { leanings } from '../../app/data/types';

export const source = `https://en.wikipedia.org/wiki/List_of_presidents_of_Chile`;

const countryId = 22;

export const chile: LeaderNoId[] = [
	{
		countryId,
		name: `Bartolomé Blanche`,
		party: `Military of Chile`,
		leaning: leanings.RIGHT,
		tookOffice: `13 September 1932`,
		leftOffice: `2 October 1932`,
	},
	{
		countryId,
		name: `Abraham Oyanedel`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `2 October 1932`,
		leftOffice: `24 December 1932`,
	},
	{
		countryId,
		name: `Arturo Alessandri`,
		party: `Liberal Party of Chile`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `24 December 1932`,
		leftOffice: `24 December 1938`,
	},
	{
		countryId,
		name: `Pedro Aguirre Cerda`,
		party: `Radical Party of Chile`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `24 December 1938`,
		leftOffice: `25 November 1941`,
	},
	{
		countryId,
		name: `Jerónimo Méndez`,
		party: `Radical Party of Chile`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `25 November 1941`,
		leftOffice: `2 April 1942`,
	},
	{
		countryId,
		name: `Juan Antonio Ríos`,
		party: `Radical Party of Chile`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `2 April 1942`,
		leftOffice: `27 June 1946`,
	},
	{
		countryId,
		name: `Alfredo Duhalde`,
		party: `Radical Party of Chile`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `27 June 1946`,
		leftOffice: `3 August 1946`,
	},
	{
		countryId,
		name: `Vicente Merino`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `3 August 1946`,
		leftOffice: `13 August 1946`,
	},
	{
		countryId,
		name: `Alfredo Duhalde`,
		party: `Radical Party of Chile`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `13 August 1946`,
		leftOffice: `17 October 1946`,
	},
	{
		countryId,
		name: `Juan Antonio Iribarren`,
		party: `Radical Party of Chile`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `17 October 1946`,
		leftOffice: `3 November 1946`,
	},
	{
		countryId,
		name: `Gabriel González Videla`,
		party: `Radical Party of Chile`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `3 November 1946`,
		leftOffice: `3 November 1952`,
	},
	{
		countryId,
		name: `Carlos Ibáñez del Campo`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `3 November 1952`,
		leftOffice: `3 November 1958`,
	},
	{
		countryId,
		name: `Jorge Alessandri`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `3 November 1958`,
		leftOffice: `3 November 1964`,
	},
	{
		countryId,
		name: `Eduardo Frei Montalva`,
		party: `Christian Democratic Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `3 November 1964`,
		leftOffice: `3 November 1970`,
	},
	{
		countryId,
		name: `Salvador Allende`,
		party: `Socialist Party`,
		leaning: leanings.LEFT,
		tookOffice: `3 November 1970`,
		leftOffice: `11 September 1973`,
	},
	{
		countryId,
		name: `Augusto Pinochet`,
		party: `Military of Chile`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `11 September 1973`,
		leftOffice: `11 March 1990`,
	},
	{
		countryId,
		name: `Patricio Aylwin`,
		party: `Christian Democratic Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `11 March 1990`,
		leftOffice: `11 March 1994`,
	},
	{
		countryId,
		name: `Eduardo Frei Ruiz-Tagle`,
		party: `Christian Democratic Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `11 March 1994`,
		leftOffice: `11 March 2000`,
	},
	{
		countryId,
		name: `Ricardo Lagos`,
		party: `Party for Democracy`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `11 March 2000`,
		leftOffice: `11 March 2006`,
	},
	{
		countryId,
		name: `Michelle Bachelet`,
		party: `Socialist Party`,
		leaning: leanings.LEFT,
		tookOffice: `11 March 2006`,
		leftOffice: `11 March 2010`,
	},
	{
		countryId,
		name: `Sebastián Piñera`,
		party: `National Renewal`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `11 March 2010`,
		leftOffice: `11 March 2014`,
	},
	{
		countryId,
		name: `Michelle Bachelet`,
		party: `Socialist Party`,
		leaning: leanings.LEFT,
		tookOffice: `11 March 2014`,
		leftOffice: `11 March 2018`,
	},
	{
		countryId,
		name: `Sebastián Piñera`,
		party: `Chile Vamos`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `11 March 2018`,
		leftOffice: `11 March 2022`,
	},
	{
		countryId,
		name: `Gabriel Boric`,
		party: `Social Convergence`,
		leaning: leanings.LEFT,
		tookOffice: `11 March 2022`,
		leftOffice: null,
	},
];
