import type { LeaderNoId } from '../../app/data/types';
import { leanings } from '../../app/data/types';

export const source = `https://www.mapsofworld.com/list-of/presidents-colombia/`;

const countryId = 10;

export const colombia: LeaderNoId[] = [
	{
		countryId,
		name: `Gustavo Francisco Petro Urrego`,
		party: `Humane Colombia`,
		leaning: leanings.LEFT,
		tookOffice: `7 August 2022`,
		leftOffice: null,
	},
	{
		countryId,
		name: `Iván Duque Márquez`,
		party: `Democratic Center`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `7 August 2018`,
		leftOffice: `7 August 2022`,
	},
	{
		countryId,
		name: `Juan Manuel Santos Calderón`,
		party: `Union Party for the People`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 2010`,
		leftOffice: `7 August 2018`,
	},
	{
		countryId,
		name: `Álvaro Uribe`,
		party: `Colombia First`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 2002`,
		leftOffice: `7 August 2010`,
	},
	{
		countryId,
		name: `Andrés Pastrana Arango`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1998`,
		leftOffice: `7 August 2002`,
	},
	{
		countryId,
		name: `Ernesto Samper Pizano`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 1994`,
		leftOffice: `7 August 1998`,
	},
	{
		countryId,
		name: `César Gaviria`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 1990`,
		leftOffice: `7 August 1994`,
	},
	{
		countryId,
		name: `Virgilio Barco Vargas`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 1986`,
		leftOffice: `7 August 1990`,
	},
	{
		countryId,
		name: `Belisario Betancur Cuartas`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1982`,
		leftOffice: `7 August 1986`,
	},
	{
		countryId,
		name: `Julio César Turbay Ayala`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 1978`,
		leftOffice: `7 August 1982`,
	},
	{
		countryId,
		name: `Alfonso López Michelsen`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 1974`,
		leftOffice: `7 August 1978`,
	},
	{
		countryId,
		name: `Misael Pastrana Borrero`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1970`,
		leftOffice: `7 August 1974`,
	},
	{
		countryId,
		name: `Carlos Lleras Restrepo`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 1966`,
		leftOffice: `7 August 1970`,
	},
	{
		countryId,
		name: `Guillermo León Valencia`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1962`,
		leftOffice: `7 August 1966`,
	},
	{
		countryId,
		name: `Alberto Lleras Camargo`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 1958`,
		leftOffice: `7 August 1962`,
	},
	{
		countryId,
		name: `Military Junta`,
		party: `Military Forces of Colombia`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `10 May 1957`,
		leftOffice: `7 August 1958`,
	},
	{
		countryId,
		name: `Gustavo Rojas Pinilla`,
		party: `National Popular Alliance`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `13 June 1953`,
		leftOffice: `10 May 1957`,
	},
	{
		countryId,
		name: `Roberto Urdaneta Arbeláez`,
		party: `Colombian Conservative Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `5 November 1951`,
		leftOffice: `13 June 1953`,
	},
	{
		countryId,
		name: `Laureano Gómez`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1950`,
		leftOffice: `5 November 1951`,
	},
	{
		countryId,
		name: `Mariano Ospina Pérez`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1946`,
		leftOffice: `7 August 1950`,
	},
	{
		countryId,
		name: `Alfonso López Pumarejo`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 1942`,
		leftOffice: `7 August 1946`,
	},
	{
		countryId,
		name: `Eduardo Santos Montejo`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 1938`,
		leftOffice: `7 August 1942`,
	},
	{
		countryId,
		name: `Alfonso López Pumarejo`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 1934`,
		leftOffice: `7 August 1938`,
	},
	{
		countryId,
		name: `Enrique Olaya Herrera`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 1930`,
		leftOffice: `7 August 1934`,
	},
	{
		countryId,
		name: `Miguel Abadía Méndez`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1926`,
		leftOffice: `7 August 1930`,
	},
	{
		countryId,
		name: `Pedro Nel Ospina`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1922`,
		leftOffice: `7 August 1926`,
	},
	{
		countryId,
		name: `Jorge Holguín`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `11 November 1921`,
		leftOffice: `7 August 1922`,
	},
	{
		countryId,
		name: `Marco Fidel Suárez`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1918`,
		leftOffice: `11 November 1921`,
	},
	{
		countryId,
		name: `José Vicente Concha`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1914`,
		leftOffice: `7 August 1918`,
	},
	{
		countryId,
		name: `Carlos Eugenio Restrepo`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1910`,
		leftOffice: `7 August 1914`,
	},
	{
		countryId,
		name: `Ramón González Valencia`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1909`,
		leftOffice: `7 August 1910`,
	},
	{
		countryId,
		name: `Rafael Reyes Prieto`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1904`,
		leftOffice: `27 July 1909`,
	},
	{
		countryId,
		name: `José Manuel Marroquín`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `31 July 1900`,
		leftOffice: `7 August 1904`,
	},
	{
		countryId,
		name: `Manuel Antonio Sanclemente`,
		party: `National Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 1898`,
		leftOffice: `31 July 1900`,
	},
	{
		countryId,
		name: `Miguel Antonio Caro`,
		party: `National Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `18 September 1894`,
		leftOffice: `7 August 1898`,
	},
	{
		countryId,
		name: `Rafael Núñez Moledo`,
		party: `National Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 April 1886`,
		leftOffice: `18 September 1894`,
	},
];
