import type { LeaderNoId } from '../../app/data/types';
import { leanings } from '../../app/data/types';

export const source = `https://www.mapsofworld.com/list-of/presidents-colombia/`;

const countryId = 10;

export const colombia: LeaderNoId[] = [
	{
		name: 'Simón Bolívar y Palacios',
		party: null,
		leaning: null,
		tookOffice: '15 February 1819',
		leftOffice: '4 May 1830',
	},
	{
		name: 'Joaquín de Mosquera y Arboleda',
		party: null,
		leaning: null,
		tookOffice: '4 May 1830',
		leftOffice: '4 September 1830',
	},
	{
		name: 'Rafael Urdaneta y Faría',
		party: null,
		leaning: null,
		tookOffice: '4 May 1830',
		leftOffice: '30 April 1831',
	},
	{
		name: 'vacant',
		party: null,
		leaning: null,
		tookOffice: '30 April 1831',
		leftOffice: '10 March 1832',
	},
	{
		name: 'Francisco de Paula Santander y Omaña',
		party: null,
		leaning: null,
		tookOffice: '10 March 1832',
		leftOffice: '1 April 1837',
	},
	{
		name: 'José Ignacio de Márquez Barreto',
		party: null,
		leaning: null,
		tookOffice: '1 April 1837',
		leftOffice: '1 April 1841',
	},
	{
		name: 'Pedro Alcántara Herrán Martínez',
		party: null,
		leaning: null,
		tookOffice: '1 April 1841',
		leftOffice: '1 April 1845',
	},
	{
		name: 'Tomás Cipriano de Mosquera y Arboleda',
		party: null,
		leaning: null,
		tookOffice: '1 April 1845',
		leftOffice: '1 April 1849',
	},
	{
		name: 'José Hilario López Valdéz',
		party: 'Colombian Liberal party',
		leaning: 'centre-left',
		tookOffice: '1 April 1849',
		leftOffice: '1 April 1853',
	},
	{
		name: 'José María Obando del Campo',
		party: 'Colombian Liberal party',
		leaning: 'centre-left',
		tookOffice: '1 April 1853',
		leftOffice: '17 April 1854',
	},
	{
		name: 'José María Melo y Ortiz',
		party: 'Colombian Liberal party',
		leaning: 'centre-left',
		tookOffice: '17 April 1854',
		leftOffice: '4 December 1854',
	},
	{
		name: 'vacant',
		party: null,
		leaning: null,
		tookOffice: '4 December 1854',
		leftOffice: '1 April 1857',
	},
	{
		name: 'Mariano Ospina Rodríguez',
		party: 'Colombian Conservative party',
		leaning: 'Centre-right',
		tookOffice: '1 April 1857',
		leftOffice: '1 April 1861',
	},
	{
		name: 'Bartolomé Calvo Díaz',
		party: 'Colombian Conservative party',
		leaning: 'Centre-right',
		tookOffice: '1 April 1861',
		leftOffice: '18 July 1861',
	},
	{
		name: 'Juan José Nieto Gil',
		party: 'Colombian Liberal party',
		leaning: 'centre-left',
		tookOffice: '25 January 1861',
		leftOffice: '18 July 1861',
	},
	{
		name: 'Tomás Cipriano de Mosquera y Arboleda',
		party: 'Colombian Liberal party',
		leaning: 'centre-left',
		tookOffice: '18 July 1861',
		leftOffice: '4 February 1863',
	},
	{
		name: 'Tomás Cipriano de Mosquera y Arboleda',
		party: 'Colombian Liberal party',
		leaning: 'centre-left',
		tookOffice: '14 May 1863',
		leftOffice: '1 April 1864',
	},
	{
		name: 'Manuel Murillo Toro',
		party: 'Colombian Liberal party',
		leaning: 'centre-left',
		tookOffice: '1 April 1864',
		leftOffice: '1 April 1866',
	},
	{
		name: 'Tomás Cipriano de Mosquera y Arboleda',
		party: 'Colombian Liberal party',
		leaning: 'centre-left',
		tookOffice: '1 April 1866',
		leftOffice: '23 May 1867',
	},
	{
		name: 'Santos Acosta Castillo',
		party: 'Colombian Liberal party',
		leaning: 'centre-left',
		tookOffice: '23 May 1867',
		leftOffice: '1 April 1868',
	},
	{
		name: 'Santos Gutiérrez Prieto',
		party: 'Colombian Liberal party',
		leaning: 'centre-left',
		tookOffice: '1 April 1868',
		leftOffice: '1 April 1870',
	},
	{
		name: 'Eustorgio Salgar Moreno',
		party: 'Colombian Liberal party',
		leaning: 'centre-left',
		tookOffice: '1 April 1870',
		leftOffice: '1 April 1872',
	},
	{
		name: 'Manuel Murillo Toro',
		party: 'Colombian Liberal party',
		leaning: 'centre-left',
		tookOffice: '1 April 1872',
		leftOffice: '1 April 1874',
	},
	{
		name: 'Santiago Pérez de Manosalbas',
		party: 'Colombian Liberal party',
		leaning: 'centre-left',
		tookOffice: '1 April 1874',
		leftOffice: '1 April 1876',
	},
	{
		name: 'Aquileo Parra Gómez',
		party: 'Colombian Liberal party',
		leaning: 'centre-left',
		tookOffice: '1 April 1876',
		leftOffice: '1 April 1878',
	},
	{
		name: 'Julián Trujillo Largacha',
		party: 'Colombian Liberal party',
		leaning: 'centre-left',
		tookOffice: '1 April 1878',
		leftOffice: '1 April 1880',
	},
	{
		name: 'Rafael Núñez Moledo',
		party: 'Colombian Liberal party',
		leaning: 'centre-left',
		tookOffice: '1 April 1880',
		leftOffice: '1 April 1882',
	},
	{
		name: 'Rafael Núñez MoledoFrancisco Javier Zaldúa y Racines',
		party: 'Colombian Liberal party',
		leaning: 'centre-left',
		tookOffice: '1 April 1882',
		leftOffice: '21 December 1882',
	},
	{
		name: 'José Eusebio Otálora Martínez',
		party: 'Colombian Liberal party',
		leaning: 'centre-left',
		tookOffice: '21 December 1882',
		leftOffice: '1 April 1884',
	},
	{
		name: 'Rafael Núñez Moledo',
		party: 'Colombian Liberal party',
		leaning: 'centre-left',
		tookOffice: '1 April 1884',
		leftOffice: '1 April 1886',
	},
	{
		name: 'Rafael Núñez Moledo',
		party: 'National party (Colombia)',
		leaning: 'Centre',
		tookOffice: '1 April 1886',
		leftOffice: '18 September 1894',
	},
	{
		name: 'Miguel Antonio Caro Tobar',
		party: 'National party (Colombia)',
		leaning: 'Centre',
		tookOffice: '18 September 1894',
		leftOffice: '7 August 1898',
	},
	// TODO REVERSE ORDER
	{
		countryId,
		name: `Gustavo Francisco Petro Urrego`,
		party: `Humane Colombia`,
		leaning: leanings.LEFT,
		tookOffice: `7 August 2022`,
		leftOffice: null,
	},
	{
		countryId,
		name: `Iván Duque Márquez`,
		party: `Democratic Center`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `7 August 2018`,
		leftOffice: `7 August 2022`,
	},
	{
		countryId,
		name: `Juan Manuel Santos Calderón`,
		party: `Union Party for the People`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 2010`,
		leftOffice: `7 August 2018`,
	},
	{
		countryId,
		name: `Álvaro Uribe`,
		party: `Colombia First`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 2002`,
		leftOffice: `7 August 2010`,
	},
	{
		countryId,
		name: `Andrés Pastrana Arango`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1998`,
		leftOffice: `7 August 2002`,
	},
	{
		countryId,
		name: `Ernesto Samper Pizano`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 1994`,
		leftOffice: `7 August 1998`,
	},
	{
		countryId,
		name: `César Gaviria`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 1990`,
		leftOffice: `7 August 1994`,
	},
	{
		countryId,
		name: `Virgilio Barco Vargas`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 1986`,
		leftOffice: `7 August 1990`,
	},
	{
		countryId,
		name: `Belisario Betancur Cuartas`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1982`,
		leftOffice: `7 August 1986`,
	},
	{
		countryId,
		name: `Julio César Turbay Ayala`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 1978`,
		leftOffice: `7 August 1982`,
	},
	{
		countryId,
		name: `Alfonso López Michelsen`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 1974`,
		leftOffice: `7 August 1978`,
	},
	{
		countryId,
		name: `Misael Pastrana Borrero`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1970`,
		leftOffice: `7 August 1974`,
	},
	{
		countryId,
		name: `Carlos Lleras Restrepo`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 1966`,
		leftOffice: `7 August 1970`,
	},
	{
		countryId,
		name: `Guillermo León Valencia`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1962`,
		leftOffice: `7 August 1966`,
	},
	{
		countryId,
		name: `Alberto Lleras Camargo`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 1958`,
		leftOffice: `7 August 1962`,
	},
	{
		countryId,
		name: `Military Junta`,
		party: `Military Forces of Colombia`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `10 May 1957`,
		leftOffice: `7 August 1958`,
	},
	{
		countryId,
		name: `Gustavo Rojas Pinilla`,
		party: `National Popular Alliance`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `13 June 1953`,
		leftOffice: `10 May 1957`,
	},
	{
		countryId,
		name: `Roberto Urdaneta Arbeláez`,
		party: `Colombian Conservative Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `5 November 1951`,
		leftOffice: `13 June 1953`,
	},
	{
		countryId,
		name: `Laureano Gómez`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1950`,
		leftOffice: `5 November 1951`,
	},
	{
		countryId,
		name: `Mariano Ospina Pérez`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1946`,
		leftOffice: `7 August 1950`,
	},
	{
		countryId,
		name: `Alfonso López Pumarejo`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 1942`,
		leftOffice: `7 August 1946`,
	},
	{
		countryId,
		name: `Eduardo Santos Montejo`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 1938`,
		leftOffice: `7 August 1942`,
	},
	{
		countryId,
		name: `Alfonso López Pumarejo`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 1934`,
		leftOffice: `7 August 1938`,
	},
	{
		countryId,
		name: `Enrique Olaya Herrera`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 1930`,
		leftOffice: `7 August 1934`,
	},
	{
		countryId,
		name: `Miguel Abadía Méndez`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1926`,
		leftOffice: `7 August 1930`,
	},
	{
		countryId,
		name: `Pedro Nel Ospina`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1922`,
		leftOffice: `7 August 1926`,
	},
	{
		countryId,
		name: `Jorge Holguín`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `11 November 1921`,
		leftOffice: `7 August 1922`,
	},
	{
		countryId,
		name: `Marco Fidel Suárez`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1918`,
		leftOffice: `11 November 1921`,
	},
	{
		countryId,
		name: `José Vicente Concha`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1914`,
		leftOffice: `7 August 1918`,
	},
	{
		countryId,
		name: `Carlos Eugenio Restrepo`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1910`,
		leftOffice: `7 August 1914`,
	},
	{
		countryId,
		name: `Ramón González Valencia`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1909`,
		leftOffice: `7 August 1910`,
	},
	{
		countryId,
		name: `Rafael Reyes Prieto`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1904`,
		leftOffice: `27 July 1909`,
	},
	{
		countryId,
		name: `José Manuel Marroquín`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `31 July 1900`,
		leftOffice: `7 August 1904`,
	},
	{
		countryId,
		name: `Manuel Antonio Sanclemente`,
		party: `National Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 1898`,
		leftOffice: `31 July 1900`,
	},
	{
		countryId,
		name: `Miguel Antonio Caro`,
		party: `National Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `18 September 1894`,
		leftOffice: `7 August 1898`,
	},
	{
		countryId,
		name: `Rafael Núñez Moledo`,
		party: `National Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 April 1886`,
		leftOffice: `18 September 1894`,
	},
];
