import type { LeaderNoId } from '../../app/data/types';
import { leanings } from '../../app/data/types';

export const source = `https://en.wikipedia.org/wiki/List_of_presidents_of_Colombia`;

const countryId = 10;

export const colombia: LeaderNoId[] = [
	{
		countryId,
		name: `Viceroyalty of New Granada`,
		party: `Kingdom of Spain`,
		leaning: leanings.MONARCHY,
		tookOffice: `27 May 1717`,
		leftOffice: `22 May 1810`,
	},
	{
		countryId,
		name: `First Republic of New Granada`,
		party: `First Republic of New Granada`,
		leaning: leanings.MILITARY,
		tookOffice: `22 May 1810`,
		leftOffice: `6 May 1816`,
	},
	{
		countryId,
		name: `Viceroyalty of New Granada`,
		party: `Kingdom of Spain`,
		leaning: leanings.MONARCHY,
		tookOffice: `6 May 1816`,
		leftOffice: `15 February 1819`,
	},
	{
		countryId,
		name: `Simón Bolívar`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `15 February 1819`,
		leftOffice: `4 May 1830`,
	},
	{
		countryId,
		name: `Joaquín de Mosquera y Arboleda`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `4 May 1830`,
		leftOffice: `4 September 1830`,
	},
	{
		countryId,
		name: `Rafael Urdaneta y Faría`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `4 May 1830`,
		leftOffice: `30 April 1831`,
	},
	{
		countryId,
		name: `Domingo Caycedo y Sanz de Santamaría`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `30 April 1831`,
		leftOffice: `21 November 1831`,
	},
	{
		countryId,
		name: `José María Obando del Campo`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `21 November 1831`,
		leftOffice: `10 March 1832`,
	},
	{
		countryId,
		name: `Francisco de Paula Santander y Omaña`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `10 March 1832`,
		leftOffice: `1 April 1837`,
	},
	{
		countryId,
		name: `José Ignacio de Márquez Barreto`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `1 April 1837`,
		leftOffice: `1 April 1841`,
	},
	{
		countryId,
		name: `Pedro Alcántara Herrán Martínez`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `1 April 1841`,
		leftOffice: `1 April 1845`,
	},
	{
		countryId,
		name: `Tomás Cipriano de Mosquera y Arboleda`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `1 April 1845`,
		leftOffice: `1 April 1849`,
	},
	{
		countryId,
		name: `José Hilario López Valdéz`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 April 1849`,
		leftOffice: `1 April 1853`,
	},
	{
		countryId,
		name: `José María Obando del Campo`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 April 1853`,
		leftOffice: `17 April 1854`,
	},
	{
		countryId,
		name: `José María Melo y Ortiz`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `17 April 1854`,
		leftOffice: `4 December 1854`,
	},
	{
		countryId,
		name: `Manuel María Mallarino Ibargüen`,
		party: `Colombian Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `4 December 1854`,
		leftOffice: `1 April 1857`,
	},
	{
		countryId,
		name: `Mariano Ospina Rodríguez`,
		party: `Colombian Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 April 1857`,
		leftOffice: `1 April 1861`,
	},
	{
		countryId,
		name: `Bartolomé Calvo Díaz`,
		party: `Colombian Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 April 1861`,
		leftOffice: `18 July 1861`,
	},
	{
		countryId,
		name: `Juan José Nieto Gil`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `25 January 1861`,
		leftOffice: `18 July 1861`,
	},
	{
		countryId,
		name: `Tomás Cipriano de Mosquera y Arboleda`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `18 July 1861`,
		leftOffice: `4 February 1863`,
	},
	{
		countryId,
		name: `Tomás Cipriano de Mosquera y Arboleda`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `14 May 1863`,
		leftOffice: `1 April 1864`,
	},
	{
		countryId,
		name: `Manuel Murillo Toro`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 April 1864`,
		leftOffice: `1 April 1866`,
	},
	{
		countryId,
		name: `Tomás Cipriano de Mosquera y Arboleda`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 April 1866`,
		leftOffice: `23 May 1867`,
	},
	{
		countryId,
		name: `Santos Acosta Castillo`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `23 May 1867`,
		leftOffice: `1 April 1868`,
	},
	{
		countryId,
		name: `Santos Gutiérrez Prieto`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 April 1868`,
		leftOffice: `1 April 1870`,
	},
	{
		countryId,
		name: `Eustorgio Salgar Moreno`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 April 1870`,
		leftOffice: `1 April 1872`,
	},
	{
		countryId,
		name: `Manuel Murillo Toro`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 April 1872`,
		leftOffice: `1 April 1874`,
	},
	{
		countryId,
		name: `Santiago Pérez de Manosalbas`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 April 1874`,
		leftOffice: `1 April 1876`,
	},
	{
		countryId,
		name: `Aquileo Parra Gómez`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 April 1876`,
		leftOffice: `1 April 1878`,
	},
	{
		countryId,
		name: `Julián Trujillo Largacha`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 April 1878`,
		leftOffice: `1 April 1880`,
	},
	{
		countryId,
		name: `Rafael Núñez Moledo`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 April 1880`,
		leftOffice: `1 April 1882`,
	},
	{
		countryId,
		name: `Rafael Núñez MoledoFrancisco Javier Zaldúa y Racines`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 April 1882`,
		leftOffice: `21 December 1882`,
	},
	{
		countryId,
		name: `José Eusebio Otálora Martínez`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `21 December 1882`,
		leftOffice: `1 April 1884`,
	},
	{
		countryId,
		name: `Rafael Núñez Moledo`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 April 1884`,
		leftOffice: `1 April 1886`,
	},
	{
		countryId,
		name: `Rafael Núñez Moledo`,
		party: `National Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 April 1886`,
		leftOffice: `18 September 1894`,
	},
	{
		countryId,
		name: `Miguel Antonio Caro Tobar`,
		party: `National Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `18 September 1894`,
		leftOffice: `7 August 1898`,
	},
	{
		countryId,
		name: `Rafael Núñez Moledo`,
		party: `National Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 April 1886`,
		leftOffice: `18 September 1894`,
	},
	{
		countryId,
		name: `Miguel Antonio Caro`,
		party: `National Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `18 September 1894`,
		leftOffice: `7 August 1898`,
	},
	{
		countryId,
		name: `Manuel Antonio Sanclemente`,
		party: `National Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 1898`,
		leftOffice: `31 July 1900`,
	},
	{
		countryId,
		name: `José Manuel Marroquín`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `31 July 1900`,
		leftOffice: `7 August 1904`,
	},
	{
		countryId,
		name: `Rafael Reyes Prieto`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1904`,
		leftOffice: `27 July 1909`,
	},
	{
		countryId,
		name: `Ramón González Valencia`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1909`,
		leftOffice: `7 August 1910`,
	},
	{
		countryId,
		name: `Carlos Eugenio Restrepo`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1910`,
		leftOffice: `7 August 1914`,
	},
	{
		countryId,
		name: `José Vicente Concha`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1914`,
		leftOffice: `7 August 1918`,
	},
	{
		countryId,
		name: `Marco Fidel Suárez`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1918`,
		leftOffice: `11 November 1921`,
	},
	{
		countryId,
		name: `Jorge Holguín`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `11 November 1921`,
		leftOffice: `7 August 1922`,
	},
	{
		countryId,
		name: `Pedro Nel Ospina`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1922`,
		leftOffice: `7 August 1926`,
	},
	{
		countryId,
		name: `Miguel Abadía Méndez`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1926`,
		leftOffice: `7 August 1930`,
	},
	{
		countryId,
		name: `Enrique Olaya Herrera`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 1930`,
		leftOffice: `7 August 1934`,
	},
	{
		countryId,
		name: `Alfonso López Pumarejo`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 1934`,
		leftOffice: `7 August 1938`,
	},
	{
		countryId,
		name: `Eduardo Santos Montejo`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 1938`,
		leftOffice: `7 August 1942`,
	},
	{
		countryId,
		name: `Alfonso López Pumarejo`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 1942`,
		leftOffice: `7 August 1946`,
	},
	{
		countryId,
		name: `Mariano Ospina Pérez`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1946`,
		leftOffice: `7 August 1950`,
	},
	{
		countryId,
		name: `Laureano Gómez`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1950`,
		leftOffice: `5 November 1951`,
	},
	{
		countryId,
		name: `Roberto Urdaneta Arbeláez`,
		party: `Colombian Conservative Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `5 November 1951`,
		leftOffice: `13 June 1953`,
	},
	{
		countryId,
		name: `Gustavo Rojas Pinilla`,
		party: `National Popular Alliance`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `13 June 1953`,
		leftOffice: `10 May 1957`,
	},
	{
		countryId,
		name: `Military Junta`,
		party: `Military`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `10 May 1957`,
		leftOffice: `7 August 1958`,
	},
	{
		countryId,
		name: `Alberto Lleras Camargo`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 1958`,
		leftOffice: `7 August 1962`,
	},
	{
		countryId,
		name: `Guillermo León Valencia`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1962`,
		leftOffice: `7 August 1966`,
	},
	{
		countryId,
		name: `Carlos Lleras Restrepo`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 1966`,
		leftOffice: `7 August 1970`,
	},
	{
		countryId,
		name: `Misael Pastrana Borrero`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1970`,
		leftOffice: `7 August 1974`,
	},
	{
		countryId,
		name: `Alfonso López Michelsen`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 1974`,
		leftOffice: `7 August 1978`,
	},
	{
		countryId,
		name: `Julio César Turbay Ayala`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 1978`,
		leftOffice: `7 August 1982`,
	},
	{
		countryId,
		name: `Belisario Betancur Cuartas`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1982`,
		leftOffice: `7 August 1986`,
	},
	{
		countryId,
		name: `Virgilio Barco Vargas`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 1986`,
		leftOffice: `7 August 1990`,
	},
	{
		countryId,
		name: `César Gaviria`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 1990`,
		leftOffice: `7 August 1994`,
	},
	{
		countryId,
		name: `Ernesto Samper Pizano`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 1994`,
		leftOffice: `7 August 1998`,
	},
	{
		countryId,
		name: `Andrés Pastrana Arango`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1998`,
		leftOffice: `7 August 2002`,
	},
	{
		countryId,
		name: `Álvaro Uribe`,
		party: `Colombia First`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 2002`,
		leftOffice: `7 August 2010`,
	},
	{
		countryId,
		name: `Juan Manuel Santos Calderón`,
		party: `Union Party for the People`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 2010`,
		leftOffice: `7 August 2018`,
	},
	{
		countryId,
		name: `Iván Duque Márquez`,
		party: `Democratic Center`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `7 August 2018`,
		leftOffice: `7 August 2022`,
	},
	{
		countryId,
		name: `Gustavo Francisco Petro Urrego`,
		party: `Humane Colombia`,
		leaning: leanings.LEFT,
		tookOffice: `7 August 2022`,
		leftOffice: null,
	},
];
