import type { LeaderNoId } from '../../app/data/types';
import { leanings } from '../../app/data/types';

export const source = `https://www.mapsofworld.com/list-of/presidents-costa-rica/`;

const countryId = 8;

export const costaRica: LeaderNoId[] = [
	{
		countryId,
		name: `Rodrigo Chaves Robles`,
		party: `Social Democratic Progress Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 May 2022`,
		leftOffice: null,
	},
	{
		countryId,
		name: `Carlos Alvarado Quesada`,
		party: `Citizens’ Action Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `8 May 2018`,
		leftOffice: `8 May 2022`,
	},
	{
		countryId,
		name: `Luis Guillermo Solís`,
		party: `Citizens’ Action Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `8 May 2014`,
		leftOffice: `8 May 2018`,
	},
	{
		countryId,
		name: `Laura Chinchilla`,
		party: `National Liberation Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `8 May 2010`,
		leftOffice: `8 May 2014`,
	},
	{
		countryId,
		name: `Óscar Arias`,
		party: `National Liberation Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `8 May 2006`,
		leftOffice: `8 May 2010`,
	},
	{
		countryId,
		name: `Abel Pacheco de La Espriella`,
		party: `Social Christian Unity Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 May 2002`,
		leftOffice: `8 May 2006`,
	},
	{
		countryId,
		name: `Miguel Ángel Rodríguez`,
		party: `Social Christian Unity Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 May 1998`,
		leftOffice: `8 May 2002`,
	},
	{
		countryId,
		name: `José María Figueres Olsen`,
		party: `National Liberation Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `8 May 1994`,
		leftOffice: `8 May 1998`,
	},
	{
		countryId,
		name: `Rafael Ángel Calderón Fournier`,
		party: `Social Christian Unity Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 May 1990`,
		leftOffice: `8 May 1994`,
	},
	{
		countryId,
		name: `Óscar Arias`,
		party: `National Liberation Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `8 May 1986`,
		leftOffice: `8 May 1990`,
	},
	{
		countryId,
		name: `Luis Alberto Monge`,
		party: `National Liberation Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `8 May 1982`,
		leftOffice: `8 May 1986`,
	},
	{
		countryId,
		name: `Rodrigo Carazo Odio`,
		party: `Unity Party`,
		leaning: leanings.RIGHT,
		tookOffice: `8 May 1978`,
		leftOffice: `8 May 1982`,
	},
	{
		countryId,
		name: `Daniel Oduber Quirós`,
		party: `National Liberation Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `8 May 1974`,
		leftOffice: `8 May 1978`,
	},
	{
		countryId,
		name: `José Figueres Ferrer`,
		party: `National Liberation Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `8 May 1970`,
		leftOffice: `8 May 1974`,
	},
	{
		countryId,
		name: `Joaquín Trejos`,
		party: `National Unification Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 May 1966`,
		leftOffice: `8 May 1970`,
	},
	{
		countryId,
		name: `Francisco Orlich`,
		party: `National Liberation Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `8 May 1962`,
		leftOffice: `8 May 1966`,
	},
	{
		countryId,
		name: `Mario Echandi Jimenéz`,
		party: `National Unification Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 May 1958`,
		leftOffice: `8 May 1962`,
	},
	{
		countryId,
		name: `José Figueres Ferrer`,
		party: `National Liberation Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `8 May 1953`,
		leftOffice: `8 May 1958`,
	},
	{
		countryId,
		name: `Otilio Ulate Blanco`,
		party: `National Union Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `7 November 1949`,
		leftOffice: `8 May 1953`,
	},
	{
		countryId,
		name: `José Figueres Ferrer`,
		party: `National Liberation Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `8 May 1948`,
		leftOffice: `8 November 1949`,
	},
	{
		countryId,
		name: `Santos León Herrera`,
		party: `National Republican Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `20 April 1948`,
		leftOffice: `8 May 1948`,
	},
	{
		countryId,
		name: `Teodoro Picado Michalski`,
		party: `National Republican Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 May 1944`,
		leftOffice: `8 May 1948`,
	},
	{
		countryId,
		name: `Rafael Ángel Calderón`,
		party: `National Republican Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 May 1940`,
		leftOffice: `8 May 1944`,
	},
	{
		countryId,
		name: `León Cortés Castro`,
		party: `National Republican Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 May 1936`,
		leftOffice: `8 May 1940`,
	},
	{
		countryId,
		name: `Ricardo Jiménez Oreamuno`,
		party: `National Republican Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 May 1932`,
		leftOffice: `8 May 1936`,
	},
	{
		countryId,
		name: `Cleto González Víquez`,
		party: `National Union Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 May 1928`,
		leftOffice: `8 May 1932`,
	},
	{
		countryId,
		name: `Ricardo Jiménez Oreamuno`,
		party: `National Republican Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 May 1924`,
		leftOffice: `8 May 1928`,
	},
	{
		countryId,
		name: `Julio Acosta García`,
		party: `Constitutional Party`,
		leaning: leanings.RIGHT,
		tookOffice: `8 May 1920`,
		leftOffice: `8 May 1924`,
	},
	{
		countryId,
		name: `Francisco Aguilar Barquero`,
		party: `National Union Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `2 September 1919`,
		leftOffice: `8 May 1920`,
	},
	{
		countryId,
		name: `Juan Bautista Quirós Segura`,
		party: `Peliquista Party`,
		leaning: leanings.RIGHT,
		tookOffice: `13 August 1919`,
		leftOffice: `2 September 1919`,
	},
	{
		countryId,
		name: `Federico Tinoco Granados`,
		party: `Peliquista Party`,
		leaning: leanings.RIGHT,
		tookOffice: `27 January 1917`,
		leftOffice: `13 August 1919`,
	},
	{
		countryId,
		name: `Alfredo González`,
		party: `National Republican Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 May 1914`,
		leftOffice: `27 January 1917`,
	},
	{
		countryId,
		name: `Ricardo Jiménez Oreamuno`,
		party: `National Republican Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 May 1910`,
		leftOffice: `8 May 1914`,
	},
	{
		countryId,
		name: `Cleto González Víquez`,
		party: `National Union Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 May 1906`,
		leftOffice: `8 May 1910`,
	},
	{
		countryId,
		name: `Ascensión Esquivel Ibarra`,
		party: `National Union Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 May 1902`,
		leftOffice: `8 May 1906`,
	},
	{
		countryId,
		name: `Rafael Yglesias Castro`,
		party: `Civil Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `8 May 1894`,
		leftOffice: `8 May 1902`,
	},
	{
		countryId,
		name: `José Joaquín Rodríguez`,
		party: `Constitutional Party`,
		leaning: leanings.RIGHT,
		tookOffice: `8 May 1890`,
		leftOffice: `8 May 1894`,
	},
];
