import type { LeaderNoId } from '../../app/data/types';
import { leanings } from '../../app/data/types';

export const source = `https://en.wikipedia.org/wiki/List_of_presidents_of_Costa_Rica`;

const countryId = 8;

export const costaRica: LeaderNoId[] = [
	{
		countryId,
		name: `Captaincy General of Guatemala`,
		party: `Kingdom of Spain`,
		leaning: leanings.MONARCHY,
		tookOffice: `1 January 1609`,
		leftOffice: `15 September 1821`,
	},
	{
		countryId,
		name: `Gabino Gaínza`,
		party: `Military / Central American Independence`,
		leaning: leanings.MILITARY,
		tookOffice: `15 September 1821`,
		leftOffice: `5 January 1822`,
	},
	{
		countryId,
		name: `Agustín de Iturbide`,
		party: `First Mexican Empire`,
		leaning: leanings.MONARCHY,
		tookOffice: `5 January 1822`,
		leftOffice: `1 July 1823`,
	},
	{
		countryId,
		name: `Vicente Filísola - Federal Republic of Central America`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 July 1823`,
		leftOffice: `10 July 1823`,
	},
	{
		countryId,
		name: `First Triumvirate - Federal Republic of Central America`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `10 July 1823`,
		leftOffice: `4 October 1823`,
	},
	{
		countryId,
		name: `Second Triumvirate - Federal Republic of Central America`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `4 October 1823`,
		leftOffice: `29 April 1825`,
	},
	{
		countryId,
		name: `Manuel José Arce - Federal Republic of Central America`,
		party: `Liberal`,
		leaning: leanings.LEFT,
		tookOffice: `29 April 1825`,
		leftOffice: `13 April 1829`,
	},
	{
		countryId,
		name: `Mariano Beltranena y Llano - Federal Republic of Central America`,
		party: `Liberal`,
		leaning: leanings.LEFT,
		tookOffice: `13 April 1829`,
		leftOffice: `14 June 1829`,
	},
	{
		countryId,
		name: `Francisco Morazán - Federal Republic of Central America`,
		party: `Liberal`,
		leaning: leanings.LEFT,
		tookOffice: `14 June 1829`,
		leftOffice: `25 June 1829`,
	},
	{
		countryId,
		name: `José Francisco Barrundia - Federal Republic of Central America`,
		party: `Liberal`,
		leaning: leanings.LEFT,
		tookOffice: `25 June 1829`,
		leftOffice: `16 September 1830`,
	},
	{
		countryId,
		name: `Francisco Morazán - Federal Republic of Central America`,
		party: `Liberal`,
		leaning: leanings.LEFT,
		tookOffice: `16 September 1830`,
		leftOffice: `16 September 1834`,
	},
	{
		countryId,
		name: `José Gregorio Salazar - Federal Republic of Central America`,
		party: `Liberal`,
		leaning: leanings.LEFT,
		tookOffice: `16 September 1834`,
		leftOffice: `14 February 1835`,
	},
	{
		countryId,
		name: `Francisco Morazán - Federal Republic of Central America`,
		party: `Liberal`,
		leaning: leanings.LEFT,
		tookOffice: `14 February 1835`,
		leftOffice: `May 28, 1838`,
	},
	// Independence from the Federal Republic of Central America
	{
		countryId,
		name: `Braulio Carrillo Colina`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `May 28, 1838`,
		leftOffice: `1 April 1842`,
	},
	{
		countryId,
		name: `Francisco Morazán`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 April 1842`,
		leftOffice: `11 September 1842`,
	},
	{
		countryId,
		name: `António Pinto Soares`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `11 September 1842`,
		leftOffice: `27 September 1842`,
	},
	{
		countryId,
		name: `José María Alfaro Zamora`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `27 September 1842`,
		leftOffice: `1 November 1844`,
	},
	{
		countryId,
		name: `Francisco María Oreamuno Bonilla`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 November 1844`,
		leftOffice: `31 December 1844`,
	},
	{
		countryId,
		name: `José Rafael Gallegos`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 January 1845`,
		leftOffice: `1 January 1846`,
	},
	{
		countryId,
		name: `José María Alfaro Zamora`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 January 1846`,
		leftOffice: `1 January 1847`,
	},
	{
		countryId,
		name: `José Castro Madriz`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 January 1847`,
		leftOffice: `31 August 1848`,
	},
	{
		countryId,
		name: `José María Castro Madriz`,
		party: `Non-partisan Liberal`,
		leaning: leanings.CENTRIST,
		tookOffice: `31 August 1848`,
		leftOffice: `16 November 1849`,
	},
	{
		countryId,
		name: `Miguel Mora Porras`,
		party: `Non-partisan Liberal`,
		leaning: leanings.CENTRIST,
		tookOffice: `16 November 1849`,
		leftOffice: `26 November 1849`,
	},
	{
		countryId,
		name: `Juan Mora Porras`,
		party: `Non-partisan Liberal`,
		leaning: leanings.CENTRIST,
		tookOffice: `26 November 1849`,
		leftOffice: `14 August 1859`,
	},
	{
		countryId,
		name: `José María Montealegre Fernández`,
		party: `Non-partisan Liberal`,
		leaning: leanings.CENTRIST,
		tookOffice: `14 August 1859`,
		leftOffice: `8 May 1863`,
	},
	{
		countryId,
		name: `Jesús Jiménez Zamora`,
		party: `Non-partisan Liberal`,
		leaning: leanings.CENTRIST,
		tookOffice: `8 May 1863`,
		leftOffice: `8 May 1866`,
	},
	{
		countryId,
		name: `José Castro Madriz`,
		party: `Non-partisan Liberal`,
		leaning: leanings.CENTRIST,
		tookOffice: `8 May 1866`,
		leftOffice: `1 November 1868`,
	},
	{
		countryId,
		name: `Jesús Jiménez Zamora`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `1 November 1868`,
		leftOffice: `27 April 1870`,
	},
	{
		countryId,
		name: `Bruno Carranza Ramírez`,
		party: `Non-partisan Liberal`,
		leaning: leanings.CENTRIST,
		tookOffice: `27 April 1870`,
		leftOffice: `8 August 1870`,
	},
	{
		countryId,
		name: `Tomás Guardia Gutiérrez`,
		party: `Non-partisan Liberal`,
		leaning: leanings.CENTRIST,
		tookOffice: `10 August 1870`,
		leftOffice: `8 May 1876`,
	},
	{
		countryId,
		name: `Aniceto Esquivel Sáenz`,
		party: `Non-partisan Liberal`,
		leaning: leanings.CENTRIST,
		tookOffice: `8 May 1876`,
		leftOffice: `30 July 1876`,
	},
	{
		countryId,
		name: `Vicente Herrera Zeledón`,
		party: `Non-partisan Conservative`,
		leaning: leanings.CENTRIST,
		tookOffice: `30 July 1876`,
		leftOffice: `11 September 1877`,
	},
	{
		countryId,
		name: `Tomás Guardia Gutiérrez`,
		party: `Non-partisan Liberal`,
		leaning: leanings.CENTRIST,
		tookOffice: `11 September 1877`,
		leftOffice: `6 July 1882`,
	},
	{
		countryId,
		name: `Saturnino Lizano Gutiérrez`,
		party: `Non-partisan Liberal`,
		leaning: leanings.CENTRIST,
		tookOffice: `6 July 1882`,
		leftOffice: `20 July 1882`,
	},
	{
		countryId,
		name: `Próspero Fernández Oreamuno`,
		party: `Non-partisan Liberal`,
		leaning: leanings.CENTRIST,
		tookOffice: `20 July 1882`,
		leftOffice: `12 March 1885`,
	},
	{
		countryId,
		name: `Bernardo Soto Alfaro`,
		party: `Non-partisan Liberal`,
		leaning: leanings.CENTRIST,
		tookOffice: `12 March 1885`,
		leftOffice: `8 May 1890`,
	},
	{
		countryId,
		name: `José Joaquín Rodríguez`,
		party: `Constitutional Party`,
		leaning: leanings.RIGHT,
		tookOffice: `8 May 1890`,
		leftOffice: `8 May 1894`,
	},
	{
		countryId,
		name: `Rafael Yglesias Castro`,
		party: `Civil Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `8 May 1894`,
		leftOffice: `8 May 1902`,
	},
	{
		countryId,
		name: `Ascensión Esquivel Ibarra`,
		party: `National Union Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 May 1902`,
		leftOffice: `8 May 1906`,
	},
	{
		countryId,
		name: `Cleto González Víquez`,
		party: `National Union Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 May 1906`,
		leftOffice: `8 May 1910`,
	},
	{
		countryId,
		name: `Ricardo Jiménez Oreamuno`,
		party: `National Republican Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 May 1910`,
		leftOffice: `8 May 1914`,
	},
	{
		countryId,
		name: `Alfredo González`,
		party: `National Republican Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 May 1914`,
		leftOffice: `27 January 1917`,
	},
	{
		countryId,
		name: `Federico Tinoco Granados`,
		party: `Peliquista Party`,
		leaning: leanings.RIGHT,
		tookOffice: `27 January 1917`,
		leftOffice: `13 August 1919`,
	},
	{
		countryId,
		name: `Juan Bautista Quirós Segura`,
		party: `Peliquista Party`,
		leaning: leanings.RIGHT,
		tookOffice: `13 August 1919`,
		leftOffice: `2 September 1919`,
	},
	{
		countryId,
		name: `Francisco Aguilar Barquero`,
		party: `National Union Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `2 September 1919`,
		leftOffice: `8 May 1920`,
	},
	{
		countryId,
		name: `Julio Acosta García`,
		party: `Constitutional Party`,
		leaning: leanings.RIGHT,
		tookOffice: `8 May 1920`,
		leftOffice: `8 May 1924`,
	},
	{
		countryId,
		name: `Ricardo Jiménez Oreamuno`,
		party: `National Republican Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 May 1924`,
		leftOffice: `8 May 1928`,
	},
	{
		countryId,
		name: `Cleto González Víquez`,
		party: `National Union Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 May 1928`,
		leftOffice: `8 May 1932`,
	},
	{
		countryId,
		name: `Ricardo Jiménez Oreamuno`,
		party: `National Republican Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 May 1932`,
		leftOffice: `8 May 1936`,
	},
	{
		countryId,
		name: `León Cortés Castro`,
		party: `National Republican Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 May 1936`,
		leftOffice: `8 May 1940`,
	},
	{
		countryId,
		name: `Rafael Ángel Calderón`,
		party: `National Republican Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 May 1940`,
		leftOffice: `8 May 1944`,
	},
	{
		countryId,
		name: `Teodoro Picado Michalski`,
		party: `National Republican Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 May 1944`,
		leftOffice: `8 May 1948`,
	},
	{
		countryId,
		name: `Santos León Herrera`,
		party: `National Republican Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `20 April 1948`,
		leftOffice: `8 May 1948`,
	},
	{
		countryId,
		name: `José Figueres Ferrer`,
		party: `National Liberation Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `8 May 1948`,
		leftOffice: `8 November 1949`,
	},
	{
		countryId,
		name: `Otilio Ulate Blanco`,
		party: `National Union Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `7 November 1949`,
		leftOffice: `8 May 1953`,
	},
	{
		countryId,
		name: `José Figueres Ferrer`,
		party: `National Liberation Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `8 May 1953`,
		leftOffice: `8 May 1958`,
	},
	{
		countryId,
		name: `Mario Echandi Jimenéz`,
		party: `National Unification Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 May 1958`,
		leftOffice: `8 May 1962`,
	},
	{
		countryId,
		name: `Francisco Orlich`,
		party: `National Liberation Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `8 May 1962`,
		leftOffice: `8 May 1966`,
	},
	{
		countryId,
		name: `Joaquín Trejos`,
		party: `National Unification Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 May 1966`,
		leftOffice: `8 May 1970`,
	},
	{
		countryId,
		name: `José Figueres Ferrer`,
		party: `National Liberation Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `8 May 1970`,
		leftOffice: `8 May 1974`,
	},
	{
		countryId,
		name: `Daniel Oduber Quirós`,
		party: `National Liberation Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `8 May 1974`,
		leftOffice: `8 May 1978`,
	},
	{
		countryId,
		name: `Rodrigo Carazo Odio`,
		party: `Unity Party`,
		leaning: leanings.RIGHT,
		tookOffice: `8 May 1978`,
		leftOffice: `8 May 1982`,
	},
	{
		countryId,
		name: `Luis Alberto Monge`,
		party: `National Liberation Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `8 May 1982`,
		leftOffice: `8 May 1986`,
	},
	{
		countryId,
		name: `Óscar Arias`,
		party: `National Liberation Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `8 May 1986`,
		leftOffice: `8 May 1990`,
	},
	{
		countryId,
		name: `Rafael Ángel Calderón Fournier`,
		party: `Social Christian Unity Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 May 1990`,
		leftOffice: `8 May 1994`,
	},
	{
		countryId,
		name: `José María Figueres Olsen`,
		party: `National Liberation Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `8 May 1994`,
		leftOffice: `8 May 1998`,
	},
	{
		countryId,
		name: `Miguel Ángel Rodríguez`,
		party: `Social Christian Unity Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 May 1998`,
		leftOffice: `8 May 2002`,
	},
	{
		countryId,
		name: `Abel Pacheco de La Espriella`,
		party: `Social Christian Unity Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 May 2002`,
		leftOffice: `8 May 2006`,
	},
	{
		countryId,
		name: `Óscar Arias`,
		party: `National Liberation Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `8 May 2006`,
		leftOffice: `8 May 2010`,
	},
	{
		countryId,
		name: `Laura Chinchilla`,
		party: `National Liberation Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `8 May 2010`,
		leftOffice: `8 May 2014`,
	},
	{
		countryId,
		name: `Luis Guillermo Solís`,
		party: `Citizens’ Action Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `8 May 2014`,
		leftOffice: `8 May 2018`,
	},
	{
		countryId,
		name: `Carlos Alvarado Quesada`,
		party: `Citizens’ Action Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `8 May 2018`,
		leftOffice: `8 May 2022`,
	},
	{
		countryId,
		name: `Rodrigo Chaves Robles`,
		party: `Social Democratic Progress Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 May 2022`,
		leftOffice: null,
	},
];
