import type { LeaderNoId } from '../../app/data/types';
import { leanings } from '../../app/data/types';

export const source = `https://en.wikipedia.org/wiki/List_of_heads_of_state_of_Cuba`;

const countryId = 24;

export const cuba: LeaderNoId[] = [
	{
		countryId,
		name: `Captaincy General of Cuba`,
		party: `Spanish Empire`,
		leaning: leanings.MONARCHY,
		tookOffice: `1 January 1607`,
		leftOffice: `10 December 1898`,
	},
	{
		countryId,
		name: `United States Occupation`,
		party: `John R. Brooke`,
		leaning: leanings.RIGHT,
		tookOffice: `1 January 1899`,
		leftOffice: `20 May 1902`,
	},
	{
		countryId,
		name: `Tomás Estrada Palma`,
		party: `Republican Party of Havana`,
		leaning: leanings.RIGHT,
		tookOffice: `20 May 1902`,
		leftOffice: `28 September 1906`,
	},
	{
		countryId,
		name: `William H. Taft`,
		party: `United States Government`,
		leaning: leanings.RIGHT,
		tookOffice: `28 September 1906`,
		leftOffice: `13 October 1906`,
	},
	{
		countryId,
		name: `Charles Edward Magoon`,
		party: `United States Government`,
		leaning: leanings.RIGHT,
		tookOffice: `13 October 1906`,
		leftOffice: `28 January 1909`,
	},
	{
		countryId,
		name: `José Miguel Gómez`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `28 January 1909`,
		leftOffice: `20 May 1913`,
	},
	{
		countryId,
		name: `Mario García Menocal`,
		party: `National Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `20 May 1913`,
		leftOffice: `20 May 1921`,
	},
	{
		countryId,
		name: `Alfredo Zayas y Alfonso`,
		party: `National Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `20 May 1921`,
		leftOffice: `20 May 1925`,
	},
	{
		countryId,
		name: `Gerardo Machado`,
		party: `National Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `20 May 1925`,
		leftOffice: `12 August 1933`,
	},
	{
		countryId,
		name: `Alberto Herrera Franchi`,
		party: `Military`,
		leaning: leanings.CENTRIST,
		tookOffice: `12 August 1933`,
		leftOffice: `13 August 1933`,
	},
	{
		countryId,
		name: `Carlos Manuel de Céspedes y Quesada`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `13 August 1933`,
		leftOffice: `5 September 1933`,
	},
	{
		countryId,
		name: `Pentarchy of 1933`,
		party: `Nonpartisan`,
		leaning: leanings.CENTRIST,
		tookOffice: `5 September 1933`,
		leftOffice: `10 September 1933`,
	},
	{
		countryId,
		name: `Ramón Grau`,
		party: `Authentic Party`,
		leaning: leanings.LEFT,
		tookOffice: `10 September 1933`,
		leftOffice: `15 January 1934`,
	},
	{
		countryId,
		name: `Carlos Hevia`,
		party: `Authentic Party`,
		leaning: leanings.LEFT,
		tookOffice: `15 January 1934`,
		leftOffice: `18 January 1934`,
	},
	{
		countryId,
		name: `Manuel Márquez Sterling`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `18 January 1934`,
		leftOffice: `18 January 1934`,
	},
	{
		countryId,
		name: `Carlos Mendieta`,
		party: `National Union`,
		leaning: leanings.CENTRIST,
		tookOffice: `18 January 1934`,
		leftOffice: `11 December 1935`,
	},
	{
		countryId,
		name: `José Agripino Barnet`,
		party: `National Union`,
		leaning: leanings.CENTRIST,
		tookOffice: `11 December 1935`,
		leftOffice: `20 May 1936`,
	},
	{
		countryId,
		name: `Miguel Mariano Gómez`,
		party: `National Union`,
		leaning: leanings.CENTRIST,
		tookOffice: `20 May 1936`,
		leftOffice: `24 December 1936`,
	},
	{
		countryId,
		name: `Federico Laredo Brú`,
		party: `National Union`,
		leaning: leanings.CENTRIST,
		tookOffice: `24 December 1936`,
		leftOffice: `10 October 1940`,
	},
	{
		countryId,
		name: `Fulgencio Batista`,
		party: `Democratic Socialist Coalition`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `10 October 1940`,
		leftOffice: `10 October 1944`,
	},
	{
		countryId,
		name: `Ramón Grau`,
		party: `Authentic Party`,
		leaning: leanings.LEFT,
		tookOffice: `10 October 1944`,
		leftOffice: `10 October 1948`,
	},
	{
		countryId,
		name: `Carlos Prío Socarrás`,
		party: `Authentic Party`,
		leaning: leanings.LEFT,
		tookOffice: `10 October 1948`,
		leftOffice: `10 March 1952`,
	},
	{
		countryId,
		name: `Fulgencio Batista`,
		party: `Progressive Action Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `10 March 1952`,
		leftOffice: `14 August 1954`,
	},
	{
		countryId,
		name: `Andrés Domingo del Castillo`,
		party: `Progressive Action Party`,
		leaning: leanings.RIGHT,
		tookOffice: `14 August 1954`,
		leftOffice: `24 February 1955`,
	},
	{
		countryId,
		name: `Fulgencio Batista`,
		party: `Progressive Action Party`,
		leaning: leanings.RIGHT,
		tookOffice: `24 February 1955`,
		leftOffice: `1 January 1959`,
	},
	{
		countryId,
		name: `Anselmo Alliegro y Milá`,
		party: `Progressive Action Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 January 1959`,
		leftOffice: `2 January 1959`,
	},
	{
		countryId,
		name: `Carlos Manuel Piedra`,
		party: `Progressive Action Party`,
		leaning: leanings.RIGHT,
		tookOffice: `2 January 1959`,
		leftOffice: `3 January 1959`,
	},
	{
		countryId,
		name: `Manuel Urrutia Lleó`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `3 January 1959`,
		leftOffice: `18 July 1959`,
	},
	{
		countryId,
		name: `Osvaldo Dorticós Torrado`,
		party: `Socialist Party`,
		leaning: leanings.FAR_LEFT,
		tookOffice: `18 July 1959`,
		leftOffice: `2 December 1976`,
	},
	{
		countryId,
		name: `Fidel Castro`,
		party: `Communist Party`,
		leaning: leanings.FAR_LEFT,
		tookOffice: `2 December 1976`,
		leftOffice: `24 February 2008`,
	},
	{
		countryId,
		name: `Raúl Castro`,
		party: `Communist Party`,
		leaning: leanings.FAR_LEFT,
		tookOffice: `24 February 2008`,
		leftOffice: `19 April 2018`,
	},
	{
		countryId,
		name: `Miguel Díaz-Canel`,
		party: `Communist Party`,
		leaning: leanings.FAR_LEFT,
		tookOffice: `19 April 2018`,
		leftOffice: null,
	},
];
