import type { LeaderNoId } from '../../app/data/types';
import { leanings } from '../../app/data/types';

export const source = `https://www.mapsofworld.com/list-of/presidents-dominican-republic/`;

const countryId = 27;

export const dominicanRepublic: LeaderNoId[] = [
	{
		countryId,
		name: `Luis Abinader`,
		party: `Modern Dominican Revolutionary Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `16 August 2020`,
		leftOffice: null,
	},
	{
		countryId,
		name: `Danilo Medina`,
		party: `Dominican Liberation Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `16 August 2012`,
		leftOffice: `16 August 2020`,
	},
	{
		countryId,
		name: `Leonel Fernández`,
		party: `Dominican Liberation Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `16 August 2004`,
		leftOffice: `16 August 2012`,
	},
	{
		countryId,
		name: `Hipólito Mejía`,
		party: `Dominican Revolutionary Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `16 August 2000`,
		leftOffice: `16 August 2004`,
	},
	{
		countryId,
		name: `Leonel Fernández`,
		party: `Dominican Liberation Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `16 August 1996`,
		leftOffice: `16 August 2000`,
	},
	{
		countryId,
		name: `Joaquín Balaguer`,
		party: `Dominican Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `16 August 1986`,
		leftOffice: `16 August 1996`,
	},
	{
		countryId,
		name: `Salvador Jorge Blanco`,
		party: `Dominican Revolutionary Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `16 August 1982`,
		leftOffice: `16 August 1986`,
	},
	{
		countryId,
		name: `Jacobo Majluta Azar`,
		party: `Dominican Revolutionary Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `4 July 1982`,
		leftOffice: `16 August 1982`,
	},
	{
		countryId,
		name: `Silvestre Antonio Guzmán Fernández`,
		party: `Dominican Dominican Revolutionary Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `16 August 1978`,
		leftOffice: `4 July 1982`,
	},
	{
		countryId,
		name: `Joaquín Balaguer`,
		party: `Dominican Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `1 July 1966`,
		leftOffice: `16 August 1978`,
	},
	{
		countryId,
		name: `Héctor Rafael García-Godoy Cáceres`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `3 September 1965`,
		leftOffice: `1 July 1966`,
	},
	{
		countryId,
		name: `Antonio Imbert`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 May 1965`,
		leftOffice: `30 August 1965`,
	},
	{
		countryId,
		name: `José Rafael Molina Ureña`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `25 April 1965`,
		leftOffice: `27 April 1965`,
	},
	{
		countryId,
		name: `Triumvirate`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `26 September 1963`,
		leftOffice: `25 April 1965`,
	},
	{
		countryId,
		name: `Víctor Elby Viñas Román`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `25 September 1963`,
		leftOffice: `26 September 1963`,
	},
	{
		countryId,
		name: `Juan Bosch`,
		party: `Dominican Revolutionary Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `27 February 1963`,
		leftOffice: `25 September 1963`,
	},
	{
		countryId,
		name: `Rafael Bonnelly`,
		party: `Dominican Revolutionary Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `18 January 1962`,
		leftOffice: `27 February 1963`,
	},
	{
		countryId,
		name: `Civic-Military Council`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `16 January 1962`,
		leftOffice: `18 January 1962`,
	},
	{
		countryId,
		name: `Joaquín Balaguer`,
		party: `Dominican Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `3 August 1960`,
		leftOffice: `16 January 1962`,
	},
	{
		countryId,
		name: `Héctor Trujillo`,
		party: `Dominican Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `16 August 1952`,
		leftOffice: `3 August 1960`,
	},
	{
		countryId,
		name: `Rafael Trujillo`,
		party: `Dominican Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `16 August 1930`,
		leftOffice: `16 August 1938`,
	},
	{
		countryId,
		name: `Manuel Troncoso de la Concha`,
		party: `Dominican Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `24 February 1940`,
		leftOffice: `18 May 1942`,
	},
	{
		countryId,
		name: `Jacinto Peynado`,
		party: `Dominican Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `16 August 1938`,
		leftOffice: `24 February 1940`,
	},
	{
		countryId,
		name: `Rafael Trujillo`,
		party: `Dominican Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `16 August 1930`,
		leftOffice: `16 August 1938`,
	},
	{
		countryId,
		name: `Rafael Estrella Ureña`,
		party: `Dominican Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `3 March 1930`,
		leftOffice: `16 August 1930`,
	},
	{
		countryId,
		name: `Horacio Vásquez`,
		party: `Red Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `24 July 1924`,
		leftOffice: `3 March 1930`,
	},
	{
		countryId,
		name: `Juan Bautista Vicini Burgos`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `21 October 1922`,
		leftOffice: `12 July 1924`,
	},
	{
		countryId,
		name: `United States Occupation`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `29 November 1916`,
		leftOffice: `21 October 1922`,
	},
	{
		countryId,
		name: `Francisco Henríquez y Carvajal`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `31 July 1916`,
		leftOffice: `29 November 1916`,
	},
	{
		countryId,
		name: `Juan Isidro Jimenes`,
		party: `Blue Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `5 December 1914`,
		leftOffice: `7 May 1916`,
	},
	{
		countryId,
		name: `Ramón Báez`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `28 August 1914`,
		leftOffice: `5 December 1914`,
	},
	{
		countryId,
		name: `José Bordas Valdez`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `14 April 1913`,
		leftOffice: `27 August 1914`,
	},
	{
		countryId,
		name: `Adolfo Alejandro Nouel`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `30 November 1912`,
		leftOffice: `13 April 1913`,
	},
	{
		countryId,
		name: `Eladio Victoria`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `5 December 1911`,
		leftOffice: `30 November 1912`,
	},
	{
		countryId,
		name: `Ramón Cáceres`,
		party: `Red Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `12 January 1906`,
		leftOffice: `19 November 1911`,
	},
	{
		countryId,
		name: `Carlos Felipe Morales Languasco`,
		party: `Red Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `24 November 1903`,
		leftOffice: `29 December 1905`,
	},
	{
		countryId,
		name: `Alejandro Woss y Gil`,
		party: `Blue Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `23 April 1903`,
		leftOffice: `24 November 1903`,
	},
	{
		countryId,
		name: `Horacio Vásquez`,
		party: `Red Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `24 July 1924`,
		leftOffice: `3 March 1930`,
	},
	{
		countryId,
		name: `Juan Isidro Jimenes`,
		party: `Blue Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `15 November 1899`,
		leftOffice: `2 May 1902`,
	},
	{
		countryId,
		name: `Horacio Vásquez`,
		party: `Red Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `4 September 1899`,
		leftOffice: `15 November 1899`,
	},
	{
		countryId,
		name: `Wenceslao Figuereo`,
		party: `Blue Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `26 July 1899`,
		leftOffice: `30 August 1899`,
	},
];
