import type { LeaderNoId } from '../../app/data/types';
import { leanings } from '../../app/data/types';

export const source = `https://www.mapsofworld.com/list-of/presidents-dominican-republic/`;

const countryId = 27;

export const dominicanRepublic: LeaderNoId[] = [
	{
		name: 'Francisco del Rosario Sánchez',
		party: null,
		leaning: null,
		tookOffice: '28 February 1844',
		leftOffice: '1 March 1844',
	},
	{
		name: 'Tomás Bobadilla',
		party: null,
		leaning: null,
		tookOffice: '1 March 1844',
		leftOffice: '9 June 1844',
	},
	{
		name: 'Francisco del Rosario Sánchez',
		party: null,
		leaning: null,
		tookOffice: '9 June 1844',
		leftOffice: '12 July 1844',
	},
	{
		name: 'Pedro Santana',
		party: null,
		leaning: null,
		tookOffice: '12 July 1844',
		leftOffice: '14 November 1844',
	},
	{
		name: 'Pedro Santana',
		party: null,
		leaning: null,
		tookOffice: '14 November 1844',
		leftOffice: '4 August 1848',
	},
	{
		name: 'Manuel Jimenes',
		party: null,
		leaning: null,
		tookOffice: '8 September 1848',
		leftOffice: '29 May 1849',
	},
	{
		name: 'Pedro Santana',
		party: null,
		leaning: null,
		tookOffice: '30 May 1849',
		leftOffice: '23 September 1849',
	},
	{
		name: 'Buenaventura Báez',
		party: null,
		leaning: null,
		tookOffice: '24 September 1849',
		leftOffice: '15 February 1853',
	},
	{
		name: 'Pedro Santana',
		party: null,
		leaning: null,
		tookOffice: '15 February 1853',
		leftOffice: '26 May 1856',
	},
	{
		name: 'Manuel de Regla Mota',
		party: null,
		leaning: null,
		tookOffice: '2 January 1855',
		leftOffice: '5 September 1855',
	},
	{
		name: 'Manuel de Regla Mota',
		party: null,
		leaning: null,
		tookOffice: '26 May 1856',
		leftOffice: '8 October 1856',
	},
	{
		name: 'Buenaventura Báez',
		party: null,
		leaning: null,
		tookOffice: '8 October 1856',
		leftOffice: '12 June 1858',
	},
	{
		name: 'José Desiderio Valverde',
		party: null,
		leaning: null,
		tookOffice: '7 July 1857',
		leftOffice: '31 August 1858',
	},
	{
		name: 'Pedro Santana',
		party: null,
		leaning: null,
		tookOffice: '13 June 1858',
		leftOffice: '31 January 1859',
	},
	{
		name: 'Pedro Santana',
		party: null,
		leaning: null,
		tookOffice: '31 January 1859',
		leftOffice: '18 March 1861',
	},
	{
		name: 'Pedro Santana',
		party: null,
		leaning: null,
		tookOffice: '18 March 1861',
		leftOffice: '20 July 1862',
	},
	{
		name: 'Felipe Ribero y Lemoine',
		party: null,
		leaning: null,
		tookOffice: '20 July 1862',
		leftOffice: '22 October 1863',
	},
	{
		name: 'Carlos de Vargas y Cerveto',
		party: null,
		leaning: null,
		tookOffice: '23 October 1863',
		leftOffice: '30 March 1864',
	},
	{
		name: 'José de la Gándara y Navarro',
		party: null,
		leaning: null,
		tookOffice: '31 March 1864',
		leftOffice: '11 July 1865',
	},
	{
		name: 'José Antonio Salcedo',
		party: null,
		leaning: null,
		tookOffice: '14 September 1863',
		leftOffice: '10 October 1864',
	},
	{
		name: 'Gaspar Polanco',
		party: null,
		leaning: null,
		tookOffice: '10 October 1864',
		leftOffice: '24 January 1865',
	},
	{
		name: 'Benigno Filomeno de Rojas',
		party: null,
		leaning: null,
		tookOffice: '24 January 1865',
		leftOffice: '24 March 1865',
	},
	{
		name: 'Pedro Antonio Pimentel',
		party: null,
		leaning: null,
		tookOffice: '25 March 1865',
		leftOffice: '11 July 1865',
	},
	{
		name: 'Pedro Antonio Pimentel',
		party: null,
		leaning: null,
		tookOffice: '11 July 1865',
		leftOffice: '4 August 1865',
	},
	{
		name: 'José María Cabral',
		party: 'Blue party (Dominican Republic)',
		leaning: 'Centre',
		tookOffice: '4 August 1865',
		leftOffice: '15 November 1865',
	},
	{
		name: 'Pedro Guillermo',
		party: null,
		leaning: null,
		tookOffice: '15 November 1865',
		leftOffice: '8 December 1865',
	},
	{
		name: 'Buenaventura Báez',
		party: 'Red party (Dominican Republic)',
		leaning: 'right-wing',
		tookOffice: '8 December 1865',
		leftOffice: '29 May 1866',
	},
	{
		name: 'Triumvirate',
		party: null,
		leaning: null,
		tookOffice: '29 May 1866',
		leftOffice: '22 August 1866',
	},
	{
		name: 'José María Cabral',
		party: 'Blue party (Dominican Republic)',
		leaning: 'Centre',
		tookOffice: '22 August 1866',
		leftOffice: '29 September 1866',
	},
	{
		name: 'José María Cabral',
		party: 'Blue party (Dominican Republic)',
		leaning: 'Centre',
		tookOffice: '29 September 1866',
		leftOffice: '31 January 1868',
	},
	{
		name: 'Manuel Altagracia Cáceres',
		party: null,
		leaning: null,
		tookOffice: '31 January 1868',
		leftOffice: '13 February 1868',
	},
	{
		name: 'Junta of Generals',
		party: null,
		leaning: null,
		tookOffice: '13 February 1868',
		leftOffice: '2 May 1868',
	},
	{
		name: 'Buenaventura Báez',
		party: 'Red party (Dominican Republic)',
		leaning: 'right-wing',
		tookOffice: '2 May 1868',
		leftOffice: '2 January 1874',
	},
	{
		name: 'Ignacio María González',
		party: 'Green Socialist party',
		leaning: null,
		tookOffice: '25 November 1873',
		leftOffice: '21 January 1874',
	},
	{
		name: 'Ignacio María González',
		party: 'Green Socialist party',
		leaning: null,
		tookOffice: '21 January 1874',
		leftOffice: '5 February 1874',
	},
	{
		name: 'Manuel Altagracia Cáceres',
		party: 'Green Socialist party',
		leaning: null,
		tookOffice: '21 January 1874',
		leftOffice: '5 February 1874',
	},
	{
		name: 'Ignacio María González',
		party: 'Green Socialist party',
		leaning: null,
		tookOffice: '5 February 1874',
		leftOffice: '23 February 1876',
	},
	{
		name: 'Council of Secretaries of State',
		party: null,
		leaning: null,
		tookOffice: '23 February 1876',
		leftOffice: '29 April 1876',
	},
	{
		name: 'Ulises Francisco Espaillat',
		party: 'Blue party (Dominican Republic)',
		leaning: 'Centre',
		tookOffice: '29 April 1876',
		leftOffice: '5 October 1876',
	},
	{
		name: 'Superior Governing Junta',
		party: null,
		leaning: null,
		tookOffice: '5 October 1876',
		leftOffice: '11 November 1876',
	},
	{
		name: 'Ignacio María González',
		party: 'Green Socialist party',
		leaning: null,
		tookOffice: '11 November 1876',
		leftOffice: '9 December 1876',
	},
	{
		name: 'Marcos Antonio Cabral',
		party: null,
		leaning: null,
		tookOffice: '10 December 1876',
		leftOffice: '26 December 1876',
	},
	{
		name: 'Buenaventura Báez',
		party: 'Red party (Dominican Republic)',
		leaning: 'right-wing',
		tookOffice: '27 December 1876',
		leftOffice: '2 March 1878',
	},
	{
		name: 'Ignacio María González',
		party: 'Green Socialist party',
		leaning: null,
		tookOffice: '1 March 1878',
		leftOffice: '3 May 1878',
	},
	{
		name: 'Council of Secretaries of State',
		party: null,
		leaning: null,
		tookOffice: '2 March 1878',
		leftOffice: '5 March 1878',
	},
	{
		name: 'Cesáreo Guillermo',
		party: 'Red party (Dominican Republic)',
		leaning: 'right-wing',
		tookOffice: '5 March 1878',
		leftOffice: '6 July 1878',
	},
	{
		name: 'Ignacio María González',
		party: 'Green Socialist party',
		leaning: null,
		tookOffice: '6 July 1878',
		leftOffice: '2 September 1878',
	},
	{
		name: 'Superior Leaders of the Revolutionary Movement',
		party: null,
		leaning: null,
		tookOffice: '2 September 1878',
		leftOffice: '6 September 1878',
	},
	{
		name: 'Jacinto de Castro',
		party: null,
		leaning: null,
		tookOffice: '7 September 1878',
		leftOffice: '29 September 1878',
	},
	{
		name: 'Council of Secretaries of State',
		party: null,
		leaning: null,
		tookOffice: '30 September 1878',
		leftOffice: '27 February 1879',
	},
	{
		name: 'Cesáreo Guillermo',
		party: 'Red party (Dominican Republic)',
		leaning: 'right-wing',
		tookOffice: '27 February 1879',
		leftOffice: '6 December 1879',
	},
	{
		name: 'Gregorio Luperón',
		party: 'Blue party (Dominican Republic)',
		leaning: 'Centre',
		tookOffice: '6 October 1879',
		leftOffice: '1 September 1880',
	},
	{
		name: 'Fernando Arturo de Meriño',
		party: 'Blue party (Dominican Republic)',
		leaning: 'Centre',
		tookOffice: '1 September 1880',
		leftOffice: '1 September 1882',
	},
	{
		name: 'Ulises Heureaux',
		party: 'Blue party (Dominican Republic)',
		leaning: 'Centre',
		tookOffice: '1 September 1882',
		leftOffice: '1 September 1884',
	},
	{
		name: 'Francisco Gregorio Billini',
		party: 'Blue party (Dominican Republic)',
		leaning: 'Centre',
		tookOffice: '1 September 1884',
		leftOffice: '16 May 1885',
	},
	{
		name: 'Alejandro Woss y Gil',
		party: 'Blue party (Dominican Republic)',
		leaning: 'Centre',
		tookOffice: '16 May 1885',
		leftOffice: '6 January 1887',
	},
	{
		name: 'Ulises Heureaux',
		party: 'Blue party (Dominican Republic)',
		leaning: 'Centre',
		tookOffice: '6 January 1887',
		leftOffice: '27 February 1889',
	},
	{
		name: 'Ulises Heureaux',
		party: 'Blue party (Dominican Republic)',
		leaning: 'Centre',
		tookOffice: '27 February 1889',
		leftOffice: '27 February 1893',
	},
	{
		name: 'Ulises Heureaux',
		party: 'Blue party (Dominican Republic)',
		leaning: 'Centre',
		tookOffice: '27 February 1893',
		leftOffice: '27 February 1897',
	},
	{
		name: 'Ulises Heureaux',
		party: 'Blue party (Dominican Republic)',
		leaning: 'Centre',
		tookOffice: '27 February 1897',
		leftOffice: '26 July 1899',
	},
	{
		name: 'Wenceslao Figuereo',
		party: 'Blue party (Dominican Republic)',
		leaning: 'Centre',
		tookOffice: '26 July 1899',
		leftOffice: '30 August 1899',
	},
	{
		name: 'Council of Secretaries of State',
		party: null,
		leaning: null,
		tookOffice: '31 August 1899',
		leftOffice: '31 August 1899',
	},
	{
		name: "People's Revolutionary Governing Junta",
		party: null,
		leaning: null,
		tookOffice: '31 August 1899',
		leftOffice: '4 September 1899',
	},
	{
		name: 'Horacio Vásquez',
		party: 'Red party (Dominican Republic)',
		leaning: 'right-wing',
		tookOffice: '4 September 1899',
		leftOffice: '15 November 1899',
	},
	{
		name: 'Juan Isidro Jimenes Pereyra',
		party: 'Blue party (Dominican Republic)',
		leaning: 'Centre',
		tookOffice: '15 November 1899',
		leftOffice: '2 May 1902',
	},
	// TODO REVERSE ORDER
	{
		countryId,
		name: `Luis Abinader`,
		party: `Modern Dominican Revolutionary Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `16 August 2020`,
		leftOffice: null,
	},
	{
		countryId,
		name: `Danilo Medina`,
		party: `Dominican Liberation Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `16 August 2012`,
		leftOffice: `16 August 2020`,
	},
	{
		countryId,
		name: `Leonel Fernández`,
		party: `Dominican Liberation Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `16 August 2004`,
		leftOffice: `16 August 2012`,
	},
	{
		countryId,
		name: `Hipólito Mejía`,
		party: `Dominican Revolutionary Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `16 August 2000`,
		leftOffice: `16 August 2004`,
	},
	{
		countryId,
		name: `Leonel Fernández`,
		party: `Dominican Liberation Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `16 August 1996`,
		leftOffice: `16 August 2000`,
	},
	{
		countryId,
		name: `Joaquín Balaguer`,
		party: `Dominican Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `16 August 1986`,
		leftOffice: `16 August 1996`,
	},
	{
		countryId,
		name: `Salvador Jorge Blanco`,
		party: `Dominican Revolutionary Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `16 August 1982`,
		leftOffice: `16 August 1986`,
	},
	{
		countryId,
		name: `Jacobo Majluta Azar`,
		party: `Dominican Revolutionary Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `4 July 1982`,
		leftOffice: `16 August 1982`,
	},
	{
		countryId,
		name: `Silvestre Antonio Guzmán Fernández`,
		party: `Dominican Dominican Revolutionary Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `16 August 1978`,
		leftOffice: `4 July 1982`,
	},
	{
		countryId,
		name: `Joaquín Balaguer`,
		party: `Dominican Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `1 July 1966`,
		leftOffice: `16 August 1978`,
	},
	{
		countryId,
		name: `Héctor Rafael García-Godoy Cáceres`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `3 September 1965`,
		leftOffice: `1 July 1966`,
	},
	{
		countryId,
		name: `Antonio Imbert`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 May 1965`,
		leftOffice: `30 August 1965`,
	},
	{
		countryId,
		name: `José Rafael Molina Ureña`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `25 April 1965`,
		leftOffice: `27 April 1965`,
	},
	{
		countryId,
		name: `Triumvirate`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `26 September 1963`,
		leftOffice: `25 April 1965`,
	},
	{
		countryId,
		name: `Víctor Elby Viñas Román`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `25 September 1963`,
		leftOffice: `26 September 1963`,
	},
	{
		countryId,
		name: `Juan Bosch`,
		party: `Dominican Revolutionary Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `27 February 1963`,
		leftOffice: `25 September 1963`,
	},
	{
		countryId,
		name: `Rafael Bonnelly`,
		party: `Dominican Revolutionary Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `18 January 1962`,
		leftOffice: `27 February 1963`,
	},
	{
		countryId,
		name: `Civic-Military Council`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `16 January 1962`,
		leftOffice: `18 January 1962`,
	},
	{
		countryId,
		name: `Joaquín Balaguer`,
		party: `Dominican Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `3 August 1960`,
		leftOffice: `16 January 1962`,
	},
	{
		countryId,
		name: `Héctor Trujillo`,
		party: `Dominican Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `16 August 1952`,
		leftOffice: `3 August 1960`,
	},
	{
		countryId,
		name: `Rafael Trujillo`,
		party: `Dominican Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `16 August 1930`,
		leftOffice: `16 August 1938`,
	},
	{
		countryId,
		name: `Manuel Troncoso de la Concha`,
		party: `Dominican Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `24 February 1940`,
		leftOffice: `18 May 1942`,
	},
	{
		countryId,
		name: `Jacinto Peynado`,
		party: `Dominican Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `16 August 1938`,
		leftOffice: `24 February 1940`,
	},
	{
		countryId,
		name: `Rafael Trujillo`,
		party: `Dominican Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `16 August 1930`,
		leftOffice: `16 August 1938`,
	},
	{
		countryId,
		name: `Rafael Estrella Ureña`,
		party: `Dominican Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `3 March 1930`,
		leftOffice: `16 August 1930`,
	},
	{
		countryId,
		name: `Horacio Vásquez`,
		party: `Red Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `24 July 1924`,
		leftOffice: `3 March 1930`,
	},
	{
		countryId,
		name: `Juan Bautista Vicini Burgos`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `21 October 1922`,
		leftOffice: `12 July 1924`,
	},
	{
		countryId,
		name: `United States Occupation`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `29 November 1916`,
		leftOffice: `21 October 1922`,
	},
	{
		countryId,
		name: `Francisco Henríquez y Carvajal`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `31 July 1916`,
		leftOffice: `29 November 1916`,
	},
	{
		countryId,
		name: `Juan Isidro Jimenes`,
		party: `Blue Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `5 December 1914`,
		leftOffice: `7 May 1916`,
	},
	{
		countryId,
		name: `Ramón Báez`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `28 August 1914`,
		leftOffice: `5 December 1914`,
	},
	{
		countryId,
		name: `José Bordas Valdez`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `14 April 1913`,
		leftOffice: `27 August 1914`,
	},
	{
		countryId,
		name: `Adolfo Alejandro Nouel`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `30 November 1912`,
		leftOffice: `13 April 1913`,
	},
	{
		countryId,
		name: `Eladio Victoria`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `5 December 1911`,
		leftOffice: `30 November 1912`,
	},
	{
		countryId,
		name: `Ramón Cáceres`,
		party: `Red Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `12 January 1906`,
		leftOffice: `19 November 1911`,
	},
	{
		countryId,
		name: `Carlos Felipe Morales Languasco`,
		party: `Red Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `24 November 1903`,
		leftOffice: `29 December 1905`,
	},
	{
		countryId,
		name: `Alejandro Woss y Gil`,
		party: `Blue Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `23 April 1903`,
		leftOffice: `24 November 1903`,
	},
	{
		countryId,
		name: `Horacio Vásquez`,
		party: `Red Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `24 July 1924`,
		leftOffice: `3 March 1930`,
	},
	{
		countryId,
		name: `Juan Isidro Jimenes`,
		party: `Blue Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `15 November 1899`,
		leftOffice: `2 May 1902`,
	},
	{
		countryId,
		name: `Horacio Vásquez`,
		party: `Red Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `4 September 1899`,
		leftOffice: `15 November 1899`,
	},
	{
		countryId,
		name: `Wenceslao Figuereo`,
		party: `Blue Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `26 July 1899`,
		leftOffice: `30 August 1899`,
	},
];
