import type { LeaderNoId } from '../../app/data/types';
import { leanings } from '../../app/data/types';

export const source = `https://www.mapsofworld.com/list-of/presidents-of-ecuador/`;

const countryId = 12;

export const ecuador: LeaderNoId[] = [
	{
		countryId,
		name: `Guillermo Lasso`,
		party: `Creating Opportunities`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `24 May 2021`,
		leftOffice: null,
	},
	{
		countryId,
		name: `Lenín Moreno`,
		party: `PAIS Alliance`,
		leaning: leanings.LEFT,
		tookOffice: `24 May 2017`,
		leftOffice: `24 May 2021`,
	},
	{
		countryId,
		name: `Rafael Correa`,
		party: `PAIS Alliance`,
		leaning: leanings.LEFT,
		tookOffice: `15 January 2007`,
		leftOffice: `24 May 2017`,
	},
	{
		countryId,
		name: `Alfredo Palacio`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `20 April 2005`,
		leftOffice: `15 January 2007`,
	},
	{
		countryId,
		name: `Lucio Gutiérrez`,
		party: `Patriotic Society Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `15 January 2003`,
		leftOffice: `20 April 2005`,
	},
	{
		countryId,
		name: `Gustavo Noboa`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `22 January 2000`,
		leftOffice: `January 15 2003`,
	},
	{
		countryId,
		name: `Jamil Mahuad`,
		party: `Popular Democracy`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `10 August 1998`,
		leftOffice: `21 January 2000`,
	},
	{
		countryId,
		name: `Fabián Alarcón`,
		party: `Alfarista Radical Front`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `11 February 1997`,
		leftOffice: `10 August 1998`,
	},
	{
		countryId,
		name: `Rosalía Arteaga`,
		party: `Alfarista Radical Front`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `9 February 1997`,
		leftOffice: `11 February 1997`,
	},
	{
		countryId,
		name: `Fabián Alarcón`,
		party: `Alfarista Radical Front`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `6 February 1997`,
		leftOffice: `9 February 1997`,
	},
	{
		countryId,
		name: `Abdalá Bucaram`,
		party: `Ecuadorian Roldosist Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `10 August 1996`,
		leftOffice: `6 February 1997`,
	},
	{
		countryId,
		name: `Sixto Durán-Ballén`,
		party: `Republican Union Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `10 August 1992`,
		leftOffice: `10 August 1996`,
	},
	{
		countryId,
		name: `Rodrigo Borja Cevallos`,
		party: `Party of the Democratic Left`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `10 August 1988`,
		leftOffice: `10 August 1992`,
	},
	{
		countryId,
		name: `León Febres-Cordero`,
		party: `Social Christian Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `10 August 1984`,
		leftOffice: `10 August 1988`,
	},
	{
		countryId,
		name: `Osvaldo Hurtado`,
		party: `Popular Democracy`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `24 May 1981`,
		leftOffice: `10 August 1984`,
	},
	{
		countryId,
		name: `Jaime Roldós Aguilera`,
		party: `Concentration of People’s Forces`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `10 August 1979`,
		leftOffice: `24 May 1981`,
	},
	{
		countryId,
		name: `Supreme Government Council`,
		party: `Ecuadorean Armed Forces`,
		leaning: leanings.CENTRIST,
		tookOffice: `11 January 1976`,
		leftOffice: `10 August 1979`,
	},
	{
		countryId,
		name: `Guillermo Rodríguez`,
		party: `Ecuadorean Armed Forces`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `15 February 1972`,
		leftOffice: `11 January 1976`,
	},
	{
		countryId,
		name: `José María Velasco Ibarra`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 September 1968`,
		leftOffice: `15 February 1972`,
	},
	{
		countryId,
		name: `Otto Arosemena`,
		party: `Democratic Institutionalist Coalition`,
		leaning: leanings.RIGHT,
		tookOffice: `16 November 1966`,
		leftOffice: `31 August 1968`,
	},
	{
		countryId,
		name: `Clemente Yerovi`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `30 March 1966`,
		leftOffice: `16 November 1966`,
	},
	{
		countryId,
		name: `Military Junta`,
		party: `Ecuadorean Armed Forces`,
		leaning: leanings.RIGHT,
		tookOffice: `11 July 1963`,
		leftOffice: `29 March 1966`,
	},
	{
		countryId,
		name: `Carlos Julio Arosemena Monroy`,
		party: `Independent`,
		leaning: leanings.LEFT,
		tookOffice: `7 November 1961`,
		leftOffice: `11 July 1963`,
	},
	{
		countryId,
		name: `José María Velasco Ibarra`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 September 1960`,
		leftOffice: `7 November 1961`,
	},
	{
		countryId,
		name: `Camilo Ponce Enríquez`,
		party: `Social Christian Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 September 1956`,
		leftOffice: `1 September 1960`,
	},
	{
		countryId,
		name: `José María Velasco Ibarra`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 September 1952`,
		leftOffice: `1 September 1956`,
	},
	{
		countryId,
		name: `Galo Plaza Lasso`,
		party: `National Democratic Civic Movement`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 September 1948`,
		leftOffice: `1 September 1952`,
	},
	{
		countryId,
		name: `Carlos Julio Arosemena Tola`,
		party: `Independent`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `17 September 1947`,
		leftOffice: `31 August 1948`,
	},
	{
		countryId,
		name: `Mariano Suárez`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `2 September 1947`,
		leftOffice: `17 September 1947`,
	},
	{
		countryId,
		name: `Carlos Mancheno Cajas`,
		party: `Ecuadorean Armed Forces`,
		leaning: leanings.CENTRIST,
		tookOffice: `23 August 1947`,
		leftOffice: `2 September 1947`,
	},
	{
		countryId,
		name: `José María Velasco Ibarra`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 June 1944`,
		leftOffice: `23 August 1947`,
	},
	{
		countryId,
		name: `Julio Teodoro Salem`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `29 May 1944`,
		leftOffice: `31 May 1944`,
	},
	{
		countryId,
		name: `Carlos Alberto Arroyo del Río`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 September 1940`,
		leftOffice: `28 May 1944`,
	},
	{
		countryId,
		name: `Julio Enrique Moreno`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `10 August 1940`,
		leftOffice: `31 August 1940`,
	},
	{
		countryId,
		name: `Andrés Córdova`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `11 December 1939`,
		leftOffice: `10 August 1940`,
	},
	{
		countryId,
		name: `Carlos Alberto Arroyo del Río`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `18 November 1939`,
		leftOffice: `10 December 1939`,
	},
	{
		countryId,
		name: `Aurelio Mosquera`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `2 December 1938`,
		leftOffice: `17 November 1939`,
	},
	{
		countryId,
		name: `Manuel María Borrero`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `10 August 1938`,
		leftOffice: `1 December 1938`,
	},
	{
		countryId,
		name: `Alberto Enríquez Gallo`,
		party: `Ecuadorian Socialist Party`,
		leaning: leanings.LEFT,
		tookOffice: `23 October 1937`,
		leftOffice: `10 August 1938`,
	},
	{
		countryId,
		name: `Federico Páez Chiriboga`,
		party: `Ecuadorian Socialist Party`,
		leaning: leanings.LEFT,
		tookOffice: `26 September 1935`,
		leftOffice: `23 October 1937`,
	},
	{
		countryId,
		name: `Antonio Pons`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `21 August 1935`,
		leftOffice: `25 September 1935`,
	},
	{
		countryId,
		name: `José María Velasco Ibarra`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 September 1934`,
		leftOffice: `21 August 1935`,
	},
];
