import type { LeaderNoId } from '../../app/data/types';
import { leanings } from '../../app/data/types';

export const source = `https://www.mapsofworld.com/list-of/presidents-of-ecuador/`;

const countryId = 12;

export const ecuador: LeaderNoId[] = [
	{
		name: 'Juan José Flores',
		party: 'Independent',
		leaning: null,
		tookOffice: ' 3 May 1830',
		leftOffice: ' 10 September 1834',
	},
	{
		name: 'Vicente Rocafuerte',
		party: 'Independent',
		leaning: null,
		tookOffice: ' 10 September 1834',
		leftOffice: ' 31 January 1839',
	},
	{
		name: 'Juan José Flores',
		party: 'Independent',
		leaning: null,
		tookOffice: ' 1 February 1839',
		leftOffice: ' 6 March 1845',
	},
	{
		name: 'José Joaquín de Olmedo',
		party: 'Independent',
		leaning: null,
		tookOffice: ' 7 March 1845',
		leftOffice: ' 8 December 1845',
	},
	{
		name: 'Vicente Ramón Roca',
		party: 'Independent',
		leaning: null,
		tookOffice: ' 8 December 1845',
		leftOffice: ' 15 October 1849',
	},
	{
		name: 'Manuel de Ascásubi',
		party: 'Independent',
		leaning: null,
		tookOffice: ' 15 October 1849',
		leftOffice: ' 7 December 1850',
	},
	{
		name: 'Diego Noboa',
		party: 'Independent',
		leaning: null,
		tookOffice: '8 December 1850',
		leftOffice: ' 12 September 1851',
	},
	{
		name: 'José María Urvina',
		party: 'Independent',
		leaning: null,
		tookOffice: '24 July 1851',
		leftOffice: ' 15 October 1856',
	},
	{
		name: 'Francisco Robles',
		party: 'Independent',
		leaning: null,
		tookOffice: ' 16 October 1856',
		leftOffice: ' 31 August 1859',
	},
	{
		name: 'Provisional Government of Quito',
		party: null,
		leaning: null,
		tookOffice: '4 September 1859',
		leftOffice: ' 10 January 1861',
	},
	{
		name: 'Government of Cuenca',
		party: null,
		leaning: null,
		tookOffice: '6 May 1859',
		leftOffice: ' 13 November 1859',
	},
	{
		name: 'Supreme Leadership of Guayas',
		party: null,
		leaning: null,
		tookOffice: '21 August 1859',
		leftOffice: ' 24 September 1860',
	},
	{
		name: 'Cañar and Azuay (with Guayas)',
		party: null,
		leaning: null,
		tookOffice: '13 November 1859',
		leftOffice: ' 3 March 1860',
	},
	{
		name: 'Federal Government of Loja',
		party: null,
		leaning: null,
		tookOffice: 'September 18 1859',
		leftOffice: ' 23 March 1860',
	},
	{
		name: 'Gabriel García Moreno',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: '17 January 1861',
		leftOffice: ' 30 August 1865',
	},
	{
		name: 'Rafael Carvajal',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: '31 August 1865',
		leftOffice: ' 7 September 1865',
	},
	{
		name: 'Jerónimo Carrión',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: '7 September 1865',
		leftOffice: ' 6 November 1867',
	},
	{
		name: 'Pedro José de Arteta',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: ' 7 November 1867',
		leftOffice: ' 20 January 1868',
	},
	{
		name: 'Javier Espinosa',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: ' 20 January 1868',
		leftOffice: ' 19 January 1869',
	},
	{
		name: 'Gabriel García Moreno',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: ' 19 January 1869',
		leftOffice: ' 19 May 1869',
	},
	{
		name: 'Manuel de Ascásubi',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: ' 19 May 1869',
		leftOffice: ' 10 August 1869',
	},
	{
		name: 'Gabriel García Moreno',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: ' 10 August 1869',
		leftOffice: ' 6 August 1875',
	},
	{
		name: 'Francisco Xavier León',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: ' 6 August 1875',
		leftOffice: ' 15 September 1875',
	},
	{
		name: 'José Javier Eguiguren',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: ' 15 September 1875',
		leftOffice: ' 9 December 1875',
	},
	{
		name: 'Antonio Borrero',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: ' 9 December 1875',
		leftOffice: ' 8 September 1876',
	},
	{
		name: 'Ignacio de Veintemilla',
		party: 'Military',
		leaning: null,
		tookOffice: ' 8 September 1876',
		leftOffice: ' 10 January 1883',
	},
	{
		name: '"Pentevirato Quiteño"',
		party: null,
		leaning: null,
		tookOffice: ' 14 January 1883',
		leftOffice: ' 15 October 1883',
	},
	{
		name: 'Supreme Leadership of Manabí and Esmeraldas',
		party: null,
		leaning: null,
		tookOffice: ' 5 June 1883',
		leftOffice: ' 15 October 1883',
	},
	{
		name: 'Supreme Leadership of Guayas',
		party: null,
		leaning: null,
		tookOffice: ' 10 July 1883',
		leftOffice: ' 15 October 1883',
	},
	{
		name: 'José Plácido Caamaño',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: ' 15 October 1883',
		leftOffice: ' 30 June 1888',
	},
	{
		name: 'Pedro José Cevallos',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: ' 1 July 1888',
		leftOffice: ' 17 August 1888',
	},
	{
		name: 'Antonio Flores Jijón',
		party: 'Republican Union party',
		leaning: null,
		tookOffice: ' 17 August 1888',
		leftOffice: ' 10 June 1892',
	},
	{
		name: 'Luis Cordero Crespo',
		party: 'Republican Union party',
		leaning: null,
		tookOffice: ' 1 July 1892',
		leftOffice: ' 16 April 1895',
	},
	{
		name: 'Vicente Lucio Salazar',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: ' 16 April 1895',
		leftOffice: ' 5 June 1895',
	},
	{
		name: 'Eloy Alfaro',
		party: 'Ecuadorian Radical Liberal party',
		leaning: 'Centre',
		tookOffice: ' 5 June 1895',
		leftOffice: ' 31 August 1901',
	},
	{
		name: 'Leónidas Plaza',
		party: 'Ecuadorian Radical Liberal party',
		leaning: 'Centre',
		tookOffice: ' 1 September 1901',
		leftOffice: ' 31 August 1905',
	},
	{
		name: 'Lizardo García',
		party: 'Ecuadorian Radical Liberal party',
		leaning: 'Centre',
		tookOffice: '  1 September 1905',
		leftOffice: ' 15 January 1906',
	},
	{
		name: 'Eloy Alfaro',
		party: 'Ecuadorian Radical Liberal party',
		leaning: 'Centre',
		tookOffice: ' 16 January 1906',
		leftOffice: ' 11 August 1911',
	},
	{
		name: 'Carlos Freile Zaldumbide',
		party: 'Ecuadorian Radical Liberal party',
		leaning: 'Centre',
		tookOffice: ' 11 August 1911',
		leftOffice: ' 31 August 1911',
	},
	{
		name: 'Emilio Estrada',
		party: 'Ecuadorian Radical Liberal party',
		leaning: 'Centre',
		tookOffice: ' 1 September 1911',
		leftOffice: '21 December 1911',
	},
	{
		name: 'Carlos Freile Zaldumbide',
		party: 'Ecuadorian Radical Liberal party',
		leaning: 'Centre',
		tookOffice: ' 22 December 1911',
		leftOffice: ' 5 March 1912',
	},
	{
		name: 'Francisco Andrade Marín',
		party: 'Ecuadorian Radical Liberal party',
		leaning: 'Centre',
		tookOffice: ' 6 March 1912',
		leftOffice: ' 1 August 1912',
	},
	{
		name: 'Alfredo Baquerizo',
		party: 'Ecuadorian Radical Liberal party',
		leaning: 'Centre',
		tookOffice: ' 1 August 1912',
		leftOffice: ' 1 September 1912',
	},
	{
		name: 'Leónidas Plaza',
		party: 'Ecuadorian Radical Liberal party',
		leaning: 'Centre',
		tookOffice: ' 1 September 1912',
		leftOffice: ' 31 August 1916',
	},
	{
		name: 'Alfredo Baquerizo',
		party: 'Ecuadorian Radical Liberal party',
		leaning: 'Centre',
		tookOffice: ' 1 September 1916',
		leftOffice: ' 31 August 1920',
	},
	{
		name: 'José Luis Tamayo',
		party: 'Ecuadorian Radical Liberal party',
		leaning: 'Centre',
		tookOffice: ' 1 September 1920',
		leftOffice: ' 31 August 1924',
	},
	{
		name: 'Gonzalo Córdova',
		party: 'Ecuadorian Radical Liberal party',
		leaning: 'Centre',
		tookOffice: ' 1 September 1924',
		leftOffice: ' 9 July 1925',
	},
	{
		name: 'First Provisional Government',
		party: null,
		leaning: null,
		tookOffice: ' 10 July 1925',
		leftOffice: ' 6 January 1926',
	},
	{
		name: 'Second Provisional Government',
		party: null,
		leaning: null,
		tookOffice: ' 10 January 1926',
		leftOffice: ' 31 March 1926',
	},
	{
		name: 'Isidro Ayora',
		party: 'Ecuadorian Radical Liberal party',
		leaning: 'Centre',
		tookOffice: ' 3 April 1926',
		leftOffice: ' 24 August 1931',
	},
	{
		name: 'Luis Larrea Alba',
		party: 'Ecuadorian Radical Liberal party',
		leaning: 'Centre',
		tookOffice: ' 24 August 1931',
		leftOffice: ' 15 October 1931',
	},
	{
		name: 'Alfredo Baquerizo',
		party: 'Ecuadorian Radical Liberal party',
		leaning: 'Centre',
		tookOffice: ' 15 October 1931',
		leftOffice: ' 28 August 1932',
	},
	{
		name: 'Carlos Freile Larrea',
		party: 'Ecuadorian Radical Liberal party',
		leaning: 'Centre',
		tookOffice: ' 28 August 1932',
		leftOffice: ' 1 September 1932',
	},
	{
		name: 'Alberto Guerrero Martínez',
		party: 'Ecuadorian Radical Liberal party',
		leaning: 'Centre',
		tookOffice: ' 2 September 1932',
		leftOffice: ' 4 December 1932',
	},
	{
		name: 'Juan de Dios Martínez',
		party: 'Ecuadorian Radical Liberal party',
		leaning: 'Centre',
		tookOffice: ' 5 December 1932',
		leftOffice: ' 19 October 1933',
	},
	{
		name: 'Abelardo Montalvo',
		party: 'Ecuadorian Radical Liberal party',
		leaning: 'Centre',
		tookOffice: ' 20 October 1933',
		leftOffice: ' 31 August 1934',
	},
	{
		name: 'José María Velasco Ibarra',
		party: 'Independent',
		leaning: null,
		tookOffice: ' 1 September 1934',
		leftOffice: ' 21 August 1935',
	},
	{
		name: 'Antonio Pons',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: ' 21 August 1935',
		leftOffice: ' 25 September 1935',
	},
	{
		name: 'Federico Páez',
		party: 'Independent',
		leaning: null,
		tookOffice: ' 26 September 1935',
		leftOffice: ' 23 October 1937',
	},
	// TODO REVERSE ORDER
	{
		countryId,
		name: `Guillermo Lasso`,
		party: `Creating Opportunities`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `24 May 2021`,
		leftOffice: null,
	},
	{
		countryId,
		name: `Lenín Moreno`,
		party: `PAIS Alliance`,
		leaning: leanings.LEFT,
		tookOffice: `24 May 2017`,
		leftOffice: `24 May 2021`,
	},
	{
		countryId,
		name: `Rafael Correa`,
		party: `PAIS Alliance`,
		leaning: leanings.LEFT,
		tookOffice: `15 January 2007`,
		leftOffice: `24 May 2017`,
	},
	{
		countryId,
		name: `Alfredo Palacio`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `20 April 2005`,
		leftOffice: `15 January 2007`,
	},
	{
		countryId,
		name: `Lucio Gutiérrez`,
		party: `Patriotic Society Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `15 January 2003`,
		leftOffice: `20 April 2005`,
	},
	{
		countryId,
		name: `Gustavo Noboa`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `22 January 2000`,
		leftOffice: `January 15 2003`,
	},
	{
		countryId,
		name: `Jamil Mahuad`,
		party: `Popular Democracy`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `10 August 1998`,
		leftOffice: `21 January 2000`,
	},
	{
		countryId,
		name: `Fabián Alarcón`,
		party: `Alfarista Radical Front`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `11 February 1997`,
		leftOffice: `10 August 1998`,
	},
	{
		countryId,
		name: `Rosalía Arteaga`,
		party: `Alfarista Radical Front`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `9 February 1997`,
		leftOffice: `11 February 1997`,
	},
	{
		countryId,
		name: `Fabián Alarcón`,
		party: `Alfarista Radical Front`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `6 February 1997`,
		leftOffice: `9 February 1997`,
	},
	{
		countryId,
		name: `Abdalá Bucaram`,
		party: `Ecuadorian Roldosist Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `10 August 1996`,
		leftOffice: `6 February 1997`,
	},
	{
		countryId,
		name: `Sixto Durán-Ballén`,
		party: `Republican Union Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `10 August 1992`,
		leftOffice: `10 August 1996`,
	},
	{
		countryId,
		name: `Rodrigo Borja Cevallos`,
		party: `Party of the Democratic Left`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `10 August 1988`,
		leftOffice: `10 August 1992`,
	},
	{
		countryId,
		name: `León Febres-Cordero`,
		party: `Social Christian Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `10 August 1984`,
		leftOffice: `10 August 1988`,
	},
	{
		countryId,
		name: `Osvaldo Hurtado`,
		party: `Popular Democracy`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `24 May 1981`,
		leftOffice: `10 August 1984`,
	},
	{
		countryId,
		name: `Jaime Roldós Aguilera`,
		party: `Concentration of People’s Forces`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `10 August 1979`,
		leftOffice: `24 May 1981`,
	},
	{
		countryId,
		name: `Supreme Government Council`,
		party: `Ecuadorean Armed Forces`,
		leaning: leanings.CENTRIST,
		tookOffice: `11 January 1976`,
		leftOffice: `10 August 1979`,
	},
	{
		countryId,
		name: `Guillermo Rodríguez`,
		party: `Ecuadorean Armed Forces`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `15 February 1972`,
		leftOffice: `11 January 1976`,
	},
	{
		countryId,
		name: `José María Velasco Ibarra`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 September 1968`,
		leftOffice: `15 February 1972`,
	},
	{
		countryId,
		name: `Otto Arosemena`,
		party: `Democratic Institutionalist Coalition`,
		leaning: leanings.RIGHT,
		tookOffice: `16 November 1966`,
		leftOffice: `31 August 1968`,
	},
	{
		countryId,
		name: `Clemente Yerovi`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `30 March 1966`,
		leftOffice: `16 November 1966`,
	},
	{
		countryId,
		name: `Military Junta`,
		party: `Ecuadorean Armed Forces`,
		leaning: leanings.RIGHT,
		tookOffice: `11 July 1963`,
		leftOffice: `29 March 1966`,
	},
	{
		countryId,
		name: `Carlos Julio Arosemena Monroy`,
		party: `Independent`,
		leaning: leanings.LEFT,
		tookOffice: `7 November 1961`,
		leftOffice: `11 July 1963`,
	},
	{
		countryId,
		name: `José María Velasco Ibarra`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 September 1960`,
		leftOffice: `7 November 1961`,
	},
	{
		countryId,
		name: `Camilo Ponce Enríquez`,
		party: `Social Christian Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 September 1956`,
		leftOffice: `1 September 1960`,
	},
	{
		countryId,
		name: `José María Velasco Ibarra`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 September 1952`,
		leftOffice: `1 September 1956`,
	},
	{
		countryId,
		name: `Galo Plaza Lasso`,
		party: `National Democratic Civic Movement`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 September 1948`,
		leftOffice: `1 September 1952`,
	},
	{
		countryId,
		name: `Carlos Julio Arosemena Tola`,
		party: `Independent`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `17 September 1947`,
		leftOffice: `31 August 1948`,
	},
	{
		countryId,
		name: `Mariano Suárez`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `2 September 1947`,
		leftOffice: `17 September 1947`,
	},
	{
		countryId,
		name: `Carlos Mancheno Cajas`,
		party: `Ecuadorean Armed Forces`,
		leaning: leanings.CENTRIST,
		tookOffice: `23 August 1947`,
		leftOffice: `2 September 1947`,
	},
	{
		countryId,
		name: `José María Velasco Ibarra`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 June 1944`,
		leftOffice: `23 August 1947`,
	},
	{
		countryId,
		name: `Julio Teodoro Salem`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `29 May 1944`,
		leftOffice: `31 May 1944`,
	},
	{
		countryId,
		name: `Carlos Alberto Arroyo del Río`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 September 1940`,
		leftOffice: `28 May 1944`,
	},
	{
		countryId,
		name: `Julio Enrique Moreno`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `10 August 1940`,
		leftOffice: `31 August 1940`,
	},
	{
		countryId,
		name: `Andrés Córdova`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `11 December 1939`,
		leftOffice: `10 August 1940`,
	},
	{
		countryId,
		name: `Carlos Alberto Arroyo del Río`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `18 November 1939`,
		leftOffice: `10 December 1939`,
	},
	{
		countryId,
		name: `Aurelio Mosquera`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `2 December 1938`,
		leftOffice: `17 November 1939`,
	},
	{
		countryId,
		name: `Manuel María Borrero`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `10 August 1938`,
		leftOffice: `1 December 1938`,
	},
	{
		countryId,
		name: `Alberto Enríquez Gallo`,
		party: `Ecuadorian Socialist Party`,
		leaning: leanings.LEFT,
		tookOffice: `23 October 1937`,
		leftOffice: `10 August 1938`,
	},
	{
		countryId,
		name: `Federico Páez Chiriboga`,
		party: `Ecuadorian Socialist Party`,
		leaning: leanings.LEFT,
		tookOffice: `26 September 1935`,
		leftOffice: `23 October 1937`,
	},
	{
		countryId,
		name: `Antonio Pons`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `21 August 1935`,
		leftOffice: `25 September 1935`,
	},
	{
		countryId,
		name: `José María Velasco Ibarra`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 September 1934`,
		leftOffice: `21 August 1935`,
	},
];
