import type { LeaderNoId } from '../../app/data/types';
import { leanings } from '../../app/data/types';

export const source = `https://www.mapsofworld.com/list-of/presidents-el-salvador/`;

const countryId = 5;

export const elSalvador: LeaderNoId[] = [
	{
		name: 'Pedro Barriere',
		party: 'Independent',
		leaning: null,
		tookOffice: '21 September 1821',
		leftOffice: '28 November 1821',
	},
	{
		name: 'José Matías Delgado',
		party: 'Independent',
		leaning: null,
		tookOffice: '28 November 1821',
		leftOffice: '9 February 1823',
	},
	{
		name: 'Vicente Filísola',
		party: 'Military',
		leaning: null,
		tookOffice: '9 February 1823',
		leftOffice: '7 May 1823',
	},
	{
		name: 'Felipe Codallos',
		party: 'Military',
		leaning: null,
		tookOffice: '7 May 1823',
		leftOffice: '25 May 1823',
	},
	{
		name: 'Consultive Junta',
		party: 'Consultive Junta',
		leaning: null,
		tookOffice: '25 May 1823',
		leftOffice: '17 June 1823',
	},
	{
		name: 'Mariano Prado',
		party: 'Liberal',
		leaning: null,
		tookOffice: '17 June 1823',
		leftOffice: '22 April 1824',
	},
	{
		name: 'Juan Manuel Rodríguez',
		party: 'Independent',
		leaning: null,
		tookOffice: '22 April 1824',
		leftOffice: '1 October 1824',
	},
	{
		name: 'Mariano Prado',
		party: 'Liberal',
		leaning: null,
		tookOffice: '1 October 1824',
		leftOffice: '13 December 1824',
	},
	{
		name: 'Juan Vicente Villacorta Díaz',
		party: 'Liberal',
		leaning: null,
		tookOffice: '13 December 1824',
		leftOffice: '1 November 1826',
	},
	{
		name: 'Mariano Prado',
		party: 'Liberal',
		leaning: null,
		tookOffice: '1 November 1826',
		leftOffice: '30 January 1829',
	},
	{
		name: 'José María Cornejo',
		party: 'Conservative',
		leaning: null,
		tookOffice: '30 January 1829',
		leftOffice: '16 February 1830',
	},
	{
		name: 'José Damián Villacorta',
		party: 'Independent',
		leaning: null,
		tookOffice: '16 February 1830',
		leftOffice: '4 December 1830',
	},
	{
		name: 'José María Cornejo',
		party: 'Conservative',
		leaning: null,
		tookOffice: '4 December 1830',
		leftOffice: '3 April 1832',
	},
	{
		name: 'Francisco Morazán',
		party: 'Liberal',
		leaning: null,
		tookOffice: '3 April 1832',
		leftOffice: '13 May 1832',
	},
	{
		name: 'Joaquín de San Martín',
		party: 'Conservative',
		leaning: null,
		tookOffice: '13 May 1832',
		leftOffice: '25 July 1832',
	},
	{
		name: 'Mariano Prado',
		party: 'Liberal',
		leaning: null,
		tookOffice: '25 July 1832',
		leftOffice: '1 July 1833',
	},
	{
		name: 'Joaquín de San Martín',
		party: 'Conservative',
		leaning: null,
		tookOffice: '1 July 1833',
		leftOffice: '23 June 1834',
	},
	{
		name: 'Carlos Salazar Castro',
		party: 'Independent',
		leaning: null,
		tookOffice: '23 June 1834',
		leftOffice: '13 July 1834',
	},
	{
		name: 'José Gregorio Salazar',
		party: 'Independent',
		leaning: null,
		tookOffice: '13 July 1834',
		leftOffice: '30 September 1834',
	},
	{
		name: 'Joaquín Escolán y Balibrera',
		party: 'Independent',
		leaning: null,
		tookOffice: '30 September 1834',
		leftOffice: '13 October 1834',
	},
	{
		name: 'José María Silva',
		party: 'Independent',
		leaning: null,
		tookOffice: '13 October 1834',
		leftOffice: '2 March 1835',
	},
	{
		name: 'Joaquín Escolán y Balibrera',
		party: 'Independent',
		leaning: null,
		tookOffice: '2 March 1835',
		leftOffice: '10 April 1835',
	},
	{
		name: 'Nicolás Espinoza',
		party: 'Liberal',
		leaning: null,
		tookOffice: '10 April 1835',
		leftOffice: '15 November 1835',
	},
	{
		name: 'Francisco Gómez',
		party: 'Independent',
		leaning: null,
		tookOffice: '15 November 1835',
		leftOffice: '1 February 1836',
	},
	{
		name: 'Diego Vigil Cocaña',
		party: 'Liberal',
		leaning: null,
		tookOffice: '1 February 1836',
		leftOffice: '23 May 1837',
	},
	{
		name: 'Timoteo Menéndez',
		party: 'Independent',
		leaning: null,
		tookOffice: '23 May 1837',
		leftOffice: '7 June 1837',
	},
	{
		name: 'Diego Vigil Cocaña',
		party: 'Liberal',
		leaning: null,
		tookOffice: '7 June 1837',
		leftOffice: '6 January 1838',
	},
	{
		name: 'Timoteo Menéndez',
		party: 'Independent',
		leaning: null,
		tookOffice: '6 January 1838',
		leftOffice: '23 May 1838',
	},
	{
		name: 'Antonio José Cañas',
		party: 'Independent',
		leaning: null,
		tookOffice: '23 May 1838',
		leftOffice: '11 July 1839',
	},
	{
		name: 'Francisco Morazán',
		party: 'Liberal',
		leaning: null,
		tookOffice: '11 July 1839',
		leftOffice: '16 February 1840',
	},
	{
		name: 'José María Silva',
		party: 'Independent',
		leaning: null,
		tookOffice: '16 February 1840',
		leftOffice: '5 April 1840',
	},
	{
		name: 'Municipal Council of San Salvador',
		party: null,
		leaning: null,
		tookOffice: '5 April 1840',
		leftOffice: '15 April 1840',
	},
	{
		name: 'Antonio José Cañas',
		party: 'Independent',
		leaning: null,
		tookOffice: '15 April 1840',
		leftOffice: '20 September 1840',
	},
	{
		name: 'Norberto Ramírez',
		party: 'Independent',
		leaning: null,
		tookOffice: '20 September 1840',
		leftOffice: '7 January 1841',
	},
	{
		name: 'Juan Lindo',
		party: 'Conservative',
		leaning: null,
		tookOffice: '7 January 1841',
		leftOffice: '22 February 1841',
	},
	{
		name: 'Juan Lindo',
		party: 'Conservative',
		leaning: null,
		tookOffice: '22 February 1841',
		leftOffice: '20 June 1841',
	},
	{
		name: 'Pedro José Arce',
		party: 'Independent',
		leaning: null,
		tookOffice: '20 June 1841',
		leftOffice: '28 June 1841',
	},
	{
		name: 'Juan Lindo',
		party: 'Conservative',
		leaning: null,
		tookOffice: '28 June 1841',
		leftOffice: '1 February 1842',
	},
	{
		name: 'José Escolástico Marín',
		party: 'Independent',
		leaning: null,
		tookOffice: '1 February 1842',
		leftOffice: '12 April 1842',
	},
	{
		name: 'Juan José Guzmán',
		party: 'Conservative',
		leaning: null,
		tookOffice: '12 April 1842',
		leftOffice: '30 June 1842',
	},
	{
		name: 'Dionisio Villacorta',
		party: 'Independent',
		leaning: null,
		tookOffice: '30 June 1842',
		leftOffice: '19 July 1842',
	},
	{
		name: 'José Escolástico Marín',
		party: 'Independent',
		leaning: null,
		tookOffice: '19 July 1842',
		leftOffice: '26 September 1842',
	},
	{
		name: 'Juan José Guzmán',
		party: 'Conservative',
		leaning: null,
		tookOffice: '26 September 1842',
		leftOffice: '10 December 1843',
	},
	{
		name: 'Cayetano Molina',
		party: 'Independent',
		leaning: null,
		tookOffice: '10 December 1843',
		leftOffice: '20 December 1843',
	},
	{
		name: 'Pedro José Arce',
		party: 'Independent',
		leaning: null,
		tookOffice: '20 December 1843',
		leftOffice: '29 December 1843',
	},
	{
		name: 'Cayetano Molina',
		party: 'Independent',
		leaning: null,
		tookOffice: '29 December 1843',
		leftOffice: '1 January 1844',
	},
	{
		name: 'Pedro José Arce',
		party: 'Independent',
		leaning: null,
		tookOffice: '1 January 1844',
		leftOffice: '1 February 1844',
	},
	{
		name: 'Fermín Palacios',
		party: 'Independent',
		leaning: null,
		tookOffice: '1 February 1844',
		leftOffice: '7 February 1844',
	},
	{
		name: 'Francisco Malespín',
		party: 'Conservative',
		leaning: null,
		tookOffice: '7 February 1844',
		leftOffice: '16 February 1845',
	},
	{
		name: 'Fermín Palacios',
		party: 'Independent',
		leaning: null,
		tookOffice: '16 February 1845',
		leftOffice: '25 April 1845',
	},
	{
		name: 'Joaquín Eufrasio Guzmán',
		party: 'Conservative',
		leaning: null,
		tookOffice: '25 April 1845',
		leftOffice: '1 February 1846',
	},
	{
		name: 'Fermín Palacios',
		party: 'Independent',
		leaning: null,
		tookOffice: '1 February 1846',
		leftOffice: '21 February 1846',
	},
	{
		name: 'Eugenio Aguilar',
		party: 'Liberal',
		leaning: null,
		tookOffice: '21 February 1846',
		leftOffice: '12 July 1846',
	},
	{
		name: 'Fermín Palacios',
		party: 'Independent',
		leaning: null,
		tookOffice: '12 July 1846',
		leftOffice: '21 July 1846',
	},
	{
		name: 'Eugenio Aguilar',
		party: 'Liberal',
		leaning: null,
		tookOffice: '12 July 1846',
		leftOffice: '1 February 1848',
	},
	{
		name: 'Tomás Medina',
		party: 'Independent',
		leaning: null,
		tookOffice: '1 February 1848',
		leftOffice: '3 February 1848',
	},
	{
		name: 'José Félix Quirós',
		party: 'Independent',
		leaning: null,
		tookOffice: '3 February 1848',
		leftOffice: '7 February 1848',
	},
	{
		name: 'Doroteo Vasconcelos',
		party: 'Liberal',
		leaning: null,
		tookOffice: '7 February 1848',
		leftOffice: '26 January 1850',
	},
	{
		name: 'Ramón Rodríguez',
		party: 'Independent',
		leaning: null,
		tookOffice: '26 January 1850',
		leftOffice: '1 February 1850',
	},
	{
		name: 'Doroteo Vasconcelos',
		party: 'Liberal',
		leaning: null,
		tookOffice: '1 February 1850',
		leftOffice: '12 January 1851',
	},
	{
		name: 'Francisco Dueñas',
		party: 'Conservative',
		leaning: null,
		tookOffice: '12 January 1851',
		leftOffice: '1 March 1851',
	},
	{
		name: 'José Félix Quirós',
		party: 'Independent',
		leaning: null,
		tookOffice: '1 March 1851',
		leftOffice: '3 May 1851',
	},
	{
		name: 'Francisco Dueñas',
		party: 'Conservative',
		leaning: null,
		tookOffice: '3 May 1851',
		leftOffice: '30 January 1852',
	},
	{
		name: 'José María San Martín',
		party: 'Conservative',
		leaning: null,
		tookOffice: '30 January 1852',
		leftOffice: '1 February 1852',
	},
	{
		name: 'Francisco Dueñas',
		party: 'Conservative',
		leaning: null,
		tookOffice: '1 February 1852',
		leftOffice: '1 February 1854',
	},
	{
		name: 'Vicente Gómez',
		party: 'Independent',
		leaning: null,
		tookOffice: '1 February 1854',
		leftOffice: '15 February 1854',
	},
	{
		name: 'José María San Martín',
		party: 'Conservative',
		leaning: null,
		tookOffice: '15 February 1854',
		leftOffice: '1 February 1856',
	},
	{
		name: 'Francisco Dueñas',
		party: 'Conservative',
		leaning: null,
		tookOffice: '1 February 1856',
		leftOffice: '12 February 1856',
	},
	{
		name: 'Rafael Campo',
		party: 'Conservative',
		leaning: null,
		tookOffice: '12 February 1856',
		leftOffice: '12 May 1856',
	},
	{
		name: 'Francisco Dueñas',
		party: 'Conservative',
		leaning: null,
		tookOffice: '12 May 1856',
		leftOffice: '19 July 1856',
	},
	{
		name: 'Rafael Campo',
		party: 'Conservative',
		leaning: null,
		tookOffice: '19 July 1856',
		leftOffice: '1 February 1858',
	},
	{
		name: 'Lorenzo Zepeda',
		party: 'Independent',
		leaning: null,
		tookOffice: '1 February 1858',
		leftOffice: '7 February 1858',
	},
	{
		name: 'Miguel Santín del Castillo',
		party: 'Conservative',
		leaning: null,
		tookOffice: '7 February 1858',
		leftOffice: '24 June 1858',
	},
	{
		name: 'Gerardo Barrios',
		party: 'Liberal',
		leaning: null,
		tookOffice: '24 June 1858',
		leftOffice: '18 September 1858',
	},
	{
		name: 'Miguel Santín del Castillo',
		party: 'Conservative',
		leaning: null,
		tookOffice: '18 September 1858',
		leftOffice: '19 January 1859',
	},
	{
		name: 'Joaquín Eufrasio Guzmán',
		party: 'Conservative',
		leaning: null,
		tookOffice: '19 January 1859',
		leftOffice: '15 February 1859',
	},
	{
		name: 'José María Peralta',
		party: 'Independent',
		leaning: null,
		tookOffice: '15 February 1859',
		leftOffice: '12 March 1859',
	},
	{
		name: 'Gerardo Barrios',
		party: 'Liberal',
		leaning: null,
		tookOffice: '12 March 1859',
		leftOffice: '1 February 1860',
	},
	{
		name: 'Gerardo Barrios',
		party: 'Liberal',
		leaning: null,
		tookOffice: '1 February 1860',
		leftOffice: '16 December 1860',
	},
	{
		name: 'José María Peralta',
		party: 'Independent',
		leaning: null,
		tookOffice: '16 December 1860',
		leftOffice: '7 February 1861',
	},
	{
		name: 'Gerardo Barrios',
		party: 'Liberal',
		leaning: null,
		tookOffice: '7 February 1861',
		leftOffice: '26 October 1863',
	},
	{
		name: 'Francisco Dueñas',
		party: 'Conservative',
		leaning: null,
		tookOffice: '26 October 1863',
		leftOffice: '1 February 1865',
	},
	{
		name: 'Francisco Dueñas',
		party: 'Conservative',
		leaning: null,
		tookOffice: '1 February 1865',
		leftOffice: '12 April 1871',
	},
	{
		name: 'Santiago González Portillo',
		party: 'Liberal',
		leaning: null,
		tookOffice: '12 April 1871',
		leftOffice: '1 February 1872',
	},
	{
		name: 'Santiago González Portillo',
		party: 'Liberal',
		leaning: null,
		tookOffice: '1 February 1872',
		leftOffice: '10 May 1872',
	},
	{
		name: 'Manuel Méndez',
		party: 'Independent',
		leaning: null,
		tookOffice: '10 May 1872',
		leftOffice: '16 June 1872',
	},
	{
		name: 'Santiago González Portillo',
		party: 'Liberal',
		leaning: null,
		tookOffice: '16 June 1872',
		leftOffice: '1 February 1876',
	},
	{
		name: 'Andrés del Valle',
		party: 'Liberal',
		leaning: null,
		tookOffice: '1 February 1876',
		leftOffice: '1 May 1876',
	},
	{
		name: 'Rafael Zaldívar',
		party: 'Liberal',
		leaning: null,
		tookOffice: '1 May 1876',
		leftOffice: '1 February 1880',
	},
	// TODO REVERSE ORDER
	{
		countryId,
		name: `Nayib Armando Bukele Ortez`,
		party: `Nuevas Ideas`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `1 June 2019`,
		leftOffice: null,
	},
	{
		countryId,
		name: `Salvador Sánchez Cerén`,
		party: `Farabundo Martí National Liberation Front`,
		leaning: leanings.FAR_LEFT,
		tookOffice: `1 June 2014`,
		leftOffice: `1 June 2019`,
	},
	{
		countryId,
		name: `Mauricio Funes`,
		party: `Farabundo Martí National Liberation Front`,
		leaning: leanings.FAR_LEFT,
		tookOffice: `1 June 2009`,
		leftOffice: `1 June 2014`,
	},
	{
		countryId,
		name: `Antonio Saca`,
		party: `Nationalist Republican Alliance`,
		leaning: leanings.RIGHT,
		tookOffice: `1 June 2004`,
		leftOffice: `1 June 2009`,
	},
	{
		countryId,
		name: `Francisco Flores Pérez`,
		party: `Nationalist Republican Alliance`,
		leaning: leanings.RIGHT,
		tookOffice: `1 June 1999`,
		leftOffice: `1 June 2004`,
	},
	{
		countryId,
		name: `Armando Calderón Sol`,
		party: `Nationalist Republican Alliance`,
		leaning: leanings.RIGHT,
		tookOffice: `1 June 1994`,
		leftOffice: `1 June 1999`,
	},
	{
		countryId,
		name: `Alfredo Cristiani`,
		party: `Nationalist Republican Alliance`,
		leaning: leanings.RIGHT,
		tookOffice: `1 June 1989`,
		leftOffice: `1 June 1994`,
	},
	{
		countryId,
		name: `José Napoleón Duarte`,
		party: `Christian Democratic Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 June 1984`,
		leftOffice: `1 June 1989`,
	},
	{
		countryId,
		name: `Álvaro Magaña`,
		party: `Nationalist Republican Alliance`,
		leaning: leanings.RIGHT,
		tookOffice: `2 May 1982`,
		leftOffice: `1 June 1984`,
	},
	{
		countryId,
		name: `Revolutionary Government Junta`,
		party: `Armed Forces of El Salvador`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `15 October 1979`,
		leftOffice: `2 May 1982`,
	},
	{
		countryId,
		name: `Carlos Humberto Romero`,
		party: `Armed Forces of El Salvador / Party of National Conciliation`,
		leaning: leanings.RIGHT,
		tookOffice: `1 July 1977`,
		leftOffice: `15 October 1979`,
	},
	{
		countryId,
		name: `Arturo Armando Molina`,
		party: `Armed Forces of El Salvador / Party of National Conciliation`,
		leaning: leanings.RIGHT,
		tookOffice: `1 July 1972`,
		leftOffice: `1 July 1977`,
	},
	{
		countryId,
		name: `Fidel Sánchez Hernández`,
		party: `National Coalition Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 July 1967`,
		leftOffice: `1 July 1972`,
	},
	{
		countryId,
		name: `Julio Adalberto Rivera`,
		party: `National Coalition Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 July 1962`,
		leftOffice: `1 July 1967`,
	},
	{
		countryId,
		name: `Eusebio Rodolfo Cordón Cea`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `25 January 1962`,
		leftOffice: `1 July 1962`,
	},
	{
		countryId,
		name: `Civic-Military Directory`,
		party: `Civic-Military Directory`,
		leaning: 0,
		tookOffice: `25 January 1961`,
		leftOffice: `25 January 1962`,
	},
	{
		countryId,
		name: `Junta of Government`,
		party: `Junta of Government`,
		leaning: 0,
		tookOffice: `26 October 1960`,
		leftOffice: `25 January 1961`,
	},
	{
		countryId,
		name: `José María Lemus`,
		party: `Armed Forces of El Salvador / Revolutionary Party of Democratic Unification`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `14 September 1956`,
		leftOffice: `26 October 1960`,
	},
	{
		countryId,
		name: `Óscar Osorio`,
		party: `Armed Forces of El Salvador / Revolutionary Party of Democratic Unification`,
		leaning: leanings.RIGHT,
		tookOffice: `14 September 1950`,
		leftOffice: `14 September 1956`,
	},
	{
		countryId,
		name: `Revolutionary Council of Government`,
		party: `Revolutionary Council of Government`,
		leaning: leanings.CENTRIST,
		tookOffice: `15 December 1948`,
		leftOffice: `14 September 1950`,
	},
	{
		countryId,
		name: `Salvador Castaneda Castro`,
		party: `Armed Forces of El Salvador / Unification Social Democratic Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `1 March 1945`,
		leftOffice: `14 December 1948`,
	},
	{
		countryId,
		name: `Osmín Aguirre y Salinas`,
		party: `Armed Forces of El Salvador`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `21 October 1944`,
		leftOffice: `1 March 1945`,
	},
	{
		countryId,
		name: `Andrés Ignacio Menéndez`,
		party: `Armed Forces of El Salvador / National Pro-Patria Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `9 May 1944`,
		leftOffice: `20 October 1944`,
	},
	{
		countryId,
		name: `Maximiliano Hernández Martínez`,
		party: `National Pro Patria Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `1 March 1935`,
		leftOffice: `9 May 1944`,
	},
	{
		countryId,
		name: `Andrés Ignacio Menéndez`,
		party: `Armed Forces of El Salvador/National Pro-Patria Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `29 August 1934`,
		leftOffice: `1 March 1935`,
	},
	{
		countryId,
		name: `Maximiliano Hernández Martínez`,
		party: `National Pro Patria Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `4 December 1931`,
		leftOffice: `28 August 1934`,
	},
	{
		countryId,
		name: `Arturo Araujo`,
		party: `Labor Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 March 1931`,
		leftOffice: `2 December 1931`,
	},
	{
		countryId,
		name: `Pío Romero Bosque`,
		party: `National Democratic Party`,
		leaning: 0,
		tookOffice: `1 March 1927`,
		leftOffice: `1 March 1931`,
	},
	{
		countryId,
		name: `Alfonso Quiñónez Molina`,
		party: `National Democratic Party`,
		leaning: 0,
		tookOffice: `1 March 1923`,
		leftOffice: `1 March 1927`,
	},
	{
		countryId,
		name: `Jorge Meléndez`,
		party: `National Democratic Party`,
		leaning: 0,
		tookOffice: `1 March 1919`,
		leftOffice: `1 March 1923`,
	},
	{
		countryId,
		name: `Alfonso Quiñónez Molina`,
		party: `National Democratic Party`,
		leaning: 0,
		tookOffice: `21 December 1918`,
		leftOffice: `1 March 1919`,
	},
	{
		countryId,
		name: `Carlos Meléndez`,
		party: `National Democratic Party`,
		leaning: 0,
		tookOffice: `1 March 1915`,
		leftOffice: `21 December 1918`,
	},
	{
		countryId,
		name: `Manuel Enrique Araujo`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1911`,
		leftOffice: `8 February 1913`,
	},
	{
		countryId,
		name: `Fernando Figueroa`,
		party: `Armed Forces of El Salvador - Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `1 March 1907`,
		leftOffice: `1 March 1911`,
	},
	{
		countryId,
		name: `Pedro José Escalón`,
		party: `Armed Forces of El Salvador - Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 March 1903`,
		leftOffice: `1 March 1907`,
	},
	{
		countryId,
		name: `Tomás Regalado`,
		party: `Armed Forces of El Salvador - Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `14 November 1898`,
		leftOffice: `1 March 1903`,
	},
	{
		countryId,
		name: `Rafael Antonio Gutiérrez`,
		party: `Armed Forces of El Salvador - Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `10 June 1894`,
		leftOffice: `13 November 1898`,
	},
	{
		countryId,
		name: `Carlos Basilio Ezeta y León`,
		party: `Armed Forces of El Salvador - Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `22 June 1890`,
		leftOffice: `9 June 1894`,
	},
	{
		countryId,
		name: `Francisco Menéndez`,
		party: `Armed Forces of El Salvador - Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `21 June 1885`,
		leftOffice: `22 June 1890`,
	},
	{
		countryId,
		name: `Rafael Zaldívar`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `1 May 1876`,
		leftOffice: `21 June 1885`,
	},
	{
		countryId,
		name: `Andrés del Valle`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `1 February 1876`,
		leftOffice: `1 May 1876`,
	},
];
