import type { LeaderNoId } from '../../app/data/types';
import { leanings } from '../../app/data/types';

export const source = `https://www.mapsofworld.com/list-of/presidents-guatemala/`;

const countryId = 3;

export const guatemala: LeaderNoId[] = [
	{
		countryId,
		name: `Alejandro Giammattei`,
		party: `Vamos`,
		leaning: leanings.RIGHT,
		tookOffice: `14 January 2020`,
		leftOffice: null,
	},
	{
		countryId,
		name: `Jimmy Morales`,
		party: `National Convergence Front`,
		leaning: leanings.RIGHT,
		tookOffice: `14 January 2016`,
		leftOffice: `14 January 2020`,
	},
	{
		countryId,
		name: `Alejandro Maldonado`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `3 September 2015`,
		leftOffice: `14 January 2016`,
	},
	{
		countryId,
		name: `Otto Pérez Molina`,
		party: `Patriotic Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `14 January 2012`,
		leftOffice: `3 September 2015`,
	},
	{
		countryId,
		name: `Álvaro Colom`,
		party: `National Unity of Hope`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `14 January 2008`,
		leftOffice: `14 January 2012`,
	},
	{
		countryId,
		name: `Óscar Berger`,
		party: `National Solidarity Party / Grand National Alliance`,
		leaning: leanings.RIGHT,
		tookOffice: `14 January 2004`,
		leftOffice: `14 January 2008`,
	},
	{
		countryId,
		name: `Alfonso Portillo`,
		party: `Guatemalan Republican Front`,
		leaning: leanings.RIGHT,
		tookOffice: `14 January 2000`,
		leftOffice: `14 January 2004`,
	},
	{
		countryId,
		name: `Álvaro Arzú`,
		party: `National Advancement Party / Unionist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `14 January 1996`,
		leftOffice: `14 January 2000`,
	},
	{
		countryId,
		name: `Ramiro de León`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `6 June 1993`,
		leftOffice: `14 January 1996`,
	},
	{
		countryId,
		name: `Gustavo Espina`,
		party: `Solidarity Action Movement`,
		leaning: leanings.RIGHT,
		tookOffice: `1 June 1993`,
		leftOffice: `5 June 1993`,
	},
	{
		countryId,
		name: `Jorge Serrano`,
		party: `Solidarity Action Movement`,
		leaning: leanings.RIGHT,
		tookOffice: `14 January 1991`,
		leftOffice: `1 June 1993`,
	},
	{
		countryId,
		name: `Vinicio Cerezo`,
		party: `Guatemalan Christian Democrats`,
		leaning: leanings.CENTRIST,
		tookOffice: `14 January 1986`,
		leftOffice: `14 January 1991`,
	},
	{
		countryId,
		name: `Óscar Humberto Mejía Victores`,
		party: `Armed Forces of Guatemala`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `8 August 1983`,
		leftOffice: `14 January 1986`,
	},
	{
		countryId,
		name: `Efraín Ríos Montt`,
		party: `Armed Forces of Guatemala`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `23 March 1982`,
		leftOffice: `8 August 1983`,
	},
	{
		countryId,
		name: `Fernando Romeo Lucas Garcia`,
		party: `Institutional Democratic Party / Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 July 1978`,
		leftOffice: `23 March 1982`,
	},
	{
		countryId,
		name: `Kjell Eugenio Laugerud García`,
		party: `National Liberation Movement / Institutional Democratic Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 July 1974`,
		leftOffice: `1 July 1978`,
	},
	{
		countryId,
		name: `Carlos Arana Osorio`,
		party: `Armed Forces of Guatemala / Institutional Democratic Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 July 1970`,
		leftOffice: `1 July 1974`,
	},
	{
		countryId,
		name: `Julio César Méndez Montenegro`,
		party: `Revolutionary Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 July 1966`,
		leftOffice: `1 July 1970`,
	},
	{
		countryId,
		name: `Enrique Peralta Azurdia`,
		party: `Institutional Democratic Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `31 March 1963`,
		leftOffice: `1 July 1966`,
	},
	{
		countryId,
		name: `Miguel Ydígoras Fuentes`,
		party: `National Democratic Reconciliation Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `2 March 1958`,
		leftOffice: `31 March 1963`,
	},
	{
		countryId,
		name: `Guillermo Flores Avendaño`,
		party: `Armed Forces of Guatemala`,
		leaning: 0,
		tookOffice: `26 October 1957`,
		leftOffice: `2 March 1958`,
	},
	{
		countryId,
		name: `Óscar Mendoza Azurdia`,
		party: `Armed Forces of Guatemala`,
		leaning: 0,
		tookOffice: `24 October 1957`,
		leftOffice: `26 October 1957`,
	},
	{
		countryId,
		name: `Luis Arturo González López`,
		party: `National Liberation Movement`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `27 July 1957`,
		leftOffice: `24 October 1957`,
	},
	{
		countryId,
		name: `Carlos Castillo Armas`,
		party: `National Liberation Movement`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `8 July 1954`,
		leftOffice: `26 July 1957`,
	},
	{
		countryId,
		name: `Elfego Hernán Monzón Aguirre`,
		party: `Armed Forces of Guatemala`,
		leaning: 0,
		tookOffice: `29 June 1954`,
		leftOffice: `8 July 1954`,
	},
	{
		countryId,
		name: `Carlos Enrique Díaz de León`,
		party: `Armed Forces of Guatemala`,
		leaning: 0,
		tookOffice: `27 June 1954`,
		leftOffice: `28 June 1954`,
	},
	{
		countryId,
		name: `Jacobo Árbenz`,
		party: `Revolutionary Action Party`,
		leaning: leanings.LEFT,
		tookOffice: `15 March 1951`,
		leftOffice: `27 June 1954`,
	},
	{
		countryId,
		name: `Juan José Arévalo`,
		party: `Revolutionary Action Party`,
		leaning: leanings.LEFT,
		tookOffice: `15 March 1945`,
		leftOffice: `15 March 1951`,
	},
	{
		countryId,
		name: `Revolutionary Government Junta`,
		party: `Armed Forces of Guatemala`,
		leaning: leanings.CENTRIST,
		tookOffice: `20 October 1944`,
		leftOffice: `15 March 1945`,
	},
	{
		countryId,
		name: `Juan Federico Ponce Vaides`,
		party: `Progressive Liberal Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `4 July 1944`,
		leftOffice: `20 October 1944`,
	},
	{
		countryId,
		name: `Jorge Ubico Castañeda`,
		party: `Progressive Liberal Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `14 February 1931`,
		leftOffice: `4 July 1944`,
	},
	{
		countryId,
		name: `José María Reina Andrade`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `2 January 1931`,
		leftOffice: `14 February 1931`,
	},
	{
		countryId,
		name: `Lázaro Chacón González`,
		party: `Unionist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `26 September 1926`,
		leftOffice: `2 January 1931`,
	},
	{
		countryId,
		name: `José María Orellana Pinto`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `10 December 1921`,
		leftOffice: `26 September 1926`,
	},
	{
		countryId,
		name: `Carlos Herrera y Luna`,
		party: `Unionist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `15 April 1920`,
		leftOffice: `10 December 1921`,
	},
	{
		countryId,
		name: `Manuel Estrada Cabrera`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `8 February 1898`,
		leftOffice: `15 April 1920`,
	},
	{
		countryId,
		name: `José María Reina Barrios`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `15 March 1892`,
		leftOffice: `8 February 1898`,
	},
	{
		countryId,
		name: `Manuel Barillas`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `6 April 1885`,
		leftOffice: `15 March 1892`,
	},
	{
		countryId,
		name: `Alejandro M. Sinibaldi`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `2 April 1885`,
		leftOffice: `5 April 1885`,
	},
	{
		countryId,
		name: `Justo Rufino Barrios`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `4 June 1873`,
		leftOffice: `2 April 1885`,
	},
	{
		countryId,
		name: `Miguel García Granados`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `29 June 1871`,
		leftOffice: `4 June 1873`,
	},
	{
		countryId,
		name: `Vicente Cerna Sandoval`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `24 May 1865`,
		leftOffice: `29 June 1871`,
	},
	{
		countryId,
		name: `Pedro de Aycinena y Piñol`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `14 April 1865`,
		leftOffice: `24 May 1865`,
	},
	{
		countryId,
		name: `Rafael Carrera`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `6 November 1851`,
		leftOffice: `14 April 1865`,
	},
	{
		countryId,
		name: `Mariano Peredes`,
		party: `Non-partisan`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 January 1849`,
		leftOffice: `6 November 1851`,
	},
	{
		countryId,
		name: `José Bernardo Escobar`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `28 November 1848`,
		leftOffice: `1 January 1849`,
	},
];
