import type { LeaderNoId } from '../../app/data/types';
import { leanings } from '../../app/data/types';

export const source = `https://en.wikipedia.org/wiki/List_of_heads_of_state_of_Haiti`;

const countryId = 26;

export const haiti: LeaderNoId[] = [
	{
		countryId,
		name: `Toussaint Louverture`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 January 1791`,
		leftOffice: `6 May 1802`,
	},
	{
		name: 'Vacant ',
		party: null,
		leaning: null,
		tookOffice: '6 May 1802',
		leftOffice: '1 January 1804',
	},
	{
		name: 'Jean-Jacques Dessalines',
		party: 'Independent',
		leaning: null,
		tookOffice: '1 January 1804',
		leftOffice: '22 September 1804',
	},
	{
		name: 'Jacques I',
		party: null,
		leaning: null,
		tookOffice: '22 September 1804',
		leftOffice: '17 October 1806',
	},
	{
		name: 'Henri Christophe',
		party: 'Independent',
		leaning: null,
		tookOffice: '17 October 1806',
		leftOffice: '28 March 1811',
	},
	{
		name: 'Henry I',
		party: null,
		leaning: null,
		tookOffice: '28 March 1811',
		leftOffice: '8 October 1820',
	},
	{
		name: 'Alexandre Pétion',
		party: 'Independent',
		leaning: null,
		tookOffice: '17 October 1806',
		leftOffice: '29 March 1818',
	},
	{
		name: 'Jean-Pierre Boyer',
		party: 'Independent',
		leaning: null,
		tookOffice: '30 March 1818',
		leftOffice: '18 October 1820',
	},
	{
		name: 'Jean-Pierre Boyer',
		party: 'Independent',
		leaning: null,
		tookOffice: '18 October 1820',
		leftOffice: '13 February 1843',
	},
	{
		name: 'Charles Rivière-Hérard',
		party: 'Independent',
		leaning: null,
		tookOffice: '4 April 1843',
		leftOffice: '3 May 1844',
	},
	{
		name: 'Philippe Guerrier',
		party: 'Independent',
		leaning: null,
		tookOffice: '3 May 1844',
		leftOffice: '15 April 1845',
	},
	{
		name: 'Jean-Louis Pierrot',
		party: 'Independent',
		leaning: null,
		tookOffice: '16 April 1845',
		leftOffice: '24 March 1846',
	},
	{
		name: 'Jean-Baptiste Riché',
		party: 'Independent',
		leaning: null,
		tookOffice: '24 March 1846',
		leftOffice: '28 February 1847',
	},
	{
		name: 'Faustin Soulouque',
		party: 'Independent',
		leaning: null,
		tookOffice: '2 March 1847',
		leftOffice: '26 August 1849',
	},
	{
		name: 'Faustin I',
		party: null,
		leaning: null,
		tookOffice: '26 August 1849',
		leftOffice: '22 January 1859',
	},
	{
		name: 'Fabre Geffrard',
		party: 'Independent',
		leaning: null,
		tookOffice: '22 January 1859',
		leftOffice: '13 March 1867',
	},
	{
		name: 'Jean-Nicolas Nissage Saget',
		party: 'Independent',
		leaning: null,
		tookOffice: '20 March 1867',
		leftOffice: '2 May 1867',
	},
	{
		name: 'Sylvain Salnave',
		party: 'Independent',
		leaning: null,
		tookOffice: '4 May 1867',
		leftOffice: '27 December 1869',
	},
	{
		name: 'Jean-Nicolas Nissage Saget',
		party: 'Liberal party',
		leaning: null,
		tookOffice: '27 December 1869',
		leftOffice: '14 May 1874',
	},
	{
		name: 'Council of Secretaries of State',
		party: 'Independent',
		leaning: null,
		tookOffice: '14 May 1874',
		leftOffice: '14 June 1874',
	},
	{
		name: 'Michel Domingue',
		party: 'Independent',
		leaning: null,
		tookOffice: '14 June 1874',
		leftOffice: '15 April 1876',
	},
	{
		name: 'Pierre Théoma Boisrond-Canal',
		party: 'Liberal party',
		leaning: null,
		tookOffice: '23 April 1876',
		leftOffice: '17 July 1879',
	},
	{
		name: 'Joseph Lamothe',
		party: 'Independent',
		leaning: null,
		tookOffice: '26 July 1879',
		leftOffice: '2 October 1879',
	},
	{
		name: 'Lysius Salomon',
		party: 'National party',
		leaning: null,
		tookOffice: '2 October 1879',
		leftOffice: '10 August 1888',
	},
	{
		name: 'Pierre Théoma Boisrond-Canal',
		party: 'Liberal party',
		leaning: null,
		tookOffice: '10 August 1888',
		leftOffice: '16 October 1888',
	},
	{
		name: 'François Denys Légitime',
		party: 'Liberal party',
		leaning: null,
		tookOffice: '16 October 1888',
		leftOffice: '23 August 1889',
	},
	{
		name: 'Monpoint Jeune',
		party: 'Independent',
		leaning: null,
		tookOffice: '23 August 1889',
		leftOffice: '17 October 1889',
	},
	{
		name: 'Florvil Hyppolite',
		party: 'National party',
		leaning: null,
		tookOffice: '17 October 1889',
		leftOffice: '24 March 1896',
	},
	{
		name: 'Tirésias Simon Sam',
		party: 'National party',
		leaning: null,
		tookOffice: '31 March 1896',
		leftOffice: '12 May 1902',
	},
	{
		name: 'Pierre Théoma Boisrond-Canal',
		party: 'Liberal party',
		leaning: null,
		tookOffice: '26 May 1902',
		leftOffice: '17 December 1902',
	},
	{
		name: 'Pierre Nord Alexis',
		party: 'Military',
		leaning: null,
		tookOffice: '21 December 1902',
		leftOffice: '2 December 1908',
	},
	{
		name: 'François C. Antoine Simon',
		party: 'Liberal party',
		leaning: null,
		tookOffice: '6 December 1908',
		leftOffice: '3 August 1911',
	},
	{
		name: 'Cincinnatus Leconte',
		party: 'National party',
		leaning: null,
		tookOffice: '15 August 1911',
		leftOffice: '8 August 1912',
	},
	{
		name: 'Tancrède Auguste',
		party: 'National party',
		leaning: null,
		tookOffice: '8 August 1912',
		leftOffice: '2 May 1913',
	},
	{
		name: 'Michel Oreste',
		party: 'Independent',
		leaning: null,
		tookOffice: '12 May 1913',
		leftOffice: '27 January 1914',
	},
	{
		name: 'Oreste Zamor',
		party: 'Military',
		leaning: null,
		tookOffice: '8 February 1914',
		leftOffice: '29 October 1914',
	},
	{
		name: 'Joseph Davilmar Théodore',
		party: 'Military',
		leaning: null,
		tookOffice: '7 November 1914',
		leftOffice: '22 February 1915',
	},
	{
		name: 'Vilbrun Guillaume Sam',
		party: 'Military',
		leaning: null,
		tookOffice: '25 February 1915',
		leftOffice: '28 July 1915',
	},
	{
		name: 'Philippe Sudré Dartiguenave',
		party: 'Independent',
		leaning: null,
		tookOffice: '12 August 1915',
		leftOffice: '15 May 1922',
	},
	{
		name: 'Louis Borno',
		party: 'Independent',
		leaning: null,
		tookOffice: '15 May 1922',
		leftOffice: '15 May 1930',
	},
	{
		name: 'Louis Eugène Roy',
		party: 'Independent',
		leaning: null,
		tookOffice: '15 May 1930',
		leftOffice: '18 November 1930',
	},
	{
		name: 'Sténio Vincent',
		party: 'Independent',
		leaning: null,
		tookOffice: '18 November 1930',
		leftOffice: '15 May 1941',
	},
	{
		name: 'Élie Lescot',
		party: 'Liberal party',
		leaning: null,
		tookOffice: '15 May 1941',
		leftOffice: '11 January 1946',
	},
	{
		name: 'Franck Lavaud',
		party: 'Military',
		leaning: null,
		tookOffice: '11 January 1946',
		leftOffice: '16 August 1946',
	},
	{
		name: 'Dumarsais Estimé',
		party: 'Independent',
		leaning: null,
		tookOffice: '16 August 1946',
		leftOffice: '10 May 1950',
	},
	{
		name: 'Franck Lavaud',
		party: 'Military',
		leaning: null,
		tookOffice: '10 May 1950',
		leftOffice: '6 December 1950',
	},
	{
		name: 'Paul Magloire',
		party: null,
		leaning: null,
		tookOffice: '6 December 1950',
		leftOffice: '12 December 1956',
	},
	{
		name: 'Joseph Nemours Pierre-Louis',
		party: 'Independent',
		leaning: null,
		tookOffice: '12 December 1956',
		leftOffice: '3 February 1957',
	},
	{
		name: 'Franck Sylvain',
		party: 'Independent',
		leaning: null,
		tookOffice: '7 February 1957',
		leftOffice: '2 April 1957',
	},
	{
		name: 'Executive Government Council',
		party: 'Independent',
		leaning: null,
		tookOffice: '2 April 1957',
		leftOffice: '25 May 1957',
	},
	{
		name: 'Daniel Fignolé',
		party: null,
		leaning: null,
		tookOffice: '25 May 1957',
		leftOffice: '14 June 1957',
	},
	{
		name: 'Antonio Thrasybule Kébreau',
		party: 'Military',
		leaning: null,
		tookOffice: '14 June 1957',
		leftOffice: '22 October 1957',
	},
	{
		countryId,
		name: `François Duvalier`,
		party: `National Unity Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `22 October 1957`,
		leftOffice: `21 April 1971`,
	},
	{
		countryId,
		name: `Jean-Claude Duvalier`,
		party: `National Unity Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `21 April 1971`,
		leftOffice: `7 February 1986`,
	},
	{
		countryId,
		name: `Henri Namphy`,
		party: `Armed Forces of Haiti`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 February 1986`,
		leftOffice: `7 February 1988`,
	},
	{
		countryId,
		name: `Leslie Manigat`,
		party: `Rally of Progressive National Democrats`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `7 February 1988`,
		leftOffice: `20 June 1988`,
	},
	{
		countryId,
		name: `Henri Namphy`,
		party: `Armed Forces of Haiti`,
		leaning: leanings.CENTRIST,
		tookOffice: `20 June 1988`,
		leftOffice: `17 September 1988`,
	},
	{
		countryId,
		name: `Prosper Avril`,
		party: `Armed Forces of Haiti`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `17 September 1988`,
		leftOffice: `10 March 1990`,
	},
	{
		countryId,
		name: `Hérard Abraham`,
		party: `Armed Forces of Haiti`,
		leaning: leanings.CENTRIST,
		tookOffice: `10 March 1990`,
		leftOffice: `13 March 1990`,
	},
	{
		countryId,
		name: `Ertha Pascal-Trouillot`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `13 March 1990`,
		leftOffice: `7 February 1991`,
	},
	{
		countryId,
		name: `Jean-Bertrand Aristide`,
		party: `Struggling People's Organization`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `7 February 1991`,
		leftOffice: `29 September 1991`,
	},
	{
		countryId,
		name: `Raoul Cédras`,
		party: `Armed Forces of Haiti`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `29 September 1991`,
		leftOffice: `8 October 1991`,
	},
	{
		countryId,
		name: `Joseph Nérette`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `8 October 1991`,
		leftOffice: `19 June 1992`,
	},
	{
		countryId,
		name: `Council of Ministers & Prime Minister Marc Bazin`,
		party: `Movement for the Instauration of Democracy in Haiti`,
		leaning: leanings.RIGHT,
		tookOffice: `19 June 1992`,
		leftOffice: `15 June 1993`,
	},
	{
		countryId,
		name: `Jean-Bertrand Aristide`,
		party: `Struggling People's Organization`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `15 June 1993`,
		leftOffice: `12 May 1994`,
	},
	{
		countryId,
		name: `Émile Jonassaint`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `12 May 1994`,
		leftOffice: `12 October 1994`,
	},
	{
		countryId,
		name: `Jean-Bertrand Aristide`,
		party: `Struggling People's Organization`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `12 October 1994`,
		leftOffice: `7 February 1996`,
	},
	{
		countryId,
		name: `René Préval`,
		party: `Lavalas Family`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `7 February 1996`,
		leftOffice: `7 February 2001`,
	},
	{
		countryId,
		name: `Jean-Bertrand Aristide`,
		party: `Lavalas Family`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `7 February 2001`,
		leftOffice: `29 February 2004`,
	},
	{
		countryId,
		name: `Boniface Alexandre`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `29 February 2004`,
		leftOffice: `14 May 2006`,
	},
	{
		countryId,
		name: `René Préval`,
		party: `Lespwa / Inite`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `14 May 2006`,
		leftOffice: `14 May 2011`,
	},
	{
		countryId,
		name: `Michel Martelly`,
		party: `Repons Peyizan`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `14 May 2011`,
		leftOffice: `7 February 2016`,
	},
	{
		countryId,
		name: `Council of Ministers & Prime Minister Evans Paul`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 February 2016`,
		leftOffice: `14 February 2016`,
	},
	{
		countryId,
		name: `Jocelerme Privert`,
		party: `Inite`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `14 February 2016`,
		leftOffice: `7 February 2017`,
	},
	{
		countryId,
		name: `Jovenel Moïse`,
		party: `Haitian Tèt Kale Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `7 February 2017`,
		leftOffice: `7 July 2021`,
	},
	{
		countryId,
		name: `Claude Joseph`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 July 2021`,
		leftOffice: `20 July 2021`,
	},
	{
		countryId,
		name: `Ariel Henry`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `20 July 2021`,
		leftOffice: null,
	},
];
