import type { LeaderNoId } from '../../app/data/types';
import { leanings } from '../../app/data/types';

export const source = `https://en.wikipedia.org/wiki/List_of_heads_of_state_of_Haiti`;

const countryId = 26;

export const haiti: LeaderNoId[] = [
	{
		countryId,
		name: `Toussaint Louverture`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 January 1791`,
		leftOffice: `6 May 1802`,
	},
	{
		countryId,
		name: `François Duvalier`,
		party: `National Unity Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `22 October 1957`,
		leftOffice: `21 April 1971`,
	},
	{
		countryId,
		name: `Jean-Claude Duvalier`,
		party: `National Unity Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `21 April 1971`,
		leftOffice: `7 February 1986`,
	},
	{
		countryId,
		name: `Henri Namphy`,
		party: `Armed Forces of Haiti`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 February 1986`,
		leftOffice: `7 February 1988`,
	},
	{
		countryId,
		name: `Leslie Manigat`,
		party: `Rally of Progressive National Democrats`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `7 February 1988`,
		leftOffice: `20 June 1988`,
	},
	{
		countryId,
		name: `Henri Namphy`,
		party: `Armed Forces of Haiti`,
		leaning: leanings.CENTRIST,
		tookOffice: `20 June 1988`,
		leftOffice: `17 September 1988`,
	},
	{
		countryId,
		name: `Prosper Avril`,
		party: `Armed Forces of Haiti`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `17 September 1988`,
		leftOffice: `10 March 1990`,
	},
	{
		countryId,
		name: `Hérard Abraham`,
		party: `Armed Forces of Haiti`,
		leaning: leanings.CENTRIST,
		tookOffice: `10 March 1990`,
		leftOffice: `13 March 1990`,
	},
	{
		countryId,
		name: `Ertha Pascal-Trouillot`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `13 March 1990`,
		leftOffice: `7 February 1991`,
	},
	{
		countryId,
		name: `Jean-Bertrand Aristide`,
		party: `Struggling People's Organization`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `7 February 1991`,
		leftOffice: `29 September 1991`,
	},
	{
		countryId,
		name: `Raoul Cédras`,
		party: `Armed Forces of Haiti`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `29 September 1991`,
		leftOffice: `8 October 1991`,
	},
	{
		countryId,
		name: `Joseph Nérette`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `8 October 1991`,
		leftOffice: `19 June 1992`,
	},
	{
		countryId,
		name: `Council of Ministers & Prime Minister Marc Bazin`,
		party: `Movement for the Instauration of Democracy in Haiti`,
		leaning: leanings.RIGHT,
		tookOffice: `19 June 1992`,
		leftOffice: `15 June 1993`,
	},
	{
		countryId,
		name: `Jean-Bertrand Aristide`,
		party: `Struggling People's Organization`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `15 June 1993`,
		leftOffice: `12 May 1994`,
	},
	{
		countryId,
		name: `Émile Jonassaint`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `12 May 1994`,
		leftOffice: `12 October 1994`,
	},
	{
		countryId,
		name: `Jean-Bertrand Aristide`,
		party: `Struggling People's Organization`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `12 October 1994`,
		leftOffice: `7 February 1996`,
	},
	{
		countryId,
		name: `René Préval`,
		party: `Lavalas Family`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `7 February 1996`,
		leftOffice: `7 February 2001`,
	},
	{
		countryId,
		name: `Jean-Bertrand Aristide`,
		party: `Lavalas Family`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `7 February 2001`,
		leftOffice: `29 February 2004`,
	},
	{
		countryId,
		name: `Boniface Alexandre`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `29 February 2004`,
		leftOffice: `14 May 2006`,
	},
	{
		countryId,
		name: `René Préval`,
		party: `Lespwa / Inite`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `14 May 2006`,
		leftOffice: `14 May 2011`,
	},
	{
		countryId,
		name: `Michel Martelly`,
		party: `Repons Peyizan`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `14 May 2011`,
		leftOffice: `7 February 2016`,
	},
	{
		countryId,
		name: `Council of Ministers & Prime Minister Evans Paul`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 February 2016`,
		leftOffice: `14 February 2016`,
	},
	{
		countryId,
		name: `Jocelerme Privert`,
		party: `Inite`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `14 February 2016`,
		leftOffice: `7 February 2017`,
	},
	{
		countryId,
		name: `Jovenel Moïse`,
		party: `Haitian Tèt Kale Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `7 February 2017`,
		leftOffice: `7 July 2021`,
	},
	{
		countryId,
		name: `Claude Joseph`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 July 2021`,
		leftOffice: `20 July 2021`,
	},
	{
		countryId,
		name: `Ariel Henry`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `20 July 2021`,
		leftOffice: null,
	},
];
