import type { LeaderNoId } from '../../app/data/types';
import { leanings } from '../../app/data/types';

export const source = `https://www.mapsofworld.com/list-of/presidents-honduras/`;

const countryId = 6;

export const honduras: LeaderNoId[] = [
	{
		countryId,
		name: `Xiomara Castro`,
		party: `Liberty and Refoundation`,
		leaning: leanings.LEFT,
		tookOffice: `27 January 2022`,
		leftOffice: null,
	},
	{
		countryId,
		name: `Juan Orlando Hernández`,
		party: `National Party of Honduras`,
		leaning: leanings.RIGHT,
		tookOffice: `27 January 2014`,
		leftOffice: `27 January 2022`,
	},
	{
		countryId,
		name: `Pepe Lobo`,
		party: `National Party of Honduras`,
		leaning: leanings.RIGHT,
		tookOffice: `27 January 2010`,
		leftOffice: `27 January 2014`,
	},
	{
		countryId,
		name: `Roberto Micheletti`,
		party: `Liberal Party of Honduras`,
		leaning: leanings.CENTRIST,
		tookOffice: `28 June 2009`,
		leftOffice: `27 January 2010`,
	},
	{
		countryId,
		name: `Manuel Zelaya`,
		party: `Liberal Party of Honduras`,
		leaning: leanings.CENTRIST,
		tookOffice: `27 January 2006`,
		leftOffice: `28 June 2009`,
	},
	{
		countryId,
		name: `Ricardo Maduro`,
		party: `National Party of Honduras`,
		leaning: leanings.RIGHT,
		tookOffice: `27 January 2002`,
		leftOffice: `27 January 2006`,
	},
	{
		countryId,
		name: `Carlos Flores`,
		party: `Liberal Party of Honduras`,
		leaning: leanings.CENTRIST,
		tookOffice: `27 January 1998`,
		leftOffice: `27 January 2002`,
	},
	{
		countryId,
		name: `Carlos Roberto Reina`,
		party: `Liberal Party of Honduras`,
		leaning: leanings.CENTRIST,
		tookOffice: `27 January 1994`,
		leftOffice: `27 January 1998`,
	},
	{
		countryId,
		name: `Rafael Callejas`,
		party: `National Party of Honduras`,
		leaning: leanings.RIGHT,
		tookOffice: `27 January 1990`,
		leftOffice: `27 January 1994`,
	},
	{
		countryId,
		name: `José Azcona`,
		party: `Liberal Party of Honduras`,
		leaning: leanings.CENTRIST,
		tookOffice: `27 January 1986`,
		leftOffice: `27 January 1990`,
	},
	{
		countryId,
		name: `Roberto Suazo Córdoba`,
		party: `Liberal Party of Honduras`,
		leaning: leanings.CENTRIST,
		tookOffice: `27 January 1982`,
		leftOffice: `27 January 1986`,
	},
	{
		countryId,
		name: `Policarpo Paz García`,
		party: `Armed Forces of Honduras`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1978`,
		leftOffice: `27 January 1982`,
	},
	{
		countryId,
		name: `Juan Alberto Melgar`,
		party: `Armed Forces of Honduras`,
		leaning: leanings.RIGHT,
		tookOffice: `22 April 1975`,
		leftOffice: `7 August 1978`,
	},
	{
		countryId,
		name: `Oswaldo López Arellano`,
		party: `National Party of Honduras`,
		leaning: leanings.RIGHT,
		tookOffice: `4 December 1972`,
		leftOffice: `22 April 1975`,
	},
	{
		countryId,
		name: `Ramón Ernesto Cruz Uclés`,
		party: `National Party of Honduras`,
		leaning: leanings.RIGHT,
		tookOffice: `7 June 1971`,
		leftOffice: `4 December 1972`,
	},
	{
		countryId,
		name: `Oswaldo López Arellano`,
		party: `National Party of Honduras`,
		leaning: leanings.RIGHT,
		tookOffice: `3 October 1963`,
		leftOffice: `7 June 1971`,
	},
	{
		countryId,
		name: `Ramon Villeda Morales`,
		party: `Liberal Party of Honduras`,
		leaning: leanings.CENTRIST,
		tookOffice: `21 December 1957`,
		leftOffice: `3 October 1963`,
	},
	{
		countryId,
		name: `Military Government Council`,
		party: `Armed Forces of Honduras`,
		leaning: leanings.RIGHT,
		tookOffice: `21 October 1956`,
		leftOffice: `21 December 1957`,
	},
	{
		countryId,
		name: `Julio Lozano Díaz`,
		party: `National Party of Honduras`,
		leaning: leanings.RIGHT,
		tookOffice: `5 December 1954`,
		leftOffice: `21 October 1956`,
	},
	{
		countryId,
		name: `Juan Manuel Gálvez`,
		party: `National Party of Honduras`,
		leaning: leanings.RIGHT,
		tookOffice: `1 January 1949`,
		leftOffice: `5 December 1954`,
	},
	{
		countryId,
		name: `Tiburcio Carías Andino`,
		party: `National Party of Honduras`,
		leaning: leanings.RIGHT,
		tookOffice: `1 February 1933`,
		leftOffice: `1 January 1949`,
	},
	{
		countryId,
		name: `Vicente Mejía Colindres`,
		party: `Liberal Party of Honduras`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 February 1929`,
		leftOffice: `1 February 1933`,
	},
	{
		countryId,
		name: `Miguel Paz Barahona`,
		party: `National Party of Honduras`,
		leaning: leanings.RIGHT,
		tookOffice: `1 February 1925`,
		leftOffice: `1 February 1929`,
	},
	{
		countryId,
		name: `Vicente Tosta`,
		party: `Liberal Party of Honduras`,
		leaning: leanings.CENTRIST,
		tookOffice: `30 April 1924`,
		leftOffice: `1 February 1925`,
	},
	{
		countryId,
		name: `Tiburcio Carías Andino`,
		party: `National Party of Honduras`,
		leaning: leanings.RIGHT,
		tookOffice: `27 April 1924`,
		leftOffice: `30 April 1924`,
	},
	{
		countryId,
		name: `Francisco Bueso`,
		party: `Liberal Party of Honduras`,
		leaning: leanings.CENTRIST,
		tookOffice: `10 March 1924`,
		leftOffice: `27 April 1924`,
	},
	{
		countryId,
		name: `Rafael López Gutiérrez`,
		party: `Liberal Party of Honduras`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 February 1920`,
		leftOffice: `10 March 1924`,
	},
	{
		countryId,
		name: `Francisco Bográn`,
		party: `Liberal Party of Honduras`,
		leaning: leanings.CENTRIST,
		tookOffice: `5 October 1919`,
		leftOffice: `1 February 1920`,
	},
	{
		countryId,
		name: `Vicente Mejía Colindres`,
		party: `Liberal Party of Honduras`,
		leaning: leanings.CENTRIST,
		tookOffice: `16 September 1919`,
		leftOffice: `5 October 1919`,
	},
	{
		countryId,
		name: `Salvador Aguirre`,
		party: `National Party of Honduras`,
		leaning: leanings.RIGHT,
		tookOffice: `21 March 1913`,
		leftOffice: `9 September 1919`,
	},
	{
		countryId,
		name: `Miguel R. Dávila`,
		party: `National Party of Honduras`,
		leaning: leanings.RIGHT,
		tookOffice: `18 April 1907`,
		leftOffice: `28 March 1911`,
	},
	{
		countryId,
		name: `Miguel Oquelí Bustillo`,
		party: `Liberal Party of Honduras`,
		leaning: leanings.CENTRIST,
		tookOffice: `25 February 1907`,
		leftOffice: `18 April 1907`,
	},
	{
		countryId,
		name: `Manuel Bonilla`,
		party: `National Party of Honduras`,
		leaning: leanings.RIGHT,
		tookOffice: `1 February 1912`,
		leftOffice: `21 March 1913`,
	},
	{
		countryId,
		name: `Juan Ángel Arias Boquín`,
		party: `Liberal Party of Honduras`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 February 1903`,
		leftOffice: `13 April 1903`,
	},
	{
		countryId,
		name: `Terencio Sierra`,
		party: `Liberal Party of Honduras`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 February 1899`,
		leftOffice: `1 February 1903`,
	},
	{
		countryId,
		name: `Policarpo Bonilla`,
		party: `Liberal Party of Honduras`,
		leaning: leanings.CENTRIST,
		tookOffice: `22 February 1894`,
		leftOffice: `1 February 1899`,
	},
	{
		countryId,
		name: `Domingo Vásquez`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1893`,
		leftOffice: `22 February 1894`,
	},
	{
		countryId,
		name: `Ponciano Leiva`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `30 November 1891`,
		leftOffice: `7 August 1893`,
	},
	{
		countryId,
		name: `Luis Bográn`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `30 November 1883`,
		leftOffice: `30 November 1891`,
	},
	{
		countryId,
		name: `Council of Ministers`,
		party: `Council of Ministers`,
		leaning: leanings.CENTRIST,
		tookOffice: `19 October 1883`,
		leftOffice: `30 November 1883`,
	},
	{
		countryId,
		name: `Marco Aurelio Soto`,
		party: `Liberal Party of Honduras`,
		leaning: leanings.CENTRIST,
		tookOffice: `27 August 1876`,
		leftOffice: `19 October 1883`,
	},
];
