import type { LeaderNoId } from '../../app/data/types';
import { leanings } from '../../app/data/types';

export const source = `https://en.wikipedia.org/wiki/List_of_presidents_of_Honduras`;

const countryId = 6;

export const honduras: LeaderNoId[] = [
	{
		countryId,
		name: `Captaincy General of Guatemala`,
		party: `Kingdom of Spain`,
		leaning: leanings.MONARCHY,
		tookOffice: `1 January 1609`,
		leftOffice: `15 September 1821`,
	},
	{
		countryId,
		name: `Gabino Gaínza`,
		party: `Military / Central American Independence`,
		leaning: leanings.MILITARY,
		tookOffice: `15 September 1821`,
		leftOffice: `5 January 1822`,
	},
	{
		countryId,
		name: `Agustín de Iturbide`,
		party: `First Mexican Empire`,
		leaning: leanings.MONARCHY,
		tookOffice: `5 January 1822`,
		leftOffice: `1 July 1823`,
	},
	{
		countryId,
		name: `Vicente Filísola - Federal Republic of Central America`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 July 1823`,
		leftOffice: `10 July 1823`,
	},
	{
		countryId,
		name: `First Triumvirate - Federal Republic of Central America`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `10 July 1823`,
		leftOffice: `4 October 1823`,
	},
	{
		countryId,
		name: `Second Triumvirate - Federal Republic of Central America`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `4 October 1823`,
		leftOffice: `29 April 1825`,
	},
	{
		countryId,
		name: `Manuel José Arce - Federal Republic of Central America`,
		party: `Liberal`,
		leaning: leanings.LEFT,
		tookOffice: `29 April 1825`,
		leftOffice: `13 April 1829`,
	},
	{
		countryId,
		name: `Mariano Beltranena y Llano - Federal Republic of Central America`,
		party: `Liberal`,
		leaning: leanings.LEFT,
		tookOffice: `13 April 1829`,
		leftOffice: `14 June 1829`,
	},
	{
		countryId,
		name: `Francisco Morazán - Federal Republic of Central America`,
		party: `Liberal`,
		leaning: leanings.LEFT,
		tookOffice: `14 June 1829`,
		leftOffice: `25 June 1829`,
	},
	{
		countryId,
		name: `José Francisco Barrundia - Federal Republic of Central America`,
		party: `Liberal`,
		leaning: leanings.LEFT,
		tookOffice: `25 June 1829`,
		leftOffice: `16 September 1830`,
	},
	{
		countryId,
		name: `Francisco Morazán - Federal Republic of Central America`,
		party: `Liberal`,
		leaning: leanings.LEFT,
		tookOffice: `16 September 1830`,
		leftOffice: `16 September 1834`,
	},
	{
		countryId,
		name: `José Gregorio Salazar - Federal Republic of Central America`,
		party: `Liberal`,
		leaning: leanings.LEFT,
		tookOffice: `16 September 1834`,
		leftOffice: `14 February 1835`,
	},
	{
		countryId,
		name: `Francisco Morazán - Federal Republic of Central America`,
		party: `Liberal`,
		leaning: leanings.LEFT,
		tookOffice: `14 February 1835`,
		leftOffice: `11 January 1839`,
	},
	// Independence from the Federal Republic of Central America
	{
		countryId,
		name: `Juan Francisco de Molina`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `11 January 1839`,
		leftOffice: `13 April 1839`,
	},
	{
		countryId,
		name: `Felipe Neri Medina`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `13 April 1839`,
		leftOffice: `15 April 1839`,
	},
	{
		countryId,
		name: `Juan José Alvarado`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `15 April 1839`,
		leftOffice: `27 April 1839`,
	},
	{
		countryId,
		name: `José María Guerrero`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `27 April 1839`,
		leftOffice: `10 August 1839`,
	},
	{
		countryId,
		name: `Mariano Garrigó`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `10 August 1839`,
		leftOffice: `20 August 1839`,
	},
	{
		countryId,
		name: `José María Bustillo`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `20 August 1839`,
		leftOffice: `27 August 1839`,
	},
	{
		countryId,
		name: `Council of Ministers`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `27 August 1839`,
		leftOffice: `21 September 1839`,
	},
	{
		countryId,
		name: `Francisco Zelaya y Ayes`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `21 September 1839`,
		leftOffice: `1 January 1841`,
	},
	{
		countryId,
		name: `Francisco Ferrera`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 January 1841`,
		leftOffice: `31 December 1842`,
	},
	{
		countryId,
		name: `Council of Ministers`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 January 1843`,
		leftOffice: `23 February 1843`,
	},
	{
		countryId,
		name: `Francisco Ferrera`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `23 February 1843`,
		leftOffice: `31 December 1844`,
	},
	{
		countryId,
		name: `Council of Ministers`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 January 1845`,
		leftOffice: `8 January 1845`,
	},
	{
		countryId,
		name: `Coronado Chávez`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `8 January 1845`,
		leftOffice: `1 January 1847`,
	},
	{
		countryId,
		name: `Council of Ministers`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 January 1847`,
		leftOffice: `12 February 1847`,
	},
	{
		countryId,
		name: `Juan Lindo`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `12 February 1847`,
		leftOffice: `1 February 1852`,
	},
	{
		countryId,
		name: `Francisco Gómez`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `1 February 1852`,
		leftOffice: `1 March 1852`,
	},
	{
		countryId,
		name: `José Trinidad Cabañas`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `1 March 1852`,
		leftOffice: `18 October 1855`,
	},
	{
		countryId,
		name: `José Santiago Bueso`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `18 October 1855`,
		leftOffice: `8 November 1855`,
	},
	{
		countryId,
		name: `Francisco de Aguilar`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `8 November 1855`,
		leftOffice: `17 February 1856`,
	},
	{
		countryId,
		name: `José Santos Guardiola`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `17 February 1856`,
		leftOffice: `11 January 1862`,
	},
	{
		countryId,
		name: `José Francisco Montes`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `11 January 1862`,
		leftOffice: `4 February 1862`,
	},
	{
		countryId,
		name: `Victoriano Castellanos`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `4 February 1862`,
		leftOffice: `11 December 1862`,
	},
	{
		countryId,
		name: `José Francisco Montes`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `11 December 1862`,
		leftOffice: `7 September 1863`,
	},
	{
		countryId,
		name: `José María Medina`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 September 1863`,
		leftOffice: `31 December 1863`,
	},
	{
		countryId,
		name: `Francisco Inestroza`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `31 December 1863`,
		leftOffice: `15 March 1864`,
	},
	{
		countryId,
		name: `Francisco Cruz Castro`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `5 September 1869`,
		leftOffice: `14 January 1870`,
	},
	{
		countryId,
		name: `José María Medina`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `15 March 1864`,
		leftOffice: `26 July 1872`,
	},
	{
		countryId,
		name: `Céleo Arias`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `26 July 1872`,
		leftOffice: `13 January 1874`,
	},
	{
		countryId,
		name: `Ponciano Leiva`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `13 January 1874`,
		leftOffice: `8 June 1876`,
	},
	{
		countryId,
		name: `Marcelino Mejía`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `8 June 1876`,
		leftOffice: `13 June 1876`,
	},
	{
		countryId,
		name: `Crescencio Gómez`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `13 June 1876`,
		leftOffice: `12 August 1876`,
	},
	{
		countryId,
		name: `José María Medina`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `12 August 1876`,
		leftOffice: `27 August 1876`,
	},
	{
		countryId,
		name: `Marco Aurelio Soto`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `27 August 1876`,
		leftOffice: `19 October 1883`,
	},
	{
		countryId,
		name: `Council of Ministers`,
		party: `Council of Ministers`,
		leaning: leanings.CENTRIST,
		tookOffice: `19 October 1883`,
		leftOffice: `30 November 1883`,
	},
	{
		countryId,
		name: `Luis Bográn`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `30 November 1883`,
		leftOffice: `30 November 1891`,
	},
	{
		countryId,
		name: `Ponciano Leiva`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `30 November 1891`,
		leftOffice: `7 August 1893`,
	},
	{
		countryId,
		name: `Domingo Vásquez`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1893`,
		leftOffice: `22 February 1894`,
	},
	{
		countryId,
		name: `Policarpo Bonilla`,
		party: `Liberal Party of Honduras`,
		leaning: leanings.CENTRIST,
		tookOffice: `22 February 1894`,
		leftOffice: `1 February 1899`,
	},
	{
		countryId,
		name: `Terencio Sierra`,
		party: `Liberal Party of Honduras`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 February 1899`,
		leftOffice: `1 February 1903`,
	},
	{
		countryId,
		name: `Juan Ángel Arias Boquín`,
		party: `Liberal Party of Honduras`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 February 1903`,
		leftOffice: `13 April 1903`,
	},
	{
		countryId,
		name: `Manuel Bonilla`,
		party: `National Party of Honduras`,
		leaning: leanings.RIGHT,
		tookOffice: `13 April 1903`,
		leftOffice: `25 February 1907`,
	},
	{
		countryId,
		name: `Miguel Oquelí Bustillo`,
		party: `Liberal Party of Honduras`,
		leaning: leanings.CENTRIST,
		tookOffice: `25 February 1907`,
		leftOffice: `18 April 1907`,
	},
	{
		countryId,
		name: `Miguel R. Dávila`,
		party: `Liberal Party of Honduras`,
		leaning: leanings.CENTRIST,
		tookOffice: `18 April 1907`,
		leftOffice: `28 March 1911`,
	},
	{
		countryId,
		name: `Francisco Bertrand`,
		party: `National Party of Honduras`,
		leaning: leanings.RIGHT,
		tookOffice: `28 March 1911`,
		leftOffice: `1 February 1912`,
	},
	{
		countryId,
		name: `Manuel Bonilla`,
		party: `National Party of Honduras`,
		leaning: leanings.RIGHT,
		tookOffice: `1 February 1912`,
		leftOffice: `21 March 1913`,
	},
	{
		countryId,
		name: `Francisco Bertrand`,
		party: `National Party of Honduras`,
		leaning: leanings.RIGHT,
		tookOffice: `21 March 1913`,
		leftOffice: `9 September 1919`,
	},
	{
		countryId,
		name: `Salvador Aguirre`,
		party: `National Party of Honduras`,
		leaning: leanings.RIGHT,
		tookOffice: `9 September 1919`,
		leftOffice: `16 September 1919`,
	},
	{
		countryId,
		name: `Vicente Mejía Colindres`,
		party: `Liberal Party of Honduras`,
		leaning: leanings.CENTRIST,
		tookOffice: `16 September 1919`,
		leftOffice: `5 October 1919`,
	},
	{
		countryId,
		name: `Francisco Bográn`,
		party: `Liberal Party of Honduras`,
		leaning: leanings.CENTRIST,
		tookOffice: `5 October 1919`,
		leftOffice: `1 February 1920`,
	},
	{
		countryId,
		name: `Rafael López Gutiérrez`,
		party: `Liberal Party of Honduras`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 February 1920`,
		leftOffice: `10 March 1924`,
	},
	{
		countryId,
		name: `Francisco Bueso`,
		party: `Liberal Party of Honduras`,
		leaning: leanings.CENTRIST,
		tookOffice: `10 March 1924`,
		leftOffice: `27 April 1924`,
	},
	{
		countryId,
		name: `Tiburcio Carías Andino`,
		party: `National Party of Honduras`,
		leaning: leanings.RIGHT,
		tookOffice: `27 April 1924`,
		leftOffice: `30 April 1924`,
	},
	{
		countryId,
		name: `Vicente Tosta`,
		party: `Liberal Party of Honduras`,
		leaning: leanings.CENTRIST,
		tookOffice: `30 April 1924`,
		leftOffice: `1 February 1925`,
	},
	{
		countryId,
		name: `Miguel Paz Barahona`,
		party: `National Party of Honduras`,
		leaning: leanings.RIGHT,
		tookOffice: `1 February 1925`,
		leftOffice: `1 February 1929`,
	},
	{
		countryId,
		name: `Vicente Mejía Colindres`,
		party: `Liberal Party of Honduras`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 February 1929`,
		leftOffice: `1 February 1933`,
	},
	{
		countryId,
		name: `Tiburcio Carías Andino`,
		party: `National Party of Honduras`,
		leaning: leanings.RIGHT,
		tookOffice: `1 February 1933`,
		leftOffice: `1 January 1949`,
	},
	{
		countryId,
		name: `Juan Manuel Gálvez`,
		party: `National Party of Honduras`,
		leaning: leanings.RIGHT,
		tookOffice: `1 January 1949`,
		leftOffice: `5 December 1954`,
	},
	{
		countryId,
		name: `Julio Lozano Díaz`,
		party: `National Party of Honduras`,
		leaning: leanings.RIGHT,
		tookOffice: `5 December 1954`,
		leftOffice: `21 October 1956`,
	},
	{
		countryId,
		name: `Military Government Council`,
		party: `Armed Forces of Honduras`,
		leaning: leanings.RIGHT,
		tookOffice: `21 October 1956`,
		leftOffice: `21 December 1957`,
	},
	{
		countryId,
		name: `Ramon Villeda Morales`,
		party: `Liberal Party of Honduras`,
		leaning: leanings.CENTRIST,
		tookOffice: `21 December 1957`,
		leftOffice: `3 October 1963`,
	},
	{
		countryId,
		name: `Oswaldo López Arellano`,
		party: `National Party of Honduras`,
		leaning: leanings.RIGHT,
		tookOffice: `3 October 1963`,
		leftOffice: `7 June 1971`,
	},
	{
		countryId,
		name: `Ramón Ernesto Cruz Uclés`,
		party: `National Party of Honduras`,
		leaning: leanings.RIGHT,
		tookOffice: `7 June 1971`,
		leftOffice: `4 December 1972`,
	},
	{
		countryId,
		name: `Oswaldo López Arellano`,
		party: `National Party of Honduras`,
		leaning: leanings.RIGHT,
		tookOffice: `4 December 1972`,
		leftOffice: `22 April 1975`,
	},
	{
		countryId,
		name: `Juan Alberto Melgar`,
		party: `Armed Forces of Honduras`,
		leaning: leanings.RIGHT,
		tookOffice: `22 April 1975`,
		leftOffice: `7 August 1978`,
	},
	{
		countryId,
		name: `Policarpo Paz García`,
		party: `Armed Forces of Honduras`,
		leaning: leanings.RIGHT,
		tookOffice: `7 August 1978`,
		leftOffice: `27 January 1982`,
	},
	{
		countryId,
		name: `Roberto Suazo Córdoba`,
		party: `Liberal Party of Honduras`,
		leaning: leanings.CENTRIST,
		tookOffice: `27 January 1982`,
		leftOffice: `27 January 1986`,
	},
	{
		countryId,
		name: `José Azcona`,
		party: `Liberal Party of Honduras`,
		leaning: leanings.CENTRIST,
		tookOffice: `27 January 1986`,
		leftOffice: `27 January 1990`,
	},
	{
		countryId,
		name: `Rafael Callejas`,
		party: `National Party of Honduras`,
		leaning: leanings.RIGHT,
		tookOffice: `27 January 1990`,
		leftOffice: `27 January 1994`,
	},
	{
		countryId,
		name: `Carlos Roberto Reina`,
		party: `Liberal Party of Honduras`,
		leaning: leanings.CENTRIST,
		tookOffice: `27 January 1994`,
		leftOffice: `27 January 1998`,
	},
	{
		countryId,
		name: `Carlos Flores`,
		party: `Liberal Party of Honduras`,
		leaning: leanings.CENTRIST,
		tookOffice: `27 January 1998`,
		leftOffice: `27 January 2002`,
	},
	{
		countryId,
		name: `Ricardo Maduro`,
		party: `National Party of Honduras`,
		leaning: leanings.RIGHT,
		tookOffice: `27 January 2002`,
		leftOffice: `27 January 2006`,
	},
	{
		countryId,
		name: `Manuel Zelaya`,
		party: `Liberal Party of Honduras`,
		leaning: leanings.CENTRIST,
		tookOffice: `27 January 2006`,
		leftOffice: `28 June 2009`,
	},
	{
		countryId,
		name: `Roberto Micheletti`,
		party: `Liberal Party of Honduras`,
		leaning: leanings.CENTRIST,
		tookOffice: `28 June 2009`,
		leftOffice: `27 January 2010`,
	},
	{
		countryId,
		name: `Pepe Lobo`,
		party: `National Party of Honduras`,
		leaning: leanings.RIGHT,
		tookOffice: `27 January 2010`,
		leftOffice: `27 January 2014`,
	},
	{
		countryId,
		name: `Juan Orlando Hernández`,
		party: `National Party of Honduras`,
		leaning: leanings.RIGHT,
		tookOffice: `27 January 2014`,
		leftOffice: `27 January 2022`,
	},
	{
		countryId,
		name: `Xiomara Castro`,
		party: `Liberty and Refoundation`,
		leaning: leanings.LEFT,
		tookOffice: `27 January 2022`,
		leftOffice: `27 January 2026`,
	},
	{
		countryId,
		name: `Nasry Asfura`,
		party: `National Party of Honduras`,
		leaning: leanings.RIGHT,
		tookOffice: `27 January 2026`,
		leftOffice: null,
	}
];
