import type { LeaderNoId } from '../../app/data/types';
import { leanings } from '../../app/data/types';

export const source = `https://en.wikipedia.org/wiki/List_of_heads_of_state_of_Mexico`;

const countryId = 2;

export const mexico: LeaderNoId[] = [
	{
		countryId,
		name: `Viceroyalty of New Spain`,
		party: `Kingdom of Spain`,
		leaning: leanings.MONARCHY,
		tookOffice: `18 August 1521`,
		leftOffice: `28 September 1821`,
	},
	{
		countryId,
		name: `First Regency`,
		party: `First Mexican Empire`,
		leaning: leanings.MONARCHY,
		tookOffice: `28 September 1821`,
		leftOffice: `11 April 1822`,
	},
	{
		countryId,
		name: `Second Regency`,
		party: `Second Mexican Empire`,
		leaning: leanings.MONARCHY,
		tookOffice: `11 April 1822`,
		leftOffice: `18 May 1822`,
	},
	{
		countryId,
		name: `Agustín I`,
		party: `Royal House of Agustín de Iturbide I`,
		leaning: leanings.MONARCHY,
		tookOffice: `19 May 1822`,
		leftOffice: `1 April 1823`,
	},
	{
		countryId,
		name: `Provisional Government of Mexico`,
		party: `Provisional Government of Mexico`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 April 1823`,
		leftOffice: `10 October 1824`,
	},
	{
		countryId,
		name: `Guadalupe Victoria`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `10 October 1824`,
		leftOffice: `31 March 1829`,
	},
	{
		countryId,
		name: `Vicente Guerrero`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `1 April 1829`,
		leftOffice: `17 December 1829`,
	},
	{
		countryId,
		name: `José María Bocanegra`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `17 December 1829`,
		leftOffice: `23 December 1829`,
	},
	{
		countryId,
		name: `Vélez -Quintanar-Alaman`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `23 December 1829`,
		leftOffice: `31 December 1829`,
	},
	{
		countryId,
		name: `Anastasio Bustamante`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 January 1830`,
		leftOffice: `13 August 1832`,
	},
	{
		countryId,
		name: `Melchor Múzquiz`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `14 August 1832`,
		leftOffice: `24 December 1832`,
	},
	{
		countryId,
		name: `Manuel Gómez Pedraza`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `24 December 1832`,
		leftOffice: `31 March 1833`,
	},
	{
		countryId,
		name: `Valentín Gómez Farías`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `1 April 1833`,
		leftOffice: `16 May 1833`,
	},
	{
		countryId,
		name: `Antonio López de Santa Anna`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `16 May 1833`,
		leftOffice: `3 June 1833`,
	},
	{
		countryId,
		name: `Valentín Gómez Farías`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `3 June 1833`,
		leftOffice: `18 June 1833`,
	},
	{
		countryId,
		name: `Antonio López de Santa Anna`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `18 June 1833`,
		leftOffice: `5 July 1833`,
	},
	{
		countryId,
		name: `Valentín Gómez Farías`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `5 July 1833`,
		leftOffice: `27 October 1833`,
	},
	{
		countryId,
		name: `Antonio López de Santa Anna`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `27 October 1833`,
		leftOffice: `15 December 1833`,
	},
	{
		countryId,
		name: `Valentín Gómez Farías`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `16 December 1833`,
		leftOffice: `24 April 1834`,
	},
	{
		countryId,
		name: `Antonio López de Santa Anna`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `24 April 1834`,
		leftOffice: `27 January 1835`,
	},
	{
		countryId,
		name: `Miguel Barragán`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `27 January 1835`,
		leftOffice: `27 February 1836`,
	},
	{
		countryId,
		name: `José Justo Corro`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `27 February 1836`,
		leftOffice: `19 April 1837`,
	},
	{
		countryId,
		name: `Anastasio Bustamante`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `19 April 1837`,
		leftOffice: `18 March 1839`,
	},
	{
		countryId,
		name: `Antonio López de Santa Anna`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `18 March 1839`,
		leftOffice: `10 July 1839`,
	},
	{
		countryId,
		name: `Nicolás Bravo`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `11 July 1839`,
		leftOffice: `19 July 1839`,
	},
	{
		countryId,
		name: `Anastasio Bustamante`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `19 July 1839`,
		leftOffice: `22 September 1841`,
	},
	{
		countryId,
		name: `Francisco Javier Echeverría`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `22 September 1841`,
		leftOffice: `10 October 1841`,
	},
	{
		countryId,
		name: `Antonio López de Santa Anna`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `10 October 1841`,
		leftOffice: `26 October 1842`,
	},
	{
		countryId,
		name: `Nicolás Bravo`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `26 October 1842`,
		leftOffice: `4 March 1843`,
	},
	{
		countryId,
		name: `Antonio López de Santa Anna`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `4 March 1843`,
		leftOffice: `4 October 1843`,
	},
	{
		countryId,
		name: `Valentín Canalizo`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `4 October 1843`,
		leftOffice: `4 June 1844`,
	},
	{
		countryId,
		name: `Antonio López de Santa Anna`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `4 June 1844`,
		leftOffice: `12 September 1844`,
	},
	{
		countryId,
		name: `José Joaquín de Herrera`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `12 September 1844`,
		leftOffice: `21 September 1844`,
	},
	{
		countryId,
		name: `Valentín Canalizo`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `21 September 1844`,
		leftOffice: `6 December 1844`,
	},
	{
		countryId,
		name: `José Joaquín de Herrera`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `6 December 1844`,
		leftOffice: `30 December 1845`,
	},
	{
		countryId,
		name: `Mariano Paredes`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `31 December 1845`,
		leftOffice: `28 July 1846`,
	},
	{
		countryId,
		name: `Nicolás Bravo`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `28 July 1846`,
		leftOffice: `4 August 1846`,
	},
	{
		countryId,
		name: `José Mariano Salas`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `5 August 1846`,
		leftOffice: `23 December 1846`,
	},
	{
		countryId,
		name: `Valentín Gómez Farías`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `23 December 1846`,
		leftOffice: `21 March 1847`,
	},
	{
		countryId,
		name: `Antonio López de Santa Anna`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `21 March 1847`,
		leftOffice: `2 April 1847`,
	},
	{
		countryId,
		name: `Pedro María de Anaya`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `2 April 1847`,
		leftOffice: `20 May 1847`,
	},
	{
		countryId,
		name: `Antonio López de Santa Anna`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `20 May 1847`,
		leftOffice: `15 September 1847`,
	},
	{
		countryId,
		name: `Manuel de la Peña y Peña`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `16 September 1847`,
		leftOffice: `13 November 1847`,
	},
	{
		countryId,
		name: `Pedro María de Anaya`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `13 November 1847`,
		leftOffice: `8 January 1848`,
	},
	{
		countryId,
		name: `Manuel de la Peña y Peña`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `8 January 1848`,
		leftOffice: `3 June 1848`,
	},
	{
		countryId,
		name: `José Joaquín de Herrera`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `3 June 1848`,
		leftOffice: `15 January 1851`,
	},
	{
		countryId,
		name: `Mariano Arista`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `15 January 1851`,
		leftOffice: `5 January 1853`,
	},
	{
		countryId,
		name: `Juan Bautista Ceballos`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `6 January 1853`,
		leftOffice: `7 February 1853`,
	},
	{
		countryId,
		name: `Manuel María Lombardini`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `8 February 1853`,
		leftOffice: `20 April 1853`,
	},
	{
		countryId,
		name: `Antonio López de Santa Anna`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `20 April 1853`,
		leftOffice: `5 August 1855`,
	},
	{
		countryId,
		name: `Martín Carrera`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `5 August 1855`,
		leftOffice: `12 September 1855`,
	},
	{
		countryId,
		name: `Rómulo Díaz de la Vega`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `12 September 1855`,
		leftOffice: `3 October 1855`,
	},
	{
		countryId,
		name: `Juan Álvarez`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `4 October 1855`,
		leftOffice: `11 December 1855`,
	},
	{
		countryId,
		name: `Ignacio Comonfort`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `11 December 1855`,
		leftOffice: `17 December 1857`,
	},
	{
		countryId,
		name: `Ignacio Comonfort`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `17 December 1857`,
		leftOffice: `21 January 1858`,
	},
	{
		countryId,
		name: `Félix María Zuloaga`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `11 January 1858`,
		leftOffice: `24 December 1858`,
	},
	{
		countryId,
		name: `Manuel Robles Pezuela`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `24 December 1858`,
		leftOffice: `23 January 1859`,
	},
	{
		countryId,
		name: `Félix María Zuloaga`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `24 January 1859`,
		leftOffice: `1 February 1859`,
	},
	{
		countryId,
		name: `Miguel Miramón`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `2 February 1859`,
		leftOffice: `13 August 1860`,
	},
	{
		countryId,
		name: `José Ignacio Pavón`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `13 August 1860`,
		leftOffice: `15 August 1860`,
	},
	{
		countryId,
		name: `Miguel Miramón`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `15 August 1860`,
		leftOffice: `24 December 1860`,
	},
	{
		countryId,
		name: `Félix María Zuloaga`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `23 May 1861`,
		leftOffice: `28 December 1862`,
	},
	{
		countryId,
		name: `Juan Nepomuceno Almonte`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `11 July 1863`,
		leftOffice: `10 April 1864`,
	},
	{
		countryId,
		name: `José Mariano Salas`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `11 July 1863`,
		leftOffice: `10 April 1864`,
	},
	{
		countryId,
		name: `Pelagio Antonio de Labastida`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `19 October 1863`,
		leftOffice: `10 April 1864`,
	},
	{
		countryId,
		name: `Benito Juárez`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `18 December 1857`,
		leftOffice: `18 July 1872`,
	},
	{
		countryId,
		name: `Sebastián Lerdo de Tejada`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `18 July 1872`,
		leftOffice: `20 November 1876`,
	},
	{
		countryId,
		name: `José María Iglesias`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `26 October 1876`,
		leftOffice: `28 November 1876`,
	},
	{
		countryId,
		name: `Porfirio Díaz`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `28 November 1876`,
		leftOffice: `6 December 1876`,
	},
	{
		countryId,
		name: `Juan N. Méndez`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `6 December 1876`,
		leftOffice: `17 February 1877`,
	},
	{
		countryId,
		name: `Porfirio Díaz`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `17 February 1877`,
		leftOffice: `30 November 1880`,
	},
	{
		countryId,
		name: `Manuel González Flores`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `1 December 1880`,
		leftOffice: `30 November 1884`,
	},
	{
		countryId,
		name: `Porfirio Díaz`,
		party: `National Porfirist party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 1884`,
		leftOffice: `25 May 1911`,
	},
	{
		countryId,
		name: `Francisco León de la Barra`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `25 May 1911`,
		leftOffice: `5 November 1911`,
	},
	{
		countryId,
		name: `Francisco I. Madero`,
		party: `Progressive Constitutionalist Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `6 November 1911`,
		leftOffice: `19 February 1913`,
	},
	{
		countryId,
		name: `Pedro Lascuráin`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `19 February 1913`,
		leftOffice: `19 February 1913`,
	},
	{
		countryId,
		name: `Victoriano Huerta`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `19 February 1913`,
		leftOffice: `15 July 1914`,
	},
	{
		countryId,
		name: `Francisco S. Carvajal`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `15 July 1914`,
		leftOffice: `13 August 1914`,
	},
	{
		countryId,
		name: `Venustiano Carranza`,
		party: `Liberal Constitutionalist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `13 August 1914`,
		leftOffice: `21 May 1920`,
	},
	{
		countryId,
		name: `Adolfo de la Huerta`,
		party: `Liberal Constitutionalist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `21 May 1920`,
		leftOffice: `30 November 1920`,
	},
	{
		countryId,
		name: `Álvaro Obregón`,
		party: `Laborist Party`,
		leaning: leanings.LEFT,
		tookOffice: `1 December 1920`,
		leftOffice: `30 November 1924`,
	},
	{
		countryId,
		name: `Plutarco Elías Calles`,
		party: `Laborist Party`,
		leaning: leanings.LEFT,
		tookOffice: `1 December 1924`,
		leftOffice: `30 November 1928`,
	},
	{
		countryId,
		name: `Emilio Portes Gil`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 1928`,
		leftOffice: `4 February 1930`,
	},
	{
		countryId,
		name: `Pascual Ortiz Rubio`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `5 February 1930`,
		leftOffice: `4 September 1932`,
	},
	{
		countryId,
		name: `Abelardo L. Rodríguez`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `4 September 1932`,
		leftOffice: `30 November 1934`,
	},
	{
		countryId,
		name: `Lázaro Cárdenas`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.LEFT,
		tookOffice: `1 December 1934`,
		leftOffice: `30 November 1940`,
	},
	{
		countryId,
		name: `Manuel Ávila Camacho`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 1940`,
		leftOffice: `30 November 1946`,
	},
	{
		countryId,
		name: `Miguel Alemán Valdés`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 1946`,
		leftOffice: `30 November 1952`,
	},
	{
		countryId,
		name: `Adolfo Ruiz Cortines`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 1952`,
		leftOffice: `30 November 1958`,
	},
	{
		countryId,
		name: `Adolfo López Mateos`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 1958`,
		leftOffice: `30 November 1964`,
	},
	{
		countryId,
		name: `Gustavo Díaz Ordaz`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 1964`,
		leftOffice: `30 November 1970`,
	},
	{
		countryId,
		name: `Luis Echeverría Álvarez`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 1970`,
		leftOffice: `30 November 1976`,
	},
	{
		countryId,
		name: `Lopez Portillo`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 1976`,
		leftOffice: `30 November 1982`,
	},
	{
		countryId,
		name: `Miguel de la Madrid`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 1982`,
		leftOffice: `30 November 1988`,
	},
	{
		countryId,
		name: `Carlos Salinas de Gortari`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 1988`,
		leftOffice: `30 November 1994`,
	},
	{
		countryId,
		name: `Ernesto Zedillo Ponce de Leon`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 1994`,
		leftOffice: `30 November 2000`,
	},
	{
		countryId,
		name: `Vicente Fox`,
		party: `National Action Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 2000`,
		leftOffice: `30 November 2006`,
	},
	{
		countryId,
		name: `Felipe Calderon`,
		party: `National Action Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 2006`,
		leftOffice: `30 November 2012`,
	},
	{
		countryId,
		name: `Enrique Pena Nieto`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 2012`,
		leftOffice: `30 November 2018`,
	},
	{
		countryId,
		name: `Andrés Manuel López Obrador`,
		party: `National Regeneration Movement`,
		leaning: leanings.LEFT,
		tookOffice: `1 December 2018`,
		leftOffice: null,
	},
];
