import type { LeaderNoId } from '../../app/data/types';
import { leanings } from '../../app/data/types';

export const source = `https://en.wikipedia.org/wiki/List_of_heads_of_state_of_Mexico`;

const countryId = 2;

export const mexico: LeaderNoId[] = [
	{
		name: "Juan O'Donojú",
		party: null,
		leaning: null,
		tookOffice: '28 September 1821',
		leftOffice: '8 October 1821',
	},
	{
		name: 'Agustín de Iturbide',
		party: null,
		leaning: null,
		tookOffice: '28 September 1821',
		leftOffice: '11 April 1822',
	},
	{
		name: 'Manuel de la Barcéna',
		party: null,
		leaning: null,
		tookOffice: '28 September 1821',
		leftOffice: '11 April 1822',
	},
	{
		name: 'José Isidro Yañez',
		party: null,
		leaning: null,
		tookOffice: '28 September 1821',
		leftOffice: '11 April 1822',
	},
	{
		name: 'Manuel Velázquez de León',
		party: null,
		leaning: null,
		tookOffice: '28 September 1821',
		leftOffice: '11 April 1822',
	},
	{
		name: 'Antonio Pérez Martínez',
		party: null,
		leaning: null,
		tookOffice: '8 October 1821',
		leftOffice: '11 April 1822',
	},
	{
		name: 'Agustín de Iturbide',
		party: null,
		leaning: null,
		tookOffice: '11 April 1822',
		leftOffice: '18 May 1822',
	},
	{
		name: 'José Isidro Yañez',
		party: null,
		leaning: null,
		tookOffice: '11 April 1822',
		leftOffice: '18 May 1822',
	},
	{
		name: 'Miguel Valentín',
		party: null,
		leaning: null,
		tookOffice: '11 April 1822',
		leftOffice: '18 May 1822',
	},
	{
		name: 'Manuel de Heras',
		party: null,
		leaning: null,
		tookOffice: '11 April 1822',
		leftOffice: '18 May 1822',
	},
	{
		name: 'Nicolás Bravo',
		party: null,
		leaning: null,
		tookOffice: '11 April 1822',
		leftOffice: '18 May 1822',
	},
	{
		name: 'Agustín I',
		party: null,
		leaning: null,
		tookOffice: '19 May 1822',
		leftOffice: '19 March 1823',
	},
	{
		name: 'Nicolás Bravo',
		party: null,
		leaning: null,
		tookOffice: '31 March 1823',
		leftOffice: '10 October 1824',
	},
	{
		name: 'Guadalupe Victoria',
		party: null,
		leaning: null,
		tookOffice: '31 March 1823',
		leftOffice: '10 October 1824',
	},
	{
		name: 'Pedro Celestino Negrete',
		party: null,
		leaning: null,
		tookOffice: '31 March 1823',
		leftOffice: '10 October 1824',
	},
	{
		name: 'José Mariano Michelena',
		party: null,
		leaning: null,
		tookOffice: '1 April 1823',
		leftOffice: '10 October 1824',
	},
	{
		name: 'Miguel Domínguez',
		party: null,
		leaning: null,
		tookOffice: '1 April 1823',
		leftOffice: '10 October 1824',
	},
	{
		name: 'Vicente Guerrero',
		party: null,
		leaning: null,
		tookOffice: '1 April 1823',
		leftOffice: '10 October 1824',
	},
	{
		name: 'Guadalupe Victoria',
		party: 'Independent',
		leaning: null,
		tookOffice: '10 October 1824',
		leftOffice: '31 March 1829',
	},
	{
		name: 'Vicente Guerrero',
		party: 'Liberal party',
		leaning: 'Centre-left ',
		tookOffice: '1 April 1829',
		leftOffice: '17 December 1829',
	},
	{
		name: 'José María Bocanegra',
		party: 'York Rite',
		leaning: null,
		tookOffice: '17 December 1829',
		leftOffice: '23 December 1829',
	},
	{
		name: 'Vélez -Quintanar-Alaman',
		party: 'Liberal party',
		leaning: 'Centre-left ',
		tookOffice: '23 December 1829',
		leftOffice: '31 December 1829',
	},
	{
		name: 'Anastasio Bustamante',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: '1 January 1830',
		leftOffice: '13 August 1832',
	},
	{
		name: 'Melchor Múzquiz',
		party: 'York Rite',
		leaning: null,
		tookOffice: '14 August 1832',
		leftOffice: '24 December 1832',
	},
	{
		name: 'Manuel Gómez Pedraza',
		party: 'York Rite',
		leaning: null,
		tookOffice: '24 December 1832',
		leftOffice: '31 March 1833',
	},
	{
		name: 'Valentín Gómez Farías',
		party: 'Liberal party',
		leaning: 'Centre-left ',
		tookOffice: '1 April 1833',
		leftOffice: '16 May 1833',
	},
	{
		name: 'Antonio López de Santa Anna',
		party: 'Liberal party',
		leaning: 'Centre-left ',
		tookOffice: '16 May 1833',
		leftOffice: '3 June 1833',
	},
	{
		name: 'Valentín Gómez Farías',
		party: 'Liberal party',
		leaning: 'Centre-left ',
		tookOffice: '3 June 1833',
		leftOffice: '18 June 1833',
	},
	{
		name: 'Antonio López de Santa Anna',
		party: 'Liberal party',
		leaning: 'Centre-left ',
		tookOffice: '18 June 1833',
		leftOffice: '5 July 1833',
	},
	{
		name: 'Valentín Gómez Farías',
		party: 'Liberal party',
		leaning: 'Centre-left ',
		tookOffice: '5 July 1833',
		leftOffice: '27 October 1833',
	},
	{
		name: 'Antonio López de Santa Anna',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: '27 October 1833',
		leftOffice: '15 December 1833',
	},
	{
		name: 'Valentín Gómez Farías',
		party: 'Liberal party',
		leaning: 'Centre-left ',
		tookOffice: '16 December 1833',
		leftOffice: '24 April 1834',
	},
	{
		name: 'Antonio López de Santa Anna',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: '24 April 1834',
		leftOffice: '27 January 1835',
	},
	{
		name: 'Miguel Barragán',
		party: 'Liberal party',
		leaning: 'Centre-left ',
		tookOffice: '27 January 1835',
		leftOffice: '27 February 1836',
	},
	{
		name: 'José Justo Corro',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: '27 February 1836',
		leftOffice: '19 April 1837',
	},
	{
		name: 'Anastasio Bustamante',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: '19 April 1837',
		leftOffice: '18 March 1839',
	},
	{
		name: 'Antonio López de Santa Anna',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: '18 March 1839',
		leftOffice: '10 July 1839',
	},
	{
		name: 'Nicolás Bravo',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: '11 July 1839',
		leftOffice: '19 July 1839',
	},
	{
		name: 'Anastasio Bustamante',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: '19 July 1839',
		leftOffice: '22 September 1841',
	},
	{
		name: 'Francisco Javier Echeverría',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: '22 September 1841',
		leftOffice: '10 October 1841',
	},
	{
		name: 'Antonio López de Santa Anna',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: '10 October 1841',
		leftOffice: '26 October 1842',
	},
	{
		name: 'Nicolás Bravo',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: '26 October 1842',
		leftOffice: '4 March 1843',
	},
	{
		name: 'Antonio López de Santa Anna',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: '4 March 1843',
		leftOffice: '4 October 1843',
	},
	{
		name: 'Valentín Canalizo',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: '4 October 1843',
		leftOffice: '4 June 1844',
	},
	{
		name: 'Antonio López de Santa Anna',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: '4 June 1844',
		leftOffice: '12 September 1844',
	},
	{
		name: 'José Joaquín de Herrera',
		party: 'Liberal party',
		leaning: 'Centre-left ',
		tookOffice: '12 September 1844',
		leftOffice: '21 September 1844',
	},
	{
		name: 'Valentín Canalizo',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: '21 September 1844',
		leftOffice: '6 December 1844',
	},
	{
		name: 'José Joaquín de Herrera',
		party: 'Liberal party',
		leaning: 'Centre-left ',
		tookOffice: '6 December 1844',
		leftOffice: '30 December 1845',
	},
	{
		name: 'Mariano Paredes',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: '31 December 1845',
		leftOffice: '28 July 1846',
	},
	{
		name: 'Nicolás Bravo',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: '28 July 1846',
		leftOffice: '4 August 1846',
	},
	{
		name: 'José Mariano Salas',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: '5 August 1846',
		leftOffice: '23 December 1846',
	},
	{
		name: 'Valentín Gómez Farías',
		party: 'Liberal party',
		leaning: 'Centre-left ',
		tookOffice: '23 December 1846',
		leftOffice: '21 March 1847',
	},
	{
		name: 'Antonio López de Santa Anna',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: '21 March 1847',
		leftOffice: '2 April 1847',
	},
	{
		name: 'Pedro María de Anaya',
		party: 'Liberal party',
		leaning: 'Centre-left',
		tookOffice: '2 April 1847',
		leftOffice: '20 May 1847',
	},
	{
		name: 'Antonio López de Santa Anna',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: '20 May 1847',
		leftOffice: '15 September 1847',
	},
	{
		name: 'Manuel de la Peña y Peña',
		party: 'Liberal party',
		leaning: 'Centre-left',
		tookOffice: '16 September 1847',
		leftOffice: '13 November 1847',
	},
	{
		name: 'Pedro María de Anaya',
		party: 'Liberal party',
		leaning: 'Centre-left',
		tookOffice: '13 November 1847',
		leftOffice: '8 January 1848',
	},
	{
		name: 'Manuel de la Peña y Peña',
		party: 'Liberal party',
		leaning: 'Centre-left',
		tookOffice: '8 January 1848',
		leftOffice: '3 June 1848',
	},
	{
		name: 'José Joaquín de Herrera',
		party: 'Liberal party',
		leaning: 'Centre-left',
		tookOffice: '3 June 1848',
		leftOffice: '15 January 1851',
	},
	{
		name: 'Mariano Arista',
		party: 'Liberal party',
		leaning: 'Centre-left',
		tookOffice: '15 January 1851',
		leftOffice: '5 January 1853',
	},
	{
		name: 'Juan Bautista Ceballos',
		party: 'Liberal party',
		leaning: 'Centre-left',
		tookOffice: '6 January 1853',
		leftOffice: '7 February 1853',
	},
	{
		name: 'Manuel María Lombardini',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: '8 February 1853',
		leftOffice: '20 April 1853',
	},
	{
		name: 'Antonio López de Santa Anna',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: '20 April 1853',
		leftOffice: '5 August 1855',
	},
	{
		name: 'Martín Carrera',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: '5 August 1855',
		leftOffice: '12 September 1855',
	},
	{
		name: 'Rómulo Díaz de la Vega',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: '12 September 1855',
		leftOffice: '3 October 1855',
	},
	{
		name: 'Juan Álvarez',
		party: 'Liberal party',
		leaning: 'Centre-left',
		tookOffice: '4 October 1855',
		leftOffice: '11 December 1855',
	},
	{
		name: 'Ignacio Comonfort',
		party: 'Liberal party',
		leaning: 'Centre-left',
		tookOffice: '11 December 1855',
		leftOffice: '17 December 1857',
	},
	{
		name: 'Ignacio Comonfort',
		party: 'Liberal party',
		leaning: 'Centre-left',
		tookOffice: '17 December 1857',
		leftOffice: '21 January 1858',
	},
	{
		name: 'Félix María Zuloaga',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: '11 January 1858',
		leftOffice: '24 December 1858',
	},
	{
		name: 'Manuel Robles Pezuela',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: '24 December 1858',
		leftOffice: '23 January 1859',
	},
	{
		name: 'Félix María Zuloaga',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: '24 January 1859',
		leftOffice: '1 February 1859',
	},
	{
		name: 'Miguel Miramón',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: '2 February 1859',
		leftOffice: '13 August 1860',
	},
	{
		name: 'José Ignacio Pavón',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: '13 August 1860',
		leftOffice: '15 August 1860',
	},
	{
		name: 'Miguel Miramón',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: '15 August 1860',
		leftOffice: '24 December 1860',
	},
	{
		name: 'Félix María Zuloaga',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: '23 May 1861',
		leftOffice: '28 December 1862',
	},
	{
		name: 'Juan Nepomuceno Almonte',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: '11 July 1863',
		leftOffice: '10 April 1864',
	},
	{
		name: 'José Mariano Salas',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: '11 July 1863',
		leftOffice: '10 April 1864',
	},
	{
		name: 'Pelagio Antonio de Labastida',
		party: 'Conservative party',
		leaning: 'Right-wing',
		tookOffice: '19 October 1863',
		leftOffice: '10 April 1864',
	},
	{
		name: 'Benito Juárez',
		party: 'Liberal party',
		leaning: 'Centre-left',
		tookOffice: '18 December 1857',
		leftOffice: '18 July 1872',
	},
	{
		name: 'Sebastián Lerdo de Tejada',
		party: 'Liberal party',
		leaning: 'Centre-left',
		tookOffice: '18 July 1872',
		leftOffice: '20 November 1876',
	},
	{
		name: 'José María Iglesias',
		party: 'Liberal party',
		leaning: 'Centre-left',
		tookOffice: '26 October 1876',
		leftOffice: '28 November 1876',
	},
	{
		name: 'Porfirio Díaz',
		party: 'Liberal party',
		leaning: 'Centre-left',
		tookOffice: '28 November 1876',
		leftOffice: '6 December 1876',
	},
	{
		name: 'Juan N. Méndez',
		party: 'Liberal party',
		leaning: 'Centre-left',
		tookOffice: '6 December 1876',
		leftOffice: '17 February 1877',
	},
	{
		name: 'Porfirio Díaz',
		party: 'Liberal party',
		leaning: 'Centre-left',
		tookOffice: '17 February 1877',
		leftOffice: '30 November 1880',
	},
	{
		name: 'Manuel González Flores',
		party: 'Liberal party',
		leaning: 'Centre-left',
		tookOffice: '1 December 1880',
		leftOffice: '30 November 1884',
	},
	{
		name: 'Porfirio Díaz',
		party: 'National Porfirist party',
		leaning: 'Centre-left',
		tookOffice: '1 December 1884',
		leftOffice: '25 May 1911',
	},
	{
		name: 'Francisco León de la Barra',
		party: 'Independent',
		leaning: null,
		tookOffice: '25 May 1911',
		leftOffice: '5 November 1911',
	},
	{
		name: 'Progressive Constitutionalist party',
		party: 'Progressive Constitutionalist party',
		leaning: 'Centre',
		tookOffice: '6 November 1911',
		leftOffice: '19 February 1913',
	},
	{
		name: 'Pedro Lascuráin',
		party: 'Independent',
		leaning: null,
		tookOffice: '19 February 1913',
		leftOffice: '19 February 1913',
	},
	{
		name: 'Victoriano Huerta',
		party: 'Independent',
		leaning: null,
		tookOffice: '19 February 1913',
		leftOffice: '15 July 1914',
	},
	{
		name: 'Francisco S. Carvajal',
		party: 'Independent',
		leaning: null,
		tookOffice: '15 July 1914',
		leftOffice: '13 August 1914',
	},
	{
		name: 'Venustiano Carranza',
		party: 'Liberal Constitutionalist party',
		leaning: 'Centre-right',
		tookOffice: '13 August 1914',
		leftOffice: '30 April 1917',
	},
	{
		name: 'Venustiano Carranza',
		party: 'Liberal Constitutionalist party',
		leaning: 'Centre-right',
		tookOffice: '1 May 1917',
		leftOffice: '21 May 1920',
	},
	{
		name: 'Adolfo de la Huerta',
		party: 'Liberal Constitutionalist party',
		leaning: 'Centre-right',
		tookOffice: '1 June 1920',
		leftOffice: '30 November 1920',
	},
	{
		name: 'Álvaro Obregón',
		party: 'Laborist party',
		leaning: 'Centre-left to left-wing',
		tookOffice: '1 December 1920',
		leftOffice: '30 November 1924',
	},
	{
		name: 'Plutarco Elías Calles',
		party: 'Laborist party',
		leaning: 'Centre-left to left-wing',
		tookOffice: '1 December 1924',
		leftOffice: '30 November 1928',
	},
	{
		name: 'Emilio Portes Gil',
		party: 'National Revolutionary party',
		leaning: 'Centre',
		tookOffice: '1 December 1928',
		leftOffice: '4 February 1930',
	},
	{
		countryId,
		name: `Emilio Portes Gil`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 1928`,
		leftOffice: `4 February 1930`,
	},
	{
		countryId,
		name: `Pascual Ortiz Rubio`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `5 February 1930`,
		leftOffice: `4 September 1932`,
	},
	{
		countryId,
		name: `Abelardo L. Rodríguez`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `4 September 1932`,
		leftOffice: `30 November 1934`,
	},
	{
		countryId,
		name: `Lázaro Cárdenas`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 1934`,
		leftOffice: `30 November 1940`,
	},
	{
		countryId,
		name: `Manuel Ávila Camacho`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 1940`,
		leftOffice: `30 November 1946`,
	},
	{
		countryId,
		name: `Miguel Alemán Valdés`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 1946`,
		leftOffice: `30 November 1952`,
	},
	{
		countryId,
		name: `Adolfo Ruiz Cortines`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 1952`,
		leftOffice: `30 November 1958`,
	},
	{
		countryId,
		name: `Adolfo López Mateos`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 1958`,
		leftOffice: `30 November 1964`,
	},
	{
		countryId,
		name: `Gustavo Díaz Ordaz`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 1964`,
		leftOffice: `30 November 1970`,
	},
	{
		countryId,
		name: `Luis Echeverría Álvarez`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 1970`,
		leftOffice: `30 November 1976`,
	},
	{
		countryId,
		name: `Lopez Portillo`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 1976`,
		leftOffice: `30 November 1982`,
	},
	{
		countryId,
		name: `Miguel de la Madrid`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 1982`,
		leftOffice: `30 November 1988`,
	},
	{
		countryId,
		name: `Carlos Salinas de Gortari`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 1988`,
		leftOffice: `30 November 1994`,
	},
	{
		countryId,
		name: `Ernesto Zedillo Ponce de Leon`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 1994`,
		leftOffice: `30 November 2000`,
	},
	{
		countryId,
		name: `Vicente Fox`,
		party: `National Action Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 2000`,
		leftOffice: `30 November 2006`,
	},
	{
		countryId,
		name: `Felipe Calderon`,
		party: `National Action Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 2006`,
		leftOffice: `30 November 2012`,
	},
	{
		countryId,
		name: `Enrique Pena Nieto`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 2012`,
		leftOffice: `30 November 2018`,
	},
	{
		countryId,
		name: `Andrés Manuel López Obrador`,
		party: `National Regeneration Movement`,
		leaning: leanings.LEFT,
		tookOffice: `1 December 2018`,
		leftOffice: null,
	},
];
