import type { LeaderNoId } from '../../app/data/types';
import { leanings } from '../../app/data/types';

export const source = `https://www.mapsofworld.com/list-of/presidents-nicaragua/`;

const countryId = 7;

export const nicaragua: LeaderNoId[] = [
	{
		countryId,
		name: `Daniel Ortega`,
		party: `Sandinista National Liberation Front`,
		leaning: leanings.FAR_LEFT,
		tookOffice: `10 January 2007`,
		leftOffice: null,
	},
	{
		countryId,
		name: `Enrique Bolaños Geyer`,
		party: `Constitutionalist Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `10 January 2002`,
		leftOffice: `10 January 2007`,
	},
	{
		countryId,
		name: `José Arnoldo Alemán Lacayo`,
		party: `Constitutionalist Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `10 January 1997`,
		leftOffice: `10 January 2002`,
	},
	{
		countryId,
		name: `Violeta Chamorro`,
		party: `Democratic Union of Liberation`,
		leaning: leanings.CENTRIST,
		tookOffice: `25 April 1990`,
		leftOffice: `10 January 1997`,
	},
	{
		countryId,
		name: `Daniel Ortega`,
		party: `Sandinista National Liberation Front`,
		leaning: leanings.FAR_LEFT,
		tookOffice: `10 January 1985`,
		leftOffice: `25 April 1990`,
	},
	{
		countryId,
		name: `Junta of National Reconstruction`,
		party: `Sandinista National Liberation Front`,
		leaning: leanings.FAR_LEFT,
		tookOffice: `18 July 1979`,
		leftOffice: `10 January 1985`,
	},
	{
		countryId,
		name: `Francisco Urcuyo`,
		party: `Nationalist Liberal Party`,
		leaning: leanings.RIGHT,
		tookOffice: `17 July 1979`,
		leftOffice: `18 July 1979`,
	},
	{
		countryId,
		name: `Anastasio Somoza DeBayle`,
		party: `Military / Nationalist Liberal Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `1 December 1974`,
		leftOffice: `17 July 1979`,
	},
	{
		countryId,
		name: `Liberal-Conservative Junta`,
		party: `Nationalist Liberal Party / Social Conservative Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `1 May 1972`,
		leftOffice: `1 December 1974`,
	},
	{
		countryId,
		name: `Anastasio Somoza DeBayle`,
		party: `Military / Nationalist Liberal Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `1 May 1967`,
		leftOffice: `1 May 1972`,
	},
	{
		countryId,
		name: `Lorenzo Guerrero`,
		party: `Nationalist Liberal Party`,
		leaning: leanings.RIGHT,
		tookOffice: `4 August 1966`,
		leftOffice: `1 May 1967`,
	},
	{
		countryId,
		name: `René Schick`,
		party: `Nationalist Liberal Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 May 1963`,
		leftOffice: `3 August 1966`,
	},
	{
		countryId,
		name: `Luis Somoza Debayle`,
		party: `Nationalist Liberal Party`,
		leaning: leanings.RIGHT,
		tookOffice: `29 September 1956`,
		leftOffice: `1 May 1963`,
	},
	{
		countryId,
		name: `Anastasio Somoza García`,
		party: `Nationalist Liberal Party`,
		leaning: leanings.RIGHT,
		tookOffice: `21 May 1950`,
		leftOffice: `29 September 1956`,
	},
	{
		countryId,
		name: `Víctor Manuel Román y Reyes`,
		party: `Nationalist Liberal Party`,
		leaning: leanings.RIGHT,
		tookOffice: `15 August 1947`,
		leftOffice: `6 May 1950`,
	},
	{
		countryId,
		name: `Benjamín Lacayo Sacasa`,
		party: `Nationalist Liberal Party`,
		leaning: leanings.RIGHT,
		tookOffice: `26 May 1947`,
		leftOffice: `15 August 1947`,
	},
	{
		countryId,
		name: `Leonardo Argüello Barreto`,
		party: `Nationalist Liberal Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 May 1947`,
		leftOffice: `26 May 1947`,
	},
	{
		countryId,
		name: `Anastasio Somoza García`,
		party: `Military/Nationalist Liberal Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 January 1937`,
		leftOffice: `1 May 1947`,
	},
	{
		countryId,
		name: `Carlos Alberto Brenes`,
		party: `Nationalist Liberal Party`,
		leaning: leanings.RIGHT,
		tookOffice: `9 June 1936`,
		leftOffice: `1 January 1937`,
	},
	{
		countryId,
		name: `Juan Bautista Sacasa`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 January 1933`,
		leftOffice: `9 June 1936`,
	},
	{
		countryId,
		name: `Jose Maria Moncada Tapia`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 January 1929`,
		leftOffice: `1 January 1933`,
	},
	{
		countryId,
		name: `Adolfo Díaz`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `14 November 1926`,
		leftOffice: `1 January 1929`,
	},
	{
		countryId,
		name: `Emiliano Chamorro Vargas`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `14 March 1926`,
		leftOffice: `11 November 1926`,
	},
	{
		countryId,
		name: `Carlos José Solórzano`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 January 1925`,
		leftOffice: `14 March 1926`,
	},
	{
		countryId,
		name: `Bartolomé Martínez`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `27 October 1923`,
		leftOffice: `1 January 1925`,
	},
	{
		countryId,
		name: `Rosendo Chamorro`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `12 October 1923`,
		leftOffice: `27 October 1923`,
	},
	{
		countryId,
		name: `Diego Manuel Chamorro`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 January 1921`,
		leftOffice: `12 October 1923`,
	},
	{
		countryId,
		name: `Emiliano Chamorro Vargas`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 January 1917`,
		leftOffice: `1 January 1921`,
	},
	{
		countryId,
		name: `Adolfo Díaz`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `9 May 1911`,
		leftOffice: `1 January 1917`,
	},
	{
		countryId,
		name: `Juan José Estrada`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `30 August 1910`,
		leftOffice: `9 May 1911`,
	},
	{
		countryId,
		name: `Luis Mena`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `27 August 1910`,
		leftOffice: `30 August 1910`,
	},
	{
		countryId,
		name: `José Dolores Estrada`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `20 August 1910`,
		leftOffice: `27 August 1910`,
	},
	{
		countryId,
		name: `José Madriz`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `21 December 1909`,
		leftOffice: `20 August 1910`,
	},
	{
		countryId,
		name: `José Santos Zelaya`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `25 July 1893`,
		leftOffice: `21 December 1909`,
	},
	{
		countryId,
		name: `Roberto Sacasa`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 March 1891`,
		leftOffice: `11 July 1893`,
	},
	{
		countryId,
		name: `Ignacio Chávez`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 January 1891`,
		leftOffice: `1 March 1891`,
	},
	{
		countryId,
		name: `Roberto Sacasa`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `5 August 1889`,
		leftOffice: `1 January 1891`,
	},
	{
		countryId,
		name: `Evaristo Carazo`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 March 1887`,
		leftOffice: `1 August 1889`,
	},
	{
		countryId,
		name: `Adán Cárdenas`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 March 1883`,
		leftOffice: `1 March 1887`,
	},
	{
		countryId,
		name: `Joaquín Zavala`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 March 1879`,
		leftOffice: `1 March 1883`,
	},
];
