import type { LeaderNoId } from '../../app/data/types';
import { leanings } from '../../app/data/types';

export const source = `https://en.wikipedia.org/wiki/President_of_Nicaragua`;

const countryId = 7;

export const nicaragua: LeaderNoId[] = [
	{
		countryId,
		name: 'Viceroyalty of New Spain',
		party: 'Spanish Empire',
		leaning: leanings.MONARCHY,
		tookOffice: '18 August 1521',
		leftOffice: '22 April 1825',
	},
	{
		countryId,
		name: 'Manuel Antonio de la Cerda',
		party: 'Conservative Federalist',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '22 April 1825',
		leftOffice: '22 April 1826',
	},
	{
		countryId,
		name: 'Juan Argüello',
		party: 'Liberal Federalist',
		leaning: leanings.CENTER_LEFT,
		tookOffice: '22 April 1826',
		leftOffice: '14 September 1827',
	},
	{
		countryId,
		name: 'Pedro Benito Pineda',
		party: 'Conservative Federalist',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '17 September 1826',
		leftOffice: '26 February 1827',
	},
	{
		countryId,
		name: 'Manuel Antonio de la Cerda',
		party: 'Conservative Federalist',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '27 February 1827',
		leftOffice: '7 November 1828',
	},
	{
		countryId,
		name: 'Pedro Oviedo',
		party: 'Liberal Federalist',
		leaning: leanings.CENTER_LEFT,
		tookOffice: '14 September 1827',
		leftOffice: 'December 1827',
	},
	{
		countryId,
		name: 'Liberal Juntas',
		party: 'Liberal Federalist',
		leaning: leanings.CENTER_LEFT,
		tookOffice: 'December 1827',
		leftOffice: 'August 1828',
	},
	{
		countryId,
		name: 'Juan Argüello',
		party: 'Liberal Federalist',
		leaning: leanings.CENTER_LEFT,
		tookOffice: '5 August 1828',
		leftOffice: 'November 1829',
	},
	{
		countryId,
		name: 'Juan Espinosa',
		party: 'Liberal Federalist',
		leaning: leanings.CENTER_LEFT,
		tookOffice: '8 November 1829',
		leftOffice: '10 May 1830',
	},
	{
		countryId,
		name: 'Dionisio de Herrera',
		party: 'Liberal Federalist',
		leaning: leanings.CENTER_LEFT,
		tookOffice: '10 May 1830',
		leftOffice: 'December, 1833',
	},
	{
		countryId,
		name: 'Benito Morales',
		party: 'Legitimist Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: 'December, 1833',
		leftOffice: '10 March 1834',
	},
	{
		countryId,
		name: 'José Núñez',
		party: 'Legitimist Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '10 March 1834',
		leftOffice: '23 April 1835',
	},
	{
		countryId,
		name: 'José Zepeda',
		party: 'Liberal Federalist',
		leaning: leanings.CENTER_LEFT,
		tookOffice: '23 April 1835',
		leftOffice: '25 January 1837',
	},
	{
		countryId,
		name: 'José Núñez',
		party: 'Legitimist Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '25 January 1837',
		leftOffice: '12 January 1838',
	},
	{
		countryId,
		name: 'Francisco Jiménez Rubio',
		party: 'Legitimist Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '12 January 1838',
		leftOffice: '13 March 1838',
	},
	{
		countryId,
		name: 'José Núñez',
		party: 'Legitimist Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '13 March 1838',
		leftOffice: '30 April 1838',
	},
	{
		countryId,
		name: 'José Núñez',
		party: 'Legitimist Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '30 April 1838',
		leftOffice: '5 January 1839',
	},
	{
		countryId,
		name: 'Joaquín del Cossío',
		party: 'Legitimist Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '1839',
		leftOffice: '15 May 1839',
	},
	{
		countryId,
		name: 'Evaristo Rocha',
		party: 'Legitimist Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '5 January 1839',
		leftOffice: '30 June 1839',
	},
	{
		countryId,
		name: 'Patricio Rivas',
		party: 'Democratic Party',
		leaning: leanings.CENTER_LEFT,
		tookOffice: '30 June 1839',
		leftOffice: '27 July 1839',
	},
	{
		countryId,
		name: 'Joaquín del Cossío',
		party: 'Legitimist Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '27 July 1839',
		leftOffice: '20 October 1839',
	},
	{
		countryId,
		name: 'Hilario Ulloa',
		party: 'Legitimist Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '20 October 1839',
		leftOffice: '7 November 1839',
	},
	{
		countryId,
		name: 'Tomás Valladares',
		party: 'Democratic Party',
		leaning: leanings.CENTER_LEFT,
		tookOffice: '7 November 1839',
		leftOffice: '21 September 1840',
	},
	{
		countryId,
		name: 'Patricio Rivas',
		party: 'Democratic Party',
		leaning: leanings.CENTER_LEFT,
		tookOffice: '21 September 1840',
		leftOffice: '4 March 1841',
	},
	{
		countryId,
		name: 'Pablo Buitrago',
		party: 'Legitimist Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '4 March 1841',
		leftOffice: '1 April 1843',
	},
	{
		countryId,
		name: 'Juan de Dios Orozco',
		party: 'Legitimist Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '1 April 1843',
		leftOffice: '31 May 1843',
	},
	{
		countryId,
		name: 'Manuel Pérez',
		party: 'Democratic Party',
		leaning: leanings.CENTER_LEFT,
		tookOffice: '31 May 1843',
		leftOffice: '4 November 1844',
	},
	{
		countryId,
		name: 'Emiliano Madriz',
		party: 'Democratic Party',
		leaning: leanings.CENTER_LEFT,
		tookOffice: '4 November 1844',
		leftOffice: '24 January 1845',
	},
	{
		countryId,
		name: 'Silvestre Selva',
		party: 'Legitimist Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '16 December 1844',
		leftOffice: '20 January 1845',
	},
	{
		countryId,
		name: 'Blas Antonio Sáenz',
		party: 'Legitimist Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '20 January 1845',
		leftOffice: '4 April 1845',
	},
	{
		countryId,
		name: 'José León Sandoval',
		party: 'Republican Party',
		leaning: leanings.CENTER_LEFT,
		tookOffice: '4 April 1845',
		leftOffice: '12 March 1847',
	},
	{
		countryId,
		name: 'Miguel Ramón Morales',
		party: 'Legitimist Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '12 March 1847',
		leftOffice: '6 April 1847',
	},
	{
		countryId,
		name: 'José María Guerrero',
		party: 'Republican Party',
		leaning: leanings.CENTER_LEFT,
		tookOffice: '6 April 1847',
		leftOffice: '1 January 1849',
	},
	{
		countryId,
		name: 'Toribio Terán',
		party: 'Legitimist Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '1 January 1849',
		leftOffice: '8 March 1849',
	},
	{
		countryId,
		name: 'Benito Rosales',
		party: 'Legitimist Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '8 March 1849',
		leftOffice: '1 April 1849',
	},
	{
		countryId,
		name: 'Norberto Ramírez',
		party: 'Legitimist Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '1 April 1849',
		leftOffice: '1 April 1851',
	},
	{
		countryId,
		name: 'Justo Abaunza',
		party: 'Legitimist Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '1 April 1851',
		leftOffice: '5 May 1851',
	},
	{
		countryId,
		name: 'Laureano Pineda',
		party: 'Democratic Party',
		leaning: leanings.CENTER_LEFT,
		tookOffice: '5 May 1851',
		leftOffice: '4 August 1851',
	},
	{
		countryId,
		name: 'Justo Abaunza',
		party: 'Legitimist Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '4 August 1851',
		leftOffice: '11 November 1851',
	},
	{
		countryId,
		name: 'Laureano Pineda',
		party: 'Democratic Party',
		leaning: leanings.CENTER_LEFT,
		tookOffice: '5 August 1851',
		leftOffice: '11 August 1851',
	},
	{
		countryId,
		name: 'José Francisco del Montenegro',
		party: 'Legitimist Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '5 August 1851',
		leftOffice: '11 August 1851',
	},
	{
		countryId,
		name: 'José de Jesús Alfaro',
		party: 'Democratic Party',
		leaning: leanings.CENTER_LEFT,
		tookOffice: '11 August 1851',
		leftOffice: '2 November 1851',
	},
	{
		countryId,
		name: 'Fulgencio Vega',
		party: 'Legitimist Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '11 November 1851',
		leftOffice: '11 November 1852',
	},
	{
		countryId,
		name: 'Laureano Pineda',
		party: 'Democratic Party',
		leaning: leanings.CENTER_LEFT,
		tookOffice: '11 November 1851',
		leftOffice: '1 April 1853',
	},
	{
		countryId,
		name: 'Fruto Chamorro',
		party: 'Legitimist Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '1 April 1853',
		leftOffice: '30 April 1854',
	},
	{
		countryId,
		name: 'Francisco Castellón',
		party: 'Democratic Party',
		leaning: leanings.CENTER_LEFT,
		tookOffice: '11 June 1854',
		leftOffice: '2 September 1855',
	},
	{
		countryId,
		name: 'Nazario Escoto',
		party: 'Democratic Party',
		leaning: leanings.CENTER_LEFT,
		tookOffice: '2 September 1855',
		leftOffice: '30 October 1855',
	},
	{
		countryId,
		name: 'Fruto Chamorro',
		party: 'Conservative Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '30 April 1854',
		leftOffice: '12 March 1855',
	},
	{
		countryId,
		name: 'José María Estrada',
		party: 'Conservative Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '12 March 1855',
		leftOffice: '22 October 1855',
	},
	{
		countryId,
		name: 'Patricio Rivas',
		party: 'Democratic Party',
		leaning: leanings.CENTER_LEFT,
		tookOffice: '30 October 1855',
		leftOffice: '24 June 1857',
	},
	{
		countryId,
		name: 'William Walker',
		party: 'Democratic Party',
		leaning: leanings.CENTER_LEFT,
		tookOffice: '12 July 1856',
		leftOffice: '1 May 1857',
	},
	{
		countryId,
		name: 'Máximo Jerez and Tomás Martínez',
		party: 'Non Partisan',
		leaning: leanings.CENTRIST,
		tookOffice: '24 June 1857',
		leftOffice: '15 November 1857',
	},
	{
		countryId,
		name: 'Tomás Martínez',
		party: 'Conservative Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '15 November 1857',
		leftOffice: '1 March 1867',
	},
	{
		countryId,
		name: 'Fernando Guzmán Solórzano',
		party: 'Conservative Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '1 March 1867',
		leftOffice: '1 March 1871',
	},
	{
		countryId,
		name: 'José Vicente Cuadra',
		party: 'Conservative Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '1 March 1871',
		leftOffice: '1 March 1875',
	},
	{
		countryId,
		name: 'Pedro Joaquín Chamorro Alfaro',
		party: 'Conservative Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '1 March 1875',
		leftOffice: '1 March 1879',
	},
	{
		countryId,
		name: 'Joaquín Zavala',
		party: 'Conservative Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '1 March 1879',
		leftOffice: '1 March 1883',
	},
	{
		countryId,
		name: 'Adán Cárdenas',
		party: 'Conservative Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '1 March 1883',
		leftOffice: '1 March 1887',
	},
	{
		countryId,
		name: `Joaquín Zavala`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 March 1879`,
		leftOffice: `1 March 1883`,
	},
	{
		countryId,
		name: `Adán Cárdenas`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 March 1883`,
		leftOffice: `1 March 1887`,
	},
	{
		countryId,
		name: `Evaristo Carazo`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 March 1887`,
		leftOffice: `1 August 1889`,
	},
	{
		countryId,
		name: `Roberto Sacasa`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `5 August 1889`,
		leftOffice: `1 January 1891`,
	},
	{
		countryId,
		name: `Ignacio Chávez`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 January 1891`,
		leftOffice: `1 March 1891`,
	},
	{
		countryId,
		name: `Roberto Sacasa`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 March 1891`,
		leftOffice: `11 July 1893`,
	},
	{
		countryId,
		name: `José Santos Zelaya`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `25 July 1893`,
		leftOffice: `21 December 1909`,
	},
	{
		countryId,
		name: `José Madriz`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `21 December 1909`,
		leftOffice: `20 August 1910`,
	},
	{
		countryId,
		name: `José Dolores Estrada`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `20 August 1910`,
		leftOffice: `27 August 1910`,
	},
	{
		countryId,
		name: `Luis Mena`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `27 August 1910`,
		leftOffice: `30 August 1910`,
	},
	{
		countryId,
		name: `Juan José Estrada`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `30 August 1910`,
		leftOffice: `9 May 1911`,
	},
	{
		countryId,
		name: `Adolfo Díaz`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `9 May 1911`,
		leftOffice: `1 January 1917`,
	},
	{
		countryId,
		name: `Emiliano Chamorro Vargas`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 January 1917`,
		leftOffice: `1 January 1921`,
	},
	{
		countryId,
		name: `Diego Manuel Chamorro`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 January 1921`,
		leftOffice: `12 October 1923`,
	},
	{
		countryId,
		name: `Rosendo Chamorro`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `12 October 1923`,
		leftOffice: `27 October 1923`,
	},
	{
		countryId,
		name: `Bartolomé Martínez`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `27 October 1923`,
		leftOffice: `1 January 1925`,
	},
	{
		countryId,
		name: `Carlos José Solórzano`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 January 1925`,
		leftOffice: `14 March 1926`,
	},
	{
		countryId,
		name: `Emiliano Chamorro Vargas`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `14 March 1926`,
		leftOffice: `11 November 1926`,
	},
	{
		countryId,
		name: `Adolfo Díaz`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `14 November 1926`,
		leftOffice: `1 January 1929`,
	},
	{
		countryId,
		name: `Jose Maria Moncada Tapia`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 January 1929`,
		leftOffice: `1 January 1933`,
	},
	{
		countryId,
		name: `Juan Bautista Sacasa`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 January 1933`,
		leftOffice: `9 June 1936`,
	},
	{
		countryId,
		name: `Carlos Alberto Brenes`,
		party: `Nationalist Liberal Party`,
		leaning: leanings.RIGHT,
		tookOffice: `9 June 1936`,
		leftOffice: `1 January 1937`,
	},
	{
		countryId,
		name: `Anastasio Somoza García`,
		party: `Military/Nationalist Liberal Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 January 1937`,
		leftOffice: `1 May 1947`,
	},
	{
		countryId,
		name: `Leonardo Argüello Barreto`,
		party: `Nationalist Liberal Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 May 1947`,
		leftOffice: `26 May 1947`,
	},
	{
		countryId,
		name: `Benjamín Lacayo Sacasa`,
		party: `Nationalist Liberal Party`,
		leaning: leanings.RIGHT,
		tookOffice: `26 May 1947`,
		leftOffice: `15 August 1947`,
	},
	{
		countryId,
		name: `Víctor Manuel Román y Reyes`,
		party: `Nationalist Liberal Party`,
		leaning: leanings.RIGHT,
		tookOffice: `15 August 1947`,
		leftOffice: `6 May 1950`,
	},
	{
		countryId,
		name: `Anastasio Somoza García`,
		party: `Nationalist Liberal Party`,
		leaning: leanings.RIGHT,
		tookOffice: `21 May 1950`,
		leftOffice: `29 September 1956`,
	},
	{
		countryId,
		name: `Luis Somoza Debayle`,
		party: `Nationalist Liberal Party`,
		leaning: leanings.RIGHT,
		tookOffice: `29 September 1956`,
		leftOffice: `1 May 1963`,
	},
	{
		countryId,
		name: `René Schick`,
		party: `Nationalist Liberal Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 May 1963`,
		leftOffice: `3 August 1966`,
	},
	{
		countryId,
		name: `Lorenzo Guerrero`,
		party: `Nationalist Liberal Party`,
		leaning: leanings.RIGHT,
		tookOffice: `4 August 1966`,
		leftOffice: `1 May 1967`,
	},
	{
		countryId,
		name: `Anastasio Somoza DeBayle`,
		party: `Military / Nationalist Liberal Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `1 May 1967`,
		leftOffice: `1 May 1972`,
	},
	{
		countryId,
		name: `Liberal-Conservative Junta`,
		party: `Nationalist Liberal Party / Social Conservative Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `1 May 1972`,
		leftOffice: `1 December 1974`,
	},
	{
		countryId,
		name: `Anastasio Somoza DeBayle`,
		party: `Military / Nationalist Liberal Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `1 December 1974`,
		leftOffice: `17 July 1979`,
	},
	{
		countryId,
		name: `Francisco Urcuyo`,
		party: `Nationalist Liberal Party`,
		leaning: leanings.RIGHT,
		tookOffice: `17 July 1979`,
		leftOffice: `18 July 1979`,
	},
	{
		countryId,
		name: `Junta of National Reconstruction`,
		party: `Sandinista National Liberation Front`,
		leaning: leanings.FAR_LEFT,
		tookOffice: `18 July 1979`,
		leftOffice: `10 January 1985`,
	},
	{
		countryId,
		name: `Daniel Ortega`,
		party: `Sandinista National Liberation Front`,
		leaning: leanings.FAR_LEFT,
		tookOffice: `10 January 1985`,
		leftOffice: `25 April 1990`,
	},
	{
		countryId,
		name: `Violeta Chamorro`,
		party: `Democratic Union of Liberation`,
		leaning: leanings.CENTRIST,
		tookOffice: `25 April 1990`,
		leftOffice: `10 January 1997`,
	},
	{
		countryId,
		name: `José Arnoldo Alemán Lacayo`,
		party: `Constitutionalist Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `10 January 1997`,
		leftOffice: `10 January 2002`,
	},
	{
		countryId,
		name: `Enrique Bolaños Geyer`,
		party: `Constitutionalist Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `10 January 2002`,
		leftOffice: `10 January 2007`,
	},
	{
		countryId,
		name: `Daniel Ortega`,
		party: `Sandinista National Liberation Front`,
		leaning: leanings.FAR_LEFT,
		tookOffice: `10 January 2007`,
		leftOffice: null,
	},
];
