import type { LeaderNoId } from '../../app/data/types';
import { leanings } from '../../app/data/types';

export const source = `https://en.wikipedia.org/wiki/List_of_heads_of_state_of_Panama`;

const countryId = 9;

export const panama: LeaderNoId[] = [
	{
		countryId,
		name: 'Viceroyalty of New Granada',
		party: 'Spanish Empire',
		leaning: leanings.MONARCHY,
		tookOffice: '27 May 1717',
		leftOffice: '28 November 1821',
	},
	{
		countryId,
		name: 'Simón Bolívar',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '28 November 1821',
		leftOffice: '20 October 1831',
	},
	{
		countryId,
		name: 'Republic of New Granada',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '20 October 1831',
		leftOffice: '11 April 1858',
	},
	{
		countryId,
		name: 'Granadine Confederation',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '11 April 1858',
		leftOffice: '8 May 1863',
	},
	{
		countryId,
		name: 'United States of Colombia',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '8 May 1863',
		leftOffice: '3 February 1886',
	},
	{
		countryId,
		name: 'Republic of Colombia',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '3 February 1886',
		leftOffice: '3 November 1903',
	},
	{
		countryId,
		name: 'Republic of Panama',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '3 November 1903',
		leftOffice: '20 February 1904',
	},
	{
		countryId,
		name: 'Manuel Amador Guerrero',
		party: 'Conservative Party',
		leaning: leanings.RIGHT,
		tookOffice: '20 February 1904',
		leftOffice: '23 June 1907',
	},
	{
		countryId,
		name: 'José Domingo de Obaldía',
		party: 'National Liberal party',
		leaning: leanings.CENTRIST,
		tookOffice: '24 June 1907',
		leftOffice: '27 December 1907',
	},
	{
		countryId,
		name: 'Manuel Amador Guerrero',
		party: 'Conservative Party',
		leaning: leanings.RIGHT,
		tookOffice: '29 December 1907',
		leftOffice: '1 October 1908',
	},
	{
		countryId,
		name: 'José Domingo de Obaldía',
		party: 'National Liberal party',
		leaning: leanings.CENTRIST,
		tookOffice: '1 October 1908',
		leftOffice: '1 March 1910',
	},
	{
		countryId,
		name: 'Carlos Antonio Mendoza',
		party: 'National Liberal party',
		leaning: leanings.CENTRIST,
		tookOffice: '1 March 1910',
		leftOffice: '1 October 1910',
	},
	{
		countryId,
		name: 'Federico Boyd',
		party: 'National Liberal party',
		leaning: leanings.CENTRIST,
		tookOffice: '1 October 1910',
		leftOffice: '5 October 1910',
	},
	{
		countryId,
		name: 'Pablo Arosemena',
		party: 'National Liberal party',
		leaning: leanings.CENTRIST,
		tookOffice: '5 October 1910',
		leftOffice: '1 October 1912',
	},
	{
		countryId,
		name: 'Belisario Porras Barahona',
		party: 'National Liberal party',
		leaning: leanings.CENTRIST,
		tookOffice: '1 October 1912',
		leftOffice: '1 October 1916',
	},
	{
		countryId,
		name: 'Ramón Maximiliano Valdés',
		party: 'National Liberal party',
		leaning: leanings.CENTRIST,
		tookOffice: '1 October 1916',
		leftOffice: '3 June 1918',
	},
	{
		countryId,
		name: 'Ciro Luis Urriola',
		party: 'National Liberal party',
		leaning: leanings.CENTRIST,
		tookOffice: '3 June 1918',
		leftOffice: '1 October 1918',
	},
	{
		countryId,
		name: 'Pedro Antonio Díaz',
		party: 'Conservative Party',
		leaning: leanings.RIGHT,
		tookOffice: '1 October 1918',
		leftOffice: '12 October 1918',
	},
	{
		countryId,
		name: 'Belisario Porras Barahona',
		party: 'National Liberal party',
		leaning: leanings.CENTRIST,
		tookOffice: '12 October 1918',
		leftOffice: '30 January 1920',
	},
	{
		countryId,
		name: 'Ernesto Tisdel Lefevre',
		party: 'National Liberal party',
		leaning: leanings.CENTRIST,
		tookOffice: '30 January 1920',
		leftOffice: '1 October 1920',
	},
	{
		countryId,
		name: 'Belisario Porras Barahona',
		party: 'National Liberal party',
		leaning: leanings.CENTRIST,
		tookOffice: '1 October 1920',
		leftOffice: '1 October 1924',
	},
	{
		countryId,
		name: 'Rodolfo Chiari',
		party: 'National Liberal party',
		leaning: leanings.CENTRIST,
		tookOffice: '1 October 1924',
		leftOffice: '1 October 1928',
	},
	{
		countryId,
		name: `Ernesto Tisdel Lefevre`,
		party: `National Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `30 January 1920`,
		leftOffice: `1 October 1920`,
	},
	{
		countryId,
		name: `Belisario Porras Barahona`,
		party: `National Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 October 1920`,
		leftOffice: `1 October 1924`,
	},
	{
		countryId,
		name: `Rodolfo Chiari`,
		party: `National Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 October 1924`,
		leftOffice: `1 October 1928`,
	},
	{
		countryId,
		name: `Florencio Harmodio Arosemena`,
		party: `National Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 October 1928`,
		leftOffice: `3 January 1931`,
	},
	{
		countryId,
		name: `Harmodio Arias Madrid`,
		party: `National Revolutionary Party`,
		leaning: leanings.RIGHT,
		tookOffice: `3 January 1931`,
		leftOffice: `16 January 1931`,
	},
	{
		countryId,
		name: `Ricardo Joaquín Alfaro Jované`,
		party: `National Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `16 January 1931`,
		leftOffice: `5 June 1932`,
	},
	{
		countryId,
		name: `Harmodio Arias Madrid`,
		party: `National Revolutionary Party`,
		leaning: leanings.RIGHT,
		tookOffice: `5 June 1932`,
		leftOffice: `1 October 1936`,
	},
	{
		countryId,
		name: `Juan Demóstenes Arosemena`,
		party: `National Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 October 1936`,
		leftOffice: `16 December 1939`,
	},
	{
		countryId,
		name: `Ezequiel Fernández`,
		party: `National Revolutionary Party`,
		leaning: leanings.RIGHT,
		tookOffice: `16 December 1939`,
		leftOffice: `18 December 1939`,
	},
	{
		countryId,
		name: `Augusto Samuel Boyd`,
		party: `National Revolutionary Party`,
		leaning: leanings.RIGHT,
		tookOffice: `18 December 1939`,
		leftOffice: `1 October 1940`,
	},
	{
		countryId,
		name: `Arnulfo Arias`,
		party: `Panameñista Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 October 1940`,
		leftOffice: `9 October 1941`,
	},
	{
		countryId,
		name: `Ricardo Adolfo de la Guardia Arango`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `9 October 1941`,
		leftOffice: `15 June 1945`,
	},
	{
		countryId,
		name: `Enrique Adolfo Jiménez`,
		party: `National Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `15 June 1945`,
		leftOffice: `7 August 1948`,
	},
	{
		countryId,
		name: `Domingo Díaz Arosemena`,
		party: `National Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 1948`,
		leftOffice: `28 July 1949`,
	},
	{
		countryId,
		name: `Daniel Chanis Pinzón`,
		party: `National Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `28 July 1949`,
		leftOffice: `20 November 1949`,
	},
	{
		countryId,
		name: `Roberto Francisco Chiari Remón`,
		party: `National Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `20 November 1949`,
		leftOffice: `24 November 1949`,
	},
	{
		countryId,
		name: `Arnulfo Arias`,
		party: `Panameñista Party`,
		leaning: leanings.RIGHT,
		tookOffice: `24 November 1949`,
		leftOffice: `9 May 1951`,
	},
	{
		countryId,
		name: `Alcibíades Arosemena`,
		party: `Authentic Revolutionary Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `9 May 1951`,
		leftOffice: `1 October 1952`,
	},
	{
		countryId,
		name: `José Antonio Remón Cantera`,
		party: `National Patriotic Coalition`,
		leaning: leanings.RIGHT,
		tookOffice: `1 October 1952`,
		leftOffice: `2 January 1955`,
	},
	{
		countryId,
		name: `José Ramón Guizado`,
		party: `National Patriotic Coalition`,
		leaning: leanings.RIGHT,
		tookOffice: `2 January 1955`,
		leftOffice: `29 March 1955`,
	},
	{
		countryId,
		name: `Ricardo Arias`,
		party: `National Patriotic Coalition`,
		leaning: leanings.RIGHT,
		tookOffice: `29 March 1955`,
		leftOffice: `1 October 1956`,
	},
	{
		countryId,
		name: `Ernesto de la Guardia`,
		party: `National Patriotic Coalition`,
		leaning: leanings.RIGHT,
		tookOffice: `1 October 1956`,
		leftOffice: `1 October 1960`,
	},
	{
		countryId,
		name: `Roberto Francisco Chiari Remón`,
		party: `National Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 October 1960`,
		leftOffice: `1 October 1964`,
	},
	{
		countryId,
		name: `Marco Aurelio Robles`,
		party: `National Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 October 1964`,
		leftOffice: `1 October 1968`,
	},
	{
		countryId,
		name: `Arnulfo Arias`,
		party: `Panameñista Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 October 1968`,
		leftOffice: `11 October 1968`,
	},
	{
		countryId,
		name: `Bolivar Urrutia Parrilla`,
		party: `National Guard`,
		leaning: leanings.CENTRIST,
		tookOffice: `12 October 1968`,
		leftOffice: `18 December 1969`,
	},
	{
		countryId,
		name: `Demetrio B. Lakas`,
		party: `Democratic Revolutionary Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `19 December 1969`,
		leftOffice: `11 October 1978`,
	},
	{
		countryId,
		name: `Aristides Royo`,
		party: `Democratic Revolutionary Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `11 October 1978`,
		leftOffice: `31 July 1982`,
	},
	{
		countryId,
		name: `Ricardo de la Espriella`,
		party: `Democratic Revolutionary Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `31 July 1982`,
		leftOffice: `13 February 1984`,
	},
	{
		countryId,
		name: `Jorge Illueca`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `13 February 1984`,
		leftOffice: `11 October 1984`,
	},
	{
		countryId,
		name: `Nicolás Ardito Barletta Vallarino`,
		party: `Democratic Revolutionary Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `11 October 1984`,
		leftOffice: `28 September 1985`,
	},
	{
		countryId,
		name: `Eric Arturo Delvalle`,
		party: `Republican Party`,
		leaning: leanings.RIGHT,
		tookOffice: `28 September 1985`,
		leftOffice: `26 February 1988`,
	},
	{
		countryId,
		name: `Manuel Solís Palma`,
		party: `Democratic Revolutionary Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `26 February 1988`,
		leftOffice: `1 September 1989`,
	},
	{
		countryId,
		name: `Francisco Rodríguez`,
		party: `Democratic Revolutionary Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 September 1989`,
		leftOffice: `20 December 1989`,
	},
	{
		countryId,
		name: `Guillermo Endara`,
		party: `Panameñista Party`,
		leaning: leanings.RIGHT,
		tookOffice: `20 December 1989`,
		leftOffice: `1 September 1994`,
	},
	{
		countryId,
		name: `Ernesto Pérez Balladares`,
		party: `Democratic Revolutionary Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 September 1994`,
		leftOffice: `1 September 1999`,
	},
	{
		countryId,
		name: `Mireya Moscoso`,
		party: `Panameñista Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 September 1999`,
		leftOffice: `1 September 2004`,
	},
	{
		countryId,
		name: `Martín Torrijos`,
		party: `Democratic Revolutionary Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 September 2004`,
		leftOffice: `1 July 2009`,
	},
	{
		countryId,
		name: `Ricardo Martinelli`,
		party: `Democratic Change`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 July 2009`,
		leftOffice: `1 July 2014`,
	},
	{
		countryId,
		name: `Juan Carlos Varela`,
		party: `Panameñista Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 July 2014`,
		leftOffice: `1 July 2019`,
	},
	{
		countryId,
		name: `Laurentino Cortizo`,
		party: `Democratic Revolutionary Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 July 2019`,
		leftOffice: null,
	},
];
