import type { LeaderNoId } from '../../app/data/types';
import { leanings } from '../../app/data/types';

export const source = `https://www.mapsofworld.com/list-of/presidents-paraguay/`;

const countryId = 18;

export const paraguay: LeaderNoId[] = [
	{
		name: 'Carlos Antonio López',
		party: null,
		leaning: null,
		tookOffice: '13 March 1844',
		leftOffice: '13 March 1854',
	},
	{
		name: 'Carlos Antonio López',
		party: null,
		leaning: null,
		tookOffice: '13 March 1854',
		leftOffice: '13 March 1857',
	},
	{
		name: 'Carlos Antonio López',
		party: null,
		leaning: null,
		tookOffice: '13 March 1857',
		leftOffice: '10 September 1862',
	},
	{
		name: 'Francisco Solano López',
		party: null,
		leaning: null,
		tookOffice: '10 September 1862',
		leftOffice: '16 October 1862',
	},
	{
		name: 'Francisco Solano López',
		party: null,
		leaning: null,
		tookOffice: '16 October 1862',
		leftOffice: '1 March 1870',
	},
	{
		name: 'Facundo Machaín',
		party: null,
		leaning: null,
		tookOffice: '31 August 1870',
		leftOffice: '1 September 1870',
	},
	{
		name: 'Cirilo Antonio Rivarola',
		party: null,
		leaning: null,
		tookOffice: '1 September 1870',
		leftOffice: '25 November 1870',
	},
	{
		name: 'Cirilo Antonio Rivarola',
		party: null,
		leaning: null,
		tookOffice: '25 November 1870',
		leftOffice: '18 December 1871',
	},
	{
		name: 'Salvador Jovellanos',
		party: null,
		leaning: null,
		tookOffice: '18 December 1871',
		leftOffice: '25 November 1874',
	},
	{
		name: 'Juan Bautista Gill',
		party: null,
		leaning: null,
		tookOffice: '25 November 1874',
		leftOffice: '12 April 1877',
	},
	{
		name: 'Higinio Uriarte',
		party: null,
		leaning: null,
		tookOffice: '12 April 1877',
		leftOffice: '25 November 1878',
	},
	{
		name: 'Cándido Bareiro',
		party: null,
		leaning: null,
		tookOffice: '25 November 1878',
		leftOffice: '4 September 1880',
	},
	{
		name: 'Bernardino Caballero',
		party: null,
		leaning: null,
		tookOffice: '4 September 1880',
		leftOffice: '25 November 1882',
	},
	{
		name: 'Bernardino Caballero',
		party: null,
		leaning: null,
		tookOffice: '25 November 1882',
		leftOffice: '25 November 1886',
	},
	{
		name: 'Patricio Escobar',
		party: 'Colorado party (Paraguay)',
		leaning: 'Centre-right to right-wing',
		tookOffice: '25 November 1886',
		leftOffice: '25 November 1890',
	},
	{
		name: 'Juan Gualberto González',
		party: 'Colorado party (Paraguay)',
		leaning: 'Centre-right to right-wing',
		tookOffice: '25 November 1890',
		leftOffice: '9 June 1894',
	},
	{
		name: 'Marcos Morínigo',
		party: 'Colorado party (Paraguay)',
		leaning: 'Centre-right to right-wing',
		tookOffice: '9 June 1894',
		leftOffice: '25 November 1894',
	},
	{
		name: 'Juan Bautista Egusquiza',
		party: 'Colorado party (Paraguay)',
		leaning: 'Centre-right to right-wing',
		tookOffice: '25 November 1894',
		leftOffice: '25 November 1898',
	},
	{
		name: 'Emilio Aceval',
		party: 'Colorado party (Paraguay)',
		leaning: 'Centre-right to right-wing',
		tookOffice: '25 November 1898',
		leftOffice: '9 January 1902',
	},
	{
		name: 'Andrés Héctor Carvallo',
		party: 'Colorado party (Paraguay)',
		leaning: 'Centre-right to right-wing',
		tookOffice: '9 January 1902',
		leftOffice: '25 November 1902',
	},
	{
		name: 'Juan Antonio Escurra',
		party: 'Colorado party (Paraguay)',
		leaning: 'Centre-right to right-wing',
		tookOffice: '25 November 1902',
		leftOffice: '19 December 1904',
	},
	{
		countryId,
		name: `Andrés Héctor Carvallo`,
		party: `Colorado Party`,
		leaning: leanings.RIGHT,
		tookOffice: `9 January 1902`,
		leftOffice: `25 November 1902`,
	},
	{
		countryId,
		name: `Juan Antonio Escurra`,
		party: `Colorado Party`,
		leaning: leanings.RIGHT,
		tookOffice: `25 November 1902`,
		leftOffice: `19 December 1904`,
	},
	{
		countryId,
		name: `Juan Bautista Gaona`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `19 December 1904`,
		leftOffice: `9 December 1905`,
	},
	{
		countryId,
		name: `Cecilio Báez`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 December 1905`,
		leftOffice: `25 November 1906`,
	},
	{
		countryId,
		name: `Benigno Ferreira`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `25 November 1906`,
		leftOffice: `4 July 1908`,
	},
	{
		countryId,
		name: `Emiliano González Navero`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `4 July 1908`,
		leftOffice: `25 November 1910`,
	},
	{
		countryId,
		name: `Manuel Gondra`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `25 November 1910`,
		leftOffice: `17 January 1911`,
	},
	{
		countryId,
		name: `Albino Jara`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `17 January 1911`,
		leftOffice: `5 July 1911`,
	},
	{
		countryId,
		name: `Liberato Marcial Rojas`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `5 July 1911`,
		leftOffice: `28 February 1912`,
	},
	{
		countryId,
		name: `Pedro Peña`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `28 February 1911`,
		leftOffice: `22 March 1912`,
	},
	{
		countryId,
		name: `Emiliano González Navero`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 July 1908`,
		leftOffice: `25 November 1910`,
	},
	{
		countryId,
		name: `Eduardo Schaerer`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `15 August 1912`,
		leftOffice: `15 August 1916`,
	},
	{
		countryId,
		name: `Manuel Franco`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `15 August 1916`,
		leftOffice: `5 June 1919`,
	},
	{
		countryId,
		name: `José Pedro Montero`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `6 June 1919`,
		leftOffice: `15 August 1920`,
	},
	{
		countryId,
		name: `Manuel Gondra`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `15 August 1920`,
		leftOffice: `7 November 1921`,
	},
	{
		countryId,
		name: `Eusebio Ayala`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `7 November 1921`,
		leftOffice: `12 April 1923`,
	},
	{
		countryId,
		name: `José Eligio Ayala`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `12 April 1923`,
		leftOffice: `17 March 1924`,
	},
	{
		countryId,
		name: `Luis Alberto Riart`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `17 March 1924`,
		leftOffice: `15 August 1924`,
	},
	{
		countryId,
		name: `José Eligio Ayala`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `15 August 1924`,
		leftOffice: `15 August 1928`,
	},
	{
		countryId,
		name: `José Patricio Guggiari`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `15 August 1928`,
		leftOffice: `15 August 1932`,
	},
	{
		countryId,
		name: `Eusebio Ayala`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `15 August 1932`,
		leftOffice: `17 February 1936`,
	},
	{
		countryId,
		name: `Rafael Franco Ojeda`,
		party: `Revolutionary Febrerista Party`,
		leaning: leanings.LEFT,
		tookOffice: `17 February 1936`,
		leftOffice: `13 August 1937`,
	},
	{
		countryId,
		name: `Félix Paiva`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `15 August 1937`,
		leftOffice: `15 August 1939`,
	},
	{
		countryId,
		name: `José Félix Estigarribia`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `15 August 1939`,
		leftOffice: `7 September 1940`,
	},
	{
		countryId,
		name: `Higinio Morínigo`,
		party: `Independent`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `7 September 1940`,
		leftOffice: `3 June 1948`,
	},
	{
		countryId,
		name: `Juan Manuel Frutos`,
		party: `Colorado Party`,
		leaning: leanings.RIGHT,
		tookOffice: `16 June 1948`,
		leftOffice: `15 August 1948`,
	},
	{
		countryId,
		name: `Juan Natalicio González`,
		party: `Colorado Party`,
		leaning: leanings.RIGHT,
		tookOffice: `16 August 1948`,
		leftOffice: `30 January 1949`,
	},
	{
		countryId,
		name: `Raimundo Rolón`,
		party: `Colorado Party`,
		leaning: leanings.RIGHT,
		tookOffice: `30 January 1949`,
		leftOffice: `27 February 1949`,
	},
	{
		countryId,
		name: `Felipe Molas López`,
		party: `Colorado Party`,
		leaning: leanings.RIGHT,
		tookOffice: `27 February 1949`,
		leftOffice: `10 September 1949`,
	},
	{
		countryId,
		name: `Federico Chaves Careaga`,
		party: `Colorado Party`,
		leaning: leanings.RIGHT,
		tookOffice: `10 September 1949`,
		leftOffice: `5 May 1954`,
	},
	{
		countryId,
		name: `Tomás Romero Pereira`,
		party: `Colorado Party`,
		leaning: leanings.RIGHT,
		tookOffice: `5 May 1954`,
		leftOffice: `15 August 1954`,
	},
	{
		countryId,
		name: `Alfredo Stroessner`,
		party: `Colorado Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `15 August 1954`,
		leftOffice: `3 February 1989`,
	},
	{
		countryId,
		name: `Andrés Rodríguez`,
		party: `Colorado Party`,
		leaning: leanings.RIGHT,
		tookOffice: `3 February 1989`,
		leftOffice: `15 August 1993`,
	},
	{
		countryId,
		name: `Juan Carlos Wasmosy`,
		party: `Colorado Party`,
		leaning: leanings.RIGHT,
		tookOffice: `15 August 1993`,
		leftOffice: `14 August 1998`,
	},
	{
		countryId,
		name: `Raúl Cubas Grau`,
		party: `Colorado Party`,
		leaning: leanings.RIGHT,
		tookOffice: `15 August 1998`,
		leftOffice: `29 March 1999`,
	},
	{
		countryId,
		name: `Luis Ángel González Macchi`,
		party: `Colorado Party`,
		leaning: leanings.RIGHT,
		tookOffice: `28 March 1999`,
		leftOffice: `15 August 2003`,
	},
	{
		countryId,
		name: `Nicanor Duarte`,
		party: `Colorado Party`,
		leaning: leanings.RIGHT,
		tookOffice: `15 August 2003`,
		leftOffice: `14 August 2008`,
	},
	{
		countryId,
		name: `Fernando Lugo`,
		party: `Patriotic Alliance for Change`,
		leaning: leanings.LEFT,
		tookOffice: `15 August 2008`,
		leftOffice: `22 June 2012`,
	},
	{
		countryId,
		name: `Federico Franco`,
		party: `Authentic Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `22 June 2012`,
		leftOffice: `15 August 2013`,
	},
	{
		countryId,
		name: `Horacio Cartes`,
		party: `Colorado Party`,
		leaning: leanings.RIGHT,
		tookOffice: `15 August 2013`,
		leftOffice: `15 August 2018`,
	},
	{
		countryId,
		name: `Mario Abdo Benítez`,
		party: `Colorado Party`,
		leaning: leanings.RIGHT,
		tookOffice: `15 August 2018`,
		leftOffice: `15 August 2023`,
	},
	{
		countryId,
		name: `Santiago Peña`,
		party: `Colorado Party`,
		leaning: leanings.RIGHT,
		tookOffice: `15 August 2023`,
		leftOffice: null,
	},
];
