import type { LeaderNoId } from '../../app/data/types';
import { leanings } from '../../app/data/types';

export const source = `https://www.mapsofworld.com/list-of/presidents-peru/`;

const countryId = 16;

export const peru: LeaderNoId[] = [
	{
		countryId,
		name: `Dina Boluarte`,
		party: `Independent`,
		leaning: leanings.LEFT,
		tookOffice: `7 December 2022`,
		leftOffice: null,
	},
	{
		countryId,
		name: `Pedro Castillo`,
		party: `Free Peru`,
		leaning: leanings.FAR_LEFT,
		tookOffice: `28 July 2021`,
		leftOffice: `7 December 2022`,
	},
	{
		countryId,
		name: `Francisco Sagasti`,
		party: `Purple Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `17 November 2020`,
		leftOffice: `28 July 2021`,
	},
	{
		countryId,
		name: `Manuel Merino`,
		party: `Popular Action`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `10 November 2020`,
		leftOffice: `15 November 2020`,
	},
	{
		countryId,
		name: `Martín Vizcarra`,
		party: `Peruvians for Change`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `23 March 2018`,
		leftOffice: `9 November 2020`,
	},
	{
		countryId,
		name: `Pedro Pablo Kuczynski Godard`,
		party: `Peruvians for Change`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `July 28, 2016`,
		leftOffice: `March 21, 2018`,
	},
	{
		countryId,
		name: `Ollanta Humala`,
		party: `Peruvian Nationalist Party`,
		leaning: leanings.LEFT,
		tookOffice: `July 28, 2011`,
		leftOffice: `July 28, 2016`,
	},
	{
		countryId,
		name: `Alan García`,
		party: `American Popular Revolutionary Alliance`,
		leaning: leanings.LEFT,
		tookOffice: `28 July 2006`,
		leftOffice: `28 July 2011`,
	},
	{
		countryId,
		name: `Alejandro Toledo`,
		party: `Possible Peru`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `28 July 2001`,
		leftOffice: `28 July 2006`,
	},
	{
		countryId,
		name: `Valentín Paniagua`,
		party: `Popular Action`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `22 November 2000`,
		leftOffice: `28 July 2001`,
	},
	{
		countryId,
		name: `Alberto Fujimori`,
		party: `Peru 2000`,
		leaning: leanings.RIGHT,
		tookOffice: `28 July 1990`,
		leftOffice: `22 November 2000`,
	},
	{
		countryId,
		name: `Alan García`,
		party: `American Popular Revolutionary Alliance`,
		leaning: leanings.LEFT,
		tookOffice: `28 July 1985`,
		leftOffice: `28 July 1990`,
	},
	{
		countryId,
		name: `Fernando Belaúnde Terry`,
		party: `Popular Action`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `28 July 1980`,
		leftOffice: `28 July 1985`,
	},
	{
		countryId,
		name: `Francisco Morales Bermúdez`,
		party: `Peruvian Armed Forces`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `30 August 1975`,
		leftOffice: `28 July 1980`,
	},
	{
		countryId,
		name: `Juan Velasco Alvarado`,
		party: `Peruvian Armed Forces`,
		leaning: leanings.LEFT,
		tookOffice: `3 October 1968`,
		leftOffice: `30 August 1975`,
	},
	{
		countryId,
		name: `Fernando Belaúnde Terry`,
		party: `Popular Action`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `28 July 1963`,
		leftOffice: `3 October 1968`,
	},
	{
		countryId,
		name: `Nicolás Lindley`,
		party: `Peruvian Armed Forces - Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `3 March 1963`,
		leftOffice: `28 July 1963`,
	},
	{
		countryId,
		name: `Ricardo Pérez Godoy`,
		party: `Peruvian Armed Forces - Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `18 July 1962`,
		leftOffice: `3 March 1963`,
	},
	{
		countryId,
		name: `Manuel Prado`,
		party: `Pradist Democratic Movement`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `28 July 1956`,
		leftOffice: `18 July 1962`,
	},
	{
		countryId,
		name: `Manuel A. Odría`,
		party: `Unión Nacional Odriista`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `28 July 1950`,
		leftOffice: `28 July 1956`,
	},
	{
		countryId,
		name: `Zenón Noriega Agüero`,
		party: `Peruvian Armed Forces`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 June 1950`,
		leftOffice: `28 July 1950`,
	},
	{
		countryId,
		name: `Manuel A. Odría`,
		party: `Unión Nacional Odriista`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `27 October 1948`,
		leftOffice: `1 June 1950`,
	},
	{
		countryId,
		name: `José Bustamante`,
		party: `National Democratic Front`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `28 July 1945`,
		leftOffice: `29 October 1948`,
	},
	{
		countryId,
		name: `Manuel Prado`,
		party: `Pradist Democratic Movement`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 December 1939`,
		leftOffice: `28 July 1945`,
	},
	{
		countryId,
		name: `Óscar R. Benavides`,
		party: `Peruvian Armed Forces`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `30 April 1933`,
		leftOffice: `8 December 1939`,
	},
	{
		countryId,
		name: `Luis Miguel Sánchez Cerro`,
		party: `Revolutionary Union`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `8 December 1931`,
		leftOffice: `30 April 1933`,
	},
	{
		countryId,
		name: `David Samanez Ocampo`,
		party: `Democratic Party of Peru`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `11 March 1931`,
		leftOffice: `8 December 1931`,
	},
	{
		countryId,
		name: `Gustavo Jiménez`,
		party: `Peruvian Armed Forces`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `5 March 1931`,
		leftOffice: `11 March 1931`,
	},
	{
		countryId,
		name: `Ricardo Leoncio Elías Arias`,
		party: `Peruvian Armed Forces`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `1 March 1931`,
		leftOffice: `5 March 1931`,
	},
	{
		countryId,
		name: `Luis Miguel Sánchez Cerro`,
		party: `Revolutionary Union`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `27 August 1930`,
		leftOffice: `1 March 1931`,
	},
	{
		countryId,
		name: `Manuel María Ponce Brousset`,
		party: `Peruvian Armed Forces`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `25 August 1930`,
		leftOffice: `27 August 1930`,
	},
	{
		countryId,
		name: `Augusto B. Leguía`,
		party: `Reformist Democratic Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `4 July 1919`,
		leftOffice: `25 August 1930`,
	},
	{
		countryId,
		name: `José Pardo`,
		party: `Civilista Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `18 August 1915`,
		leftOffice: `4 July 1919`,
	},
	{
		countryId,
		name: `Óscar R. Benavides`,
		party: `Peruvian Armed Forces`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `4 February 1914`,
		leftOffice: `18 August 1915`,
	},
	{
		countryId,
		name: `Guillermo Billinghurst`,
		party: `Democratic Party of Peru`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `24 September 1912`,
		leftOffice: `4 February 1914`,
	},
	{
		countryId,
		name: `Augusto B. Leguía`,
		party: `Civilista Party`,
		leaning: leanings.RIGHT,
		tookOffice: `24 September 1908`,
		leftOffice: `24 September 1912`,
	},
	{
		countryId,
		name: `José Pardo`,
		party: `Civilista Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `24 September 1904`,
		leftOffice: `24 September 1908`,
	},
	{
		countryId,
		name: `Serapio Calderón`,
		party: `Civilista Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `7 May 1904`,
		leftOffice: `24 September 1904`,
	},
	{
		countryId,
		name: `Manuel Candamo`,
		party: `Civilista Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 September 1903`,
		leftOffice: `7 May 1904`,
	},
	{
		countryId,
		name: `Eduardo López de Romaña`,
		party: `Civilista Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 September 1899`,
		leftOffice: `8 September 1903`,
	},
	{
		countryId,
		name: `Nicolás de Piérola`,
		party: `Democratic Party of Peru`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `8 September 1895`,
		leftOffice: `8 September 1899`,
	},
	{
		countryId,
		name: `Manuel Candamo`,
		party: `Civilista Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `20 March 1895`,
		leftOffice: `8 September 1895`,
	},
	{
		countryId,
		name: `Andrés Avelino Cáceres`,
		party: `Constitutional Party`,
		leaning: leanings.RIGHT,
		tookOffice: `10 August 1894`,
		leftOffice: `20 March 1895`,
	},
	{
		countryId,
		name: `Justiniano Borgoño Castañeda`,
		party: `Constitutional Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 April 1894`,
		leftOffice: `10 August 1894`,
	},
	{
		countryId,
		name: `Remigio Morales Bermúdez`,
		party: `Constitutional Party`,
		leaning: leanings.RIGHT,
		tookOffice: `10 August 1890`,
		leftOffice: `1 April 1894`,
	},
	{
		countryId,
		name: `Andrés Avelino Cáceres`,
		party: `Constitutional Party`,
		leaning: leanings.RIGHT,
		tookOffice: `5 June 1886`,
		leftOffice: `10 August 1890`,
	},
];
