import type { LeaderNoId } from '../../app/data/types';
import { leanings } from '../../app/data/types';

export const source = `https://en.wikipedia.org/wiki/List_of_presidents_of_Peru`;

const countryId = 16;

export const peru: LeaderNoId[] = [
	{
		countryId,
		name: 'Viceroyalty of Peru',
		party: 'Spanish Empire',
		leaning: leanings.MONARCHY,
		tookOffice: '1 January 1542',
		leftOffice: '3 August 1821',
	},
	{
		countryId,
		name: 'José de San Martín',
		party: 'Independent',
		leaning: leanings.RIGHT,
		tookOffice: '3 August 1821',
		leftOffice: '20 September 1822',
	},
	{
		countryId,
		name: 'José de la Riva Agüero',
		party: 'Military',
		leaning: leanings.CENTRIST,
		tookOffice: '28 February 1823',
		leftOffice: '23 June 1823',
	},
	{
		countryId,
		name: 'José Bernardo de Tagle',
		party: 'Military',
		leaning: leanings.CENTRIST,
		tookOffice: '16 August 1823',
		leftOffice: '10 February 1824',
	},
	{
		countryId,
		name: 'Simón Bolívar',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '10 February 1824',
		leftOffice: '10 June 1827',
	},
	{
		countryId,
		name: 'José de La Mar',
		party: 'Military',
		leaning: leanings.CENTRIST,
		tookOffice: '10 June 1827',
		leftOffice: '7 June 1829',
	},
	{
		countryId,
		name: 'Agustín Gamarra',
		party: 'Military',
		leaning: leanings.CENTRIST,
		tookOffice: '7 June 1829',
		leftOffice: '19 December 1833',
	},
	{
		countryId,
		name: 'Luis José de Orbegoso',
		party: 'Military',
		leaning: leanings.CENTRIST,
		tookOffice: '21 December 1833',
		leftOffice: '25 February 1835',
	},
	{
		countryId,
		name: 'Felipe Salaverry',
		party: 'Military',
		leaning: leanings.CENTRIST,
		tookOffice: '25 February 1835',
		leftOffice: '7 February 1836',
	},
	{
		countryId,
		name: 'Andrés de Santa Cruz',
		party: 'Peru–Bolivian Confederation',
		leaning: leanings.CENTRIST,
		tookOffice: '7 February 1836',
		leftOffice: '20 January 1839',
	},
	{
		countryId,
		name: 'Agustín Gamarra',
		party: 'Military',
		leaning: leanings.CENTRIST,
		tookOffice: '20 January 1839',
		leftOffice: '18 November 1841',
	},
	{
		countryId,
		name: 'Manuel Menéndez',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '18 November 1841',
		leftOffice: '16 August 1842',
	},
	{
		countryId,
		name: 'Juan Francisco de Vidal',
		party: 'Military',
		leaning: leanings.CENTRIST,
		tookOffice: '20 October 1842',
		leftOffice: '15 March 1843',
	},
	{
		countryId,
		name: 'Manuel Ignacio de Vivanco',
		party: 'Military',
		leaning: leanings.CENTRIST,
		tookOffice: '27 March 1843',
		leftOffice: '17 June 1844',
	},
	{
		countryId,
		name: 'Manuel Menéndez',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '7 October 1844',
		leftOffice: '20 April 1845',
	},
	{
		countryId,
		name: 'Ramón Castilla',
		party: 'Military',
		leaning: leanings.CENTER_LEFT,
		tookOffice: '20 April 1845',
		leftOffice: '20 April 1851',
	},
	{
		countryId,
		name: 'José Rufino Echenique',
		party: 'Military',
		leaning: leanings.CENTRIST,
		tookOffice: '20 April 1851',
		leftOffice: '5 January 1855',
	},
	{
		countryId,
		name: 'Ramón Castilla',
		party: 'Military',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '5 January 1855',
		leftOffice: '24 October 1862',
	},
	{
		countryId,
		name: 'Miguel de San Román',
		party: 'Military',
		leaning: leanings.CENTRIST,
		tookOffice: '24 October 1862',
		leftOffice: '3 April 1863',
	},
	{
		countryId,
		name: 'Pedro Diez Canseco',
		party: 'Military',
		leaning: leanings.CENTRIST,
		tookOffice: '3 April 1863',
		leftOffice: '5 August 1863',
	},
	{
		countryId,
		name: 'Juan Antonio Pezet',
		party: 'Military',
		leaning: leanings.CENTRIST,
		tookOffice: '5 August 1863',
		leftOffice: '8 November 1865',
	},
	{
		countryId,
		name: 'Mariano Ignacio Prado',
		party: 'Military',
		leaning: leanings.CENTRIST,
		tookOffice: '28 November 1865',
		leftOffice: '15 February 1867',
	},
	{
		countryId,
		name: 'Mariano Ignacio Prado',
		party: 'Military',
		leaning: leanings.CENTRIST,
		tookOffice: '15 February 1867',
		leftOffice: '31 August 1867',
	},
	{
		countryId,
		name: 'Mariano Ignacio Prado',
		party: 'Military',
		leaning: leanings.CENTRIST,
		tookOffice: '31 August 1867',
		leftOffice: '7 January 1868',
	},
	{
		countryId,
		name: 'Mariano Ignacio Prado',
		party: 'Military',
		leaning: leanings.CENTRIST,
		tookOffice: '7 January 1868',
		leftOffice: '2 August 1868',
	},
	{
		countryId,
		name: 'José Balta',
		party: 'Military',
		leaning: leanings.CENTRIST,
		tookOffice: '2 August 1868',
		leftOffice: '22 July 1872',
	},
	{
		countryId,
		name: 'Tomás Gutiérrez',
		party: 'Military',
		leaning: leanings.CENTRIST,
		tookOffice: '22 July 1872',
		leftOffice: '26 July 1872',
	},
	{
		countryId,
		name: 'Mariano Herencia Zevallos',
		party: 'Civilista Party',
		leaning: leanings.RIGHT,
		tookOffice: '27 July 1872',
		leftOffice: '2 August 1872',
	},
	{
		countryId,
		name: 'Manuel Pardo y Lavalle',
		party: 'Civilista Party',
		leaning: leanings.RIGHT,
		tookOffice: '2 August 1872',
		leftOffice: '2 August 1876',
	},
	{
		countryId,
		name: 'Mariano Ignacio Prado',
		party: 'Civilista Party',
		leaning: leanings.RIGHT,
		tookOffice: '2 August 1876',
		leftOffice: '18 December 1879',
	},
	{
		countryId,
		name: 'Luis La Puerta',
		party: 'Military',
		leaning: leanings.CENTRIST,
		tookOffice: '18 December 1879',
		leftOffice: '23 December 1879',
	},
	{
		countryId,
		name: 'Nicolás de Piérola',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '23 December 1879',
		leftOffice: '28 July 1881',
	},
	{
		countryId,
		name: 'Nicolás de Piérola',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '31 July 1881',
		leftOffice: '28 December 1881',
	},
	{
		countryId,
		name: 'Francisco García Calderón',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '12 March 1881',
		leftOffice: '10 July 1881',
	},
	{
		countryId,
		name: 'Francisco García Calderón',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '10 July 1881',
		leftOffice: '6 November 1881',
	},
	{
		countryId,
		name: 'Lizardo Montero',
		party: 'Civilista Party',
		leaning: leanings.RIGHT,
		tookOffice: '28 September 1881',
		leftOffice: '28 October 1883',
	},
	{
		countryId,
		name: 'Miguel Iglesias',
		party: 'Military',
		leaning: leanings.RIGHT,
		tookOffice: '30 December 1882',
		leftOffice: '3 December 1885',
	},
	{
		countryId,
		name: 'Antonio Arenas',
		party: 'President of the Government Junta of Peru',
		leaning: leanings.CENTRIST,
		tookOffice: '3 December 1885',
		leftOffice: '5 June 1886',
	},
	{
		countryId,
		name: `Andrés Avelino Cáceres`,
		party: `Constitutional Party`,
		leaning: leanings.RIGHT,
		tookOffice: `5 June 1886`,
		leftOffice: `10 August 1890`,
	},
	{
		countryId,
		name: `Remigio Morales Bermúdez`,
		party: `Constitutional Party`,
		leaning: leanings.RIGHT,
		tookOffice: `10 August 1890`,
		leftOffice: `1 April 1894`,
	},
	{
		countryId,
		name: `Justiniano Borgoño Castañeda`,
		party: `Constitutional Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 April 1894`,
		leftOffice: `10 August 1894`,
	},
	{
		countryId,
		name: `Andrés Avelino Cáceres`,
		party: `Constitutional Party`,
		leaning: leanings.RIGHT,
		tookOffice: `10 August 1894`,
		leftOffice: `20 March 1895`,
	},
	{
		countryId,
		name: `Manuel Candamo`,
		party: `Civilista Party`,
		leaning: leanings.RIGHT,
		tookOffice: `20 March 1895`,
		leftOffice: `8 September 1895`,
	},
	{
		countryId,
		name: `Nicolás de Piérola`,
		party: `Democratic Party of Peru`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `8 September 1895`,
		leftOffice: `8 September 1899`,
	},
	{
		countryId,
		name: `Eduardo López de Romaña`,
		party: `Civilista Party`,
		leaning: leanings.RIGHT,
		tookOffice: `8 September 1899`,
		leftOffice: `8 September 1903`,
	},
	{
		countryId,
		name: `Manuel Candamo`,
		party: `Civilista Party`,
		leaning: leanings.RIGHT,
		tookOffice: `8 September 1903`,
		leftOffice: `7 May 1904`,
	},
	{
		countryId,
		name: `Serapio Calderón`,
		party: `Civilista Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 May 1904`,
		leftOffice: `24 September 1904`,
	},
	{
		countryId,
		name: `José Pardo`,
		party: `Civilista Party`,
		leaning: leanings.RIGHT,
		tookOffice: `24 September 1904`,
		leftOffice: `24 September 1908`,
	},
	{
		countryId,
		name: `Augusto B. Leguía`,
		party: `Civilista Party`,
		leaning: leanings.RIGHT,
		tookOffice: `24 September 1908`,
		leftOffice: `24 September 1912`,
	},
	{
		countryId,
		name: `Guillermo Billinghurst`,
		party: `Democratic Party of Peru`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `24 September 1912`,
		leftOffice: `4 February 1914`,
	},
	{
		countryId,
		name: `Óscar R. Benavides`,
		party: `Peruvian Armed Forces`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `4 February 1914`,
		leftOffice: `18 August 1915`,
	},
	{
		countryId,
		name: `José Pardo`,
		party: `Civilista Party`,
		leaning: leanings.RIGHT,
		tookOffice: `18 August 1915`,
		leftOffice: `4 July 1919`,
	},
	{
		countryId,
		name: `Augusto B. Leguía`,
		party: `Reformist Democratic Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `4 July 1919`,
		leftOffice: `25 August 1930`,
	},
	{
		countryId,
		name: `Manuel María Ponce Brousset`,
		party: `Peruvian Armed Forces`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `25 August 1930`,
		leftOffice: `27 August 1930`,
	},
	{
		countryId,
		name: `Luis Miguel Sánchez Cerro`,
		party: `Revolutionary Union`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `27 August 1930`,
		leftOffice: `1 March 1931`,
	},
	{
		countryId,
		name: `Ricardo Leoncio Elías Arias`,
		party: `Peruvian Armed Forces`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `1 March 1931`,
		leftOffice: `5 March 1931`,
	},
	{
		countryId,
		name: `Gustavo Jiménez`,
		party: `Peruvian Armed Forces`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `5 March 1931`,
		leftOffice: `11 March 1931`,
	},
	{
		countryId,
		name: `David Samanez Ocampo`,
		party: `Democratic Party of Peru`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `11 March 1931`,
		leftOffice: `8 December 1931`,
	},
	{
		countryId,
		name: `Luis Miguel Sánchez Cerro`,
		party: `Revolutionary Union`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `8 December 1931`,
		leftOffice: `30 April 1933`,
	},
	{
		countryId,
		name: `Óscar R. Benavides`,
		party: `Peruvian Armed Forces`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `30 April 1933`,
		leftOffice: `8 December 1939`,
	},
	{
		countryId,
		name: `Manuel Prado`,
		party: `Pradist Democratic Movement`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 December 1939`,
		leftOffice: `28 July 1945`,
	},
	{
		countryId,
		name: `José Bustamante`,
		party: `National Democratic Front`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `28 July 1945`,
		leftOffice: `29 October 1948`,
	},
	{
		countryId,
		name: `Manuel A. Odría`,
		party: `Unión Nacional Odriista`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `27 October 1948`,
		leftOffice: `1 June 1950`,
	},
	{
		countryId,
		name: `Zenón Noriega Agüero`,
		party: `Peruvian Armed Forces`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 June 1950`,
		leftOffice: `28 July 1950`,
	},
	{
		countryId,
		name: `Manuel A. Odría`,
		party: `Unión Nacional Odriista`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `28 July 1950`,
		leftOffice: `28 July 1956`,
	},
	{
		countryId,
		name: `Manuel Prado`,
		party: `Pradist Democratic Movement`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `28 July 1956`,
		leftOffice: `18 July 1962`,
	},
	{
		countryId,
		name: `Ricardo Pérez Godoy`,
		party: `Peruvian Armed Forces - Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `18 July 1962`,
		leftOffice: `3 March 1963`,
	},
	{
		countryId,
		name: `Nicolás Lindley`,
		party: `Peruvian Armed Forces - Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `3 March 1963`,
		leftOffice: `28 July 1963`,
	},
	{
		countryId,
		name: `Fernando Belaúnde Terry`,
		party: `Popular Action`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `28 July 1963`,
		leftOffice: `3 October 1968`,
	},
	{
		countryId,
		name: `Juan Velasco Alvarado`,
		party: `Peruvian Armed Forces`,
		leaning: leanings.LEFT,
		tookOffice: `3 October 1968`,
		leftOffice: `30 August 1975`,
	},
	{
		countryId,
		name: `Francisco Morales Bermúdez`,
		party: `Peruvian Armed Forces`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `30 August 1975`,
		leftOffice: `28 July 1980`,
	},
	{
		countryId,
		name: `Fernando Belaúnde Terry`,
		party: `Popular Action`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `28 July 1980`,
		leftOffice: `28 July 1985`,
	},
	{
		countryId,
		name: `Alan García`,
		party: `American Popular Revolutionary Alliance`,
		leaning: leanings.LEFT,
		tookOffice: `28 July 1985`,
		leftOffice: `28 July 1990`,
	},
	{
		countryId,
		name: `Alberto Fujimori`,
		party: `Peru 2000`,
		leaning: leanings.RIGHT,
		tookOffice: `28 July 1990`,
		leftOffice: `22 November 2000`,
	},
	{
		countryId,
		name: `Valentín Paniagua`,
		party: `Popular Action`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `22 November 2000`,
		leftOffice: `28 July 2001`,
	},
	{
		countryId,
		name: `Alejandro Toledo`,
		party: `Possible Peru`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `28 July 2001`,
		leftOffice: `28 July 2006`,
	},
	{
		countryId,
		name: `Alan García`,
		party: `American Popular Revolutionary Alliance`,
		leaning: leanings.LEFT,
		tookOffice: `28 July 2006`,
		leftOffice: `28 July 2011`,
	},
	{
		countryId,
		name: `Ollanta Humala`,
		party: `Peruvian Nationalist Party`,
		leaning: leanings.LEFT,
		tookOffice: `July 28, 2011`,
		leftOffice: `July 28, 2016`,
	},
	{
		countryId,
		name: `Pedro Pablo Kuczynski Godard`,
		party: `Peruvians for Change`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `July 28, 2016`,
		leftOffice: `March 21, 2018`,
	},
	{
		countryId,
		name: `Martín Vizcarra`,
		party: `Peruvians for Change`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `23 March 2018`,
		leftOffice: `9 November 2020`,
	},
	{
		countryId,
		name: `Manuel Merino`,
		party: `Popular Action`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `10 November 2020`,
		leftOffice: `15 November 2020`,
	},
	{
		countryId,
		name: `Francisco Sagasti`,
		party: `Purple Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `17 November 2020`,
		leftOffice: `28 July 2021`,
	},
	{
		countryId,
		name: `Pedro Castillo`,
		party: `Free Peru`,
		leaning: leanings.FAR_LEFT,
		tookOffice: `28 July 2021`,
		leftOffice: `7 December 2022`,
	},
	{
		countryId,
		name: `Dina Boluarte`,
		party: `Independent`,
		leaning: leanings.LEFT,
		tookOffice: `7 December 2022`,
		leftOffice: null,
	},
];
