import type { LeaderNoId } from "../../app/data/types";
import { leanings } from "../../app/data/types";

export const source = `https://www.mapsofworld.com/list-of/presidents-uruguay/`;

const countryId = 21;

export const uruguay: LeaderNoId[] = [
	{
		countryId,
		name: `Luis Lacalle Pou`,
		party: `National Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 March 2020`,
		leftOffice: null,
	},
	{
		countryId,
		name: `Tabaré Vázquez`,
		party: `Broad Front`,
		leaning: leanings.LEFT,
		tookOffice: `1 March 2015`,
		leftOffice: `1 March 2020`,
	},
	{
		countryId,
		name: `José Mujica`,
		party: `Broad Front`,
		leaning: leanings.LEFT,
		tookOffice: `1 March 2010`,
		leftOffice: `1 March 2015`,
	},
	{
		countryId,
		name: `Tabaré Vázquez`,
		party: `Broad Front`,
		leaning: leanings.LEFT,
		tookOffice: `1 March 2005`,
		leftOffice: `1 March 2010`,
	},
	{
		countryId,
		name: `Jorge Batlle`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 2000`,
		leftOffice: `1 March 2005`,
	},
	{
		countryId,
		name: `Julio María Sanguinetti`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1995`,
		leftOffice: `1 March 2000`,
	},
	{
		countryId,
		name: `Luis Alberto Lacalle`,
		party: `National Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 March 1990`,
		leftOffice: `1 March 1995`,
	},
	{
		countryId,
		name: `Julio María Sanguinetti`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1985`,
		leftOffice: `1 March 1990`,
	},
	{
		countryId,
		name: `Rafael Addiego`,
		party: `Civic Union Party`,
		leaning: leanings.RIGHT,
		tookOffice: `12 February 1985`,
		leftOffice: `1 March 1985`,
	},
	{
		countryId,
		name: `Gregorio Álvarez`,
		party: `Independent - Armed Forces of Uruguay`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `1 September 1981`,
		leftOffice: `12 February 1985`,
	},
	{
		countryId,
		name: `Aparicio Méndez`,
		party: `National Party / Civic-Military Dictatorship`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `1 September 1976`,
		leftOffice: `1 September 1981`,
	},
	{
		countryId,
		name: `Alberto Demicheli`,
		party: `Colorado Party / Civic-Military Dictatorship`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `12 June 1976`,
		leftOffice: `1 September 1976`,
	},
	{
		countryId,
		name: `Juan María Bordaberry`,
		party: `Colorado Party / Civic-Military Dictatorship`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `1 March 1972`,
		leftOffice: `12 June 1976`,
	},
	{
		countryId,
		name: `Jorge Pacheco`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `6 December 1967`,
		leftOffice: `1 March 1972`,
	},
	{
		countryId,
		name: `Óscar Diego Gestido`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1967`,
		leftOffice: `6 December 1967`,
	},
	{
		countryId,
		name: `National Council of Government`,
		party: `National Council of Government`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1952`,
		leftOffice: `1 March 1967`,
	},
	{
		countryId,
		name: `Andres Martínez Trueba`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1951`,
		leftOffice: `1 March 1952`,
	},
	{
		countryId,
		name: `Luis Batlle Berres`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `2 August 1947`,
		leftOffice: `1 March 1951`,
	},
	{
		countryId,
		name: `Tomás Berreta`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1947`,
		leftOffice: `2 August 1947`,
	},
	{
		countryId,
		name: `Juan José de Amézaga`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1943`,
		leftOffice: `1 March 1947`,
	},
	{
		countryId,
		name: `Alfredo Baldomir Ferrari`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `19 June 1938`,
		leftOffice: `1 March 1943`,
	},
	{
		countryId,
		name: `Gabriel Terra`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1931`,
		leftOffice: `19 June 1938`,
	},
	{
		countryId,
		name: `Juan Campisteguy`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1927`,
		leftOffice: `19 June 1938`,
	},
	{
		countryId,
		name: `José Serrato`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1923`,
		leftOffice: `1 March 1927`,
	},
	{
		countryId,
		name: `Baltasar Brum`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1919`,
		leftOffice: `1 March 1923`,
	},
	{
		countryId,
		name: `Feliciano Viera`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1915`,
		leftOffice: `1 March 1919`,
	},
	{
		countryId,
		name: `José Batlle y Ordoñez`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1911`,
		leftOffice: `1 March 1915`,
	},
	{
		countryId,
		name: `Claudio Wílliman`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1907`,
		leftOffice: `1 March 1911`,
	},
	{
		countryId,
		name: `José Batlle y Ordoñez`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1903`,
		leftOffice: `1 March 1907`,
	},
	{
		countryId,
		name: `Juan Lindolfo Cuestas`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1899`,
		leftOffice: `1 March 1903`,
	},
	{
		countryId,
		name: `José Batlle y Ordoñez`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `5 February 1899`,
		leftOffice: `1 March 1899`,
	},
	{
		countryId,
		name: `Juan Lindolfo Cuestas`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `25 August 1897`,
		leftOffice: `5 February 1899`,
	},
	{
		countryId,
		name: `Juan Idiarte Borda`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `21 March 1894`,
		leftOffice: `25 August 1897`,
	},
	{
		countryId,
		name: `Duncan Stewart`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1894`,
		leftOffice: `21 March 1894`,
	},
	{
		countryId,
		name: `Julio Herrera y Obes`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1890`,
		leftOffice: `1 March 1894`,
	},
	{
		countryId,
		name: `Máximo Santos`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `18 November 1886`,
		leftOffice: `1 March 1890`,
	},
	{
		countryId,
		name: `Francisco Antonino Vidal`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1886`,
		leftOffice: `24 May 1886`,
	},
	{
		countryId,
		name: `Máximo Santos`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1882`,
		leftOffice: `1 March 1886`,
	},
	{
		countryId,
		name: `Francisco Antonino Vidal`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `15 March 1880`,
		leftOffice: `1 February 1882`,
	},
	{
		countryId,
		name: `Lorenzo Latorre`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1879`,
		leftOffice: `15 March 1880`,
	},
	{
		countryId,
		name: `Pedro Varela`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `22 January 1875`,
		leftOffice: `10 March 1876`,
	},
];
