import type { LeaderNoId } from '../../app/data/types';
import { leanings } from '../../app/data/types';

export const source = `https://en.wikipedia.org/wiki/List_of_presidents_of_Uruguay`;

const countryId = 21;

export const uruguay: LeaderNoId[] = [
	{
		countryId,
		name: 'Viceroyalty of the Río de la Plata',
		party: 'Spanish Empire',
		leaning: leanings.MONARCHY,
		tookOffice: '1 August 1776',
		leftOffice: '9 July 1814',
	},
	{
		countryId,
		name: 'Nicolás Rodríguez Peña',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '9 July 1814',
		leftOffice: '25 August 1814',
	},
	{
		countryId,
		name: 'Miguel Estanislao Soler',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '25 August 1814',
		leftOffice: '25 February 1815',
	},
	{
		countryId,
		name: 'Fernando Otorgués',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '26 February 1815',
		leftOffice: 'July 1815',
	},
	{
		countryId,
		name: 'Miguel Barreiro',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: 'July 1815',
		leftOffice: '20 January 1817',
	},
	{
		countryId,
		name: 'Carlos Frederico Lecor',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '20 January 1817',
		leftOffice: '3 February 1826',
	},
	{
		countryId,
		name: 'Francisco de Paula Magessi Tavares de Carvalho',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '3 February 1826',
		leftOffice: '27 August 1828',
	},
	{
		countryId,
		name: 'Juan Antonio Lavalleja',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '19 September 1825',
		leftOffice: '5 July 1826',
	},
	{
		countryId,
		name: 'Joaquín Suárez',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '5 July 1826',
		leftOffice: '12 October 1827',
	},
	{
		countryId,
		name: 'Luis Eduardo Pérez',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '12 October 1827',
		leftOffice: '27 August 1828',
	},
	{
		countryId,
		name: 'Luis Eduardo Pérez',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '27 August 1828',
		leftOffice: '1 December 1828',
	},
	{
		countryId,
		name: 'Joaquín Suárez',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '2 December 1828',
		leftOffice: '22 December 1828',
	},
	{
		countryId,
		name: 'José Rondeau',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '22 December 1828',
		leftOffice: '17 April 1830',
	},
	{
		countryId,
		name: 'Juan Antonio Lavalleja',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '17 April 1830',
		leftOffice: '28 June 1830',
	},
	{
		countryId,
		name: 'Juan Antonio Lavalleja',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '28 June 1830',
		leftOffice: '24 October 1830',
	},
	{
		countryId,
		name: 'Luis Eduardo Pérez',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '24 October 1830',
		leftOffice: '6 November 1830',
	},
	{
		countryId,
		name: 'Fructuoso Rivera',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '6 November 1830',
		leftOffice: '24 October 1834',
	},
	{
		countryId,
		name: 'Carlos Anaya',
		party: 'Colorado Party',
		leaning: leanings.CENTRIST,
		tookOffice: '24 October 1834',
		leftOffice: '1 March 1835',
	},
	{
		countryId,
		name: 'Manuel Oribe',
		party: 'National Party / White Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '1 March 1835',
		leftOffice: '24 October 1838',
	},
	{
		countryId,
		name: 'Gabriel Antonio Pereira',
		party: 'Colorado Party',
		leaning: leanings.CENTRIST,
		tookOffice: '24 October 1838',
		leftOffice: '1 March 1839',
	},
	{
		countryId,
		name: 'Fructuoso Rivera',
		party: 'Colorado Party',
		leaning: leanings.CENTRIST,
		tookOffice: '1 March 1839',
		leftOffice: '1 March 1843',
	},
	{
		countryId,
		name: 'Manuel Oribe',
		party: 'National Party / White Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '16 February 1843',
		leftOffice: '8 October 1851',
	},
	{
		countryId,
		name: 'Joaquín Suárez',
		party: 'Colorado Party',
		leaning: leanings.CENTRIST,
		tookOffice: '1 March 1843',
		leftOffice: '15 February 1852',
	},
	{
		countryId,
		name: 'Bernardo Prudencio Berro',
		party: 'National Party / White Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '15 February 1852',
		leftOffice: '1 March 1852',
	},
	{
		countryId,
		name: 'Juan Francisco Giró',
		party: 'National Party / White Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '1 March 1852',
		leftOffice: '25 September 1853',
	},
	{
		countryId,
		name: 'Juan Antonio Lavalleja',
		party: 'Independent',
		leaning: leanings.CENTRIST,
		tookOffice: '25 September 1853',
		leftOffice: '22 October 1853',
	},
	{
		countryId,
		name: 'Venancio Flores',
		party: 'Colorado Party',
		leaning: leanings.CENTRIST,
		tookOffice: '25 September 1853',
		leftOffice: '12 March 1854',
	},
	{
		countryId,
		name: 'Fructuoso Rivera',
		party: 'Colorado Party',
		leaning: leanings.CENTRIST,
		tookOffice: '25 September 1853',
		leftOffice: '13 January 1854',
	},
	{
		countryId,
		name: 'Venancio Flores',
		party: 'Colorado Party',
		leaning: leanings.CENTRIST,
		tookOffice: '12 March 1854',
		leftOffice: '10 September 1855',
	},
	{
		countryId,
		name: 'Luis María Lamas',
		party: 'Rebellion of the Conservatives',
		leaning: leanings.RIGHT,
		tookOffice: '29 August 1855',
		leftOffice: '10 September 1855',
	},
	{
		countryId,
		name: 'Manuel Basilio Bustamante',
		party: 'Colorado Party',
		leaning: leanings.CENTRIST,
		tookOffice: '10 September 1855',
		leftOffice: '15 February 1856',
	},
	{
		countryId,
		name: 'José María Plá',
		party: 'Colorado Party',
		leaning: leanings.CENTRIST,
		tookOffice: '15 February 1856',
		leftOffice: '1 March 1856',
	},
	{
		countryId,
		name: 'Gabriel Antonio Pereira',
		party: 'Colorado Party',
		leaning: leanings.CENTRIST,
		tookOffice: '1 March 1856',
		leftOffice: '1 March 1860',
	},
	{
		countryId,
		name: 'Bernardo Prudencio Berro',
		party: 'National Party / White Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '1 March 1860',
		leftOffice: '1 March 1864',
	},
	{
		countryId,
		name: 'Atanasio Cruz Aguirre',
		party: 'National Party / White Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '1 March 1864',
		leftOffice: '15 February 1865',
	},
	{
		countryId,
		name: 'Tomás Villalba',
		party: 'National Party / White Party',
		leaning: leanings.CENTER_RIGHT,
		tookOffice: '15 February 1865',
		leftOffice: '20 February 1865',
	},
	{
		countryId,
		name: 'Venancio Flores',
		party: 'Colorado Party',
		leaning: leanings.CENTRIST,
		tookOffice: '20 February 1865',
		leftOffice: '15 February 1868',
	},
	{
		countryId,
		name: 'Pedro Varela',
		party: 'Colorado Party',
		leaning: leanings.CENTRIST,
		tookOffice: '15 February 1868',
		leftOffice: '1 March 1868',
	},
	{
		countryId,
		name: 'Lorenzo Batlle',
		party: 'Colorado Party',
		leaning: leanings.CENTRIST,
		tookOffice: '1 March 1868',
		leftOffice: '1 March 1872',
	},
	{
		countryId,
		name: 'Tomás Gomensoro Albín',
		party: 'Colorado Party',
		leaning: leanings.CENTRIST,
		tookOffice: '1 March 1872',
		leftOffice: '1 March 1873',
	},
	{
		countryId,
		name: 'José Eugenio Ellauri',
		party: 'Colorado Party',
		leaning: leanings.CENTRIST,
		tookOffice: '1 March 1873',
		leftOffice: '22 January 1875',
	},
	{
		countryId,
		name: 'Pedro Varela',
		party: 'Colorado Party',
		leaning: leanings.CENTRIST,
		tookOffice: '22 January 1875',
		leftOffice: '10 March 1876',
	},
	{
		countryId,
		name: 'Lorenzo Latorre',
		party: 'Colorado Party',
		leaning: leanings.CENTRIST,
		tookOffice: '10 March 1876',
		leftOffice: '1 March 1879',
	},
	{
		countryId,
		name: `Pedro Varela`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `22 January 1875`,
		leftOffice: `10 March 1876`,
	},
	{
		countryId,
		name: `Lorenzo Latorre`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1879`,
		leftOffice: `15 March 1880`,
	},
	{
		countryId,
		name: `Francisco Antonino Vidal`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `15 March 1880`,
		leftOffice: `1 February 1882`,
	},
	{
		countryId,
		name: `Máximo Santos`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1882`,
		leftOffice: `1 March 1886`,
	},
	{
		countryId,
		name: `Francisco Antonino Vidal`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1886`,
		leftOffice: `24 May 1886`,
	},
	{
		countryId,
		name: `Máximo Santos`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `24 May 1886`,
		leftOffice: `18 November 1886`,
	},
	{
		countryId,
		name: `Máximo Tajes`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `18 November 1886`,
		leftOffice: `1 March 1890`,
	},
	{
		countryId,
		name: `Julio Herrera y Obes`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1890`,
		leftOffice: `1 March 1894`,
	},
	{
		countryId,
		name: `Duncan Stewart`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1894`,
		leftOffice: `21 March 1894`,
	},
	{
		countryId,
		name: `Juan Idiarte Borda`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `21 March 1894`,
		leftOffice: `25 August 1897`,
	},
	{
		countryId,
		name: `Juan Lindolfo Cuestas`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `25 August 1897`,
		leftOffice: `5 February 1899`,
	},
	{
		countryId,
		name: `José Batlle y Ordoñez`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `5 February 1899`,
		leftOffice: `1 March 1899`,
	},
	{
		countryId,
		name: `Juan Lindolfo Cuestas`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1899`,
		leftOffice: `1 March 1903`,
	},
	{
		countryId,
		name: `José Batlle y Ordoñez`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1903`,
		leftOffice: `1 March 1907`,
	},
	{
		countryId,
		name: `Claudio Wílliman`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1907`,
		leftOffice: `1 March 1911`,
	},
	{
		countryId,
		name: `José Batlle y Ordoñez`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1911`,
		leftOffice: `1 March 1915`,
	},
	{
		countryId,
		name: `Feliciano Viera`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1915`,
		leftOffice: `1 March 1919`,
	},
	{
		countryId,
		name: `Baltasar Brum`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1919`,
		leftOffice: `1 March 1923`,
	},
	{
		countryId,
		name: `José Serrato`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1923`,
		leftOffice: `1 March 1927`,
	},
	{
		countryId,
		name: `Juan Campisteguy`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1927`,
		leftOffice: `19 June 1938`,
	},
	{
		countryId,
		name: `Gabriel Terra`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1931`,
		leftOffice: `19 June 1938`,
	},
	{
		countryId,
		name: `Alfredo Baldomir Ferrari`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `19 June 1938`,
		leftOffice: `1 March 1943`,
	},
	{
		countryId,
		name: `Juan José de Amézaga`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1943`,
		leftOffice: `1 March 1947`,
	},
	{
		countryId,
		name: `Tomás Berreta`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1947`,
		leftOffice: `2 August 1947`,
	},
	{
		countryId,
		name: `Luis Batlle Berres`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `2 August 1947`,
		leftOffice: `1 March 1951`,
	},
	{
		countryId,
		name: `Andres Martínez Trueba`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1951`,
		leftOffice: `1 March 1952`,
	},
	{
		countryId,
		name: `National Council of Government`,
		party: `National Council of Government`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1952`,
		leftOffice: `1 March 1967`,
	},
	{
		countryId,
		name: `Óscar Diego Gestido`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1967`,
		leftOffice: `6 December 1967`,
	},
	{
		countryId,
		name: `Jorge Pacheco`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `6 December 1967`,
		leftOffice: `1 March 1972`,
	},
	{
		countryId,
		name: `Juan María Bordaberry`,
		party: `Colorado Party / Civic-Military Dictatorship`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `1 March 1972`,
		leftOffice: `12 June 1976`,
	},
	{
		countryId,
		name: `Alberto Demicheli`,
		party: `Colorado Party / Civic-Military Dictatorship`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `12 June 1976`,
		leftOffice: `1 September 1976`,
	},
	{
		countryId,
		name: `Aparicio Méndez`,
		party: `National Party / White Party / Civic-Military Dictatorship`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `1 September 1976`,
		leftOffice: `1 September 1981`,
	},
	{
		countryId,
		name: `Gregorio Álvarez`,
		party: `Independent - Armed Forces of Uruguay`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `1 September 1981`,
		leftOffice: `12 February 1985`,
	},
	{
		countryId,
		name: `Rafael Addiego`,
		party: `Civic Union Party`,
		leaning: leanings.RIGHT,
		tookOffice: `12 February 1985`,
		leftOffice: `1 March 1985`,
	},
	{
		countryId,
		name: `Julio María Sanguinetti`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1985`,
		leftOffice: `1 March 1990`,
	},
	{
		countryId,
		name: `Luis Alberto Lacalle`,
		party: `National Party / White Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 March 1990`,
		leftOffice: `1 March 1995`,
	},
	{
		countryId,
		name: `Julio María Sanguinetti`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1995`,
		leftOffice: `1 March 2000`,
	},
	{
		countryId,
		name: `Jorge Batlle`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 2000`,
		leftOffice: `1 March 2005`,
	},
	{
		countryId,
		name: `Tabaré Vázquez`,
		party: `Broad Front`,
		leaning: leanings.LEFT,
		tookOffice: `1 March 2005`,
		leftOffice: `1 March 2010`,
	},
	{
		countryId,
		name: `José Mujica`,
		party: `Broad Front`,
		leaning: leanings.LEFT,
		tookOffice: `1 March 2010`,
		leftOffice: `1 March 2015`,
	},
	{
		countryId,
		name: `Tabaré Vázquez`,
		party: `Broad Front`,
		leaning: leanings.LEFT,
		tookOffice: `1 March 2015`,
		leftOffice: `1 March 2020`,
	},
	{
		countryId,
		name: `Luis Lacalle Pou`,
		party: `National Party / White Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 March 2020`,
		leftOffice: null,
	},
];
