import type { LeaderNoId } from '../../app/data/types';
import { leanings } from '../../app/data/types';

export const source = `https://en.wikipedia.org/wiki/List_of_presidents_of_Venezuela`;

const countryId = 11;

export const venezuela: LeaderNoId[] = [
	{
		countryId,
		name: `Viceroyalty of New Granada`,
		party: `Kingdom of Spain`,
		leaning: leanings.MONARCHY,
		tookOffice: `27 May 1717`,
		leftOffice: `5 July 1811`,
	},
	{
		countryId,
		name: `Cristóbal Mendoza`,
		party: `First Republic of Venezuela`,
		leaning: leanings.MILITARY,
		tookOffice: `5 July 1811`,
		leftOffice: `3 April 1812`,
	},
	{
		countryId,
		name: `Francisco Espejo`,
		party: `First Republic of Venezuela`,
		leaning: leanings.MILITARY,
		tookOffice: `3 April 1812`,
		leftOffice: `25 July 1812`,
	},
	{
		countryId,
		name: `Various Military Leaders`,
		party: `Venezuelan War of Independence`,
		leaning: leanings.MILITARY,
		tookOffice: `25 July 1812`,
		leftOffice: `15 February 1819`,
	},
	{
		countryId,
		name: `Simón Bolívar`,
		party: `Independent`,
		leaning: leanings.MILITARY,
		tookOffice: `15 February 1819`,
		leftOffice: `13 January 1830`,
	},
	{
		countryId,
		name: `José Antonio Páez`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `13 January 1830`,
		leftOffice: `20 January 1835`,
	},
	{
		countryId,
		name: `Andrés Narvarte`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `20 January 1835`,
		leftOffice: `9 February 1835`,
	},
	{
		countryId,
		name: `José María Vargas`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `9 February 1835`,
		leftOffice: `9 July 1835`,
	},
	{
		countryId,
		name: `José María Carreño`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `27 July 1835`,
		leftOffice: `20 August 1835`,
	},
	{
		countryId,
		name: `José María Vargas`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `20 August 1835`,
		leftOffice: `24 April 1836`,
	},
	{
		countryId,
		name: `Andrés Narvarte`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `24 April 1836`,
		leftOffice: `20 January 1837`,
	},
	{
		countryId,
		name: `José María Carreño`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `27 January 1837`,
		leftOffice: `11 March 1837`,
	},
	{
		countryId,
		name: `Carlos Soublette`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `11 March 1837`,
		leftOffice: `1 February 1839`,
	},
	{
		countryId,
		name: `José Antonio Páez`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 February 1839`,
		leftOffice: `28 January 1843`,
	},
	{
		countryId,
		name: `Carlos Soublette`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `28 January 1843`,
		leftOffice: `20 January 1847`,
	},
	{
		countryId,
		name: `José Tadeo Monagas`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `20 January 1847`,
		leftOffice: `5 February 1851`,
	},
	{
		countryId,
		name: `José Gregorio Monagas`,
		party: `Great Liberal Party of Venezuela`,
		leaning: leanings.LEFT,
		tookOffice: `5 February 1851`,
		leftOffice: `20 January 1855`,
	},
	{
		countryId,
		name: `José Tadeo Monagas`,
		party: `Great Liberal Party of Venezuela`,
		leaning: leanings.LEFT,
		tookOffice: `20 January 1855`,
		leftOffice: `15 March 1858`,
	},
	{
		countryId,
		name: `Pedro Gual Escandón`,
		party: `Great Liberal Party of Venezuela`,
		leaning: leanings.LEFT,
		tookOffice: `15 March 1858`,
		leftOffice: `18 March 1858`,
	},
	{
		countryId,
		name: `Julián Castro`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `18 March 1858`,
		leftOffice: `2 August 1859`,
	},
	{
		countryId,
		name: `Pedro Gual Escandón`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `2 August 1859`,
		leftOffice: `29 September 1859`,
	},
	{
		countryId,
		name: `Manuel Felipe de Tovar`,
		party: `Great Liberal Party of Venezuela`,
		leaning: leanings.LEFT,
		tookOffice: `29 September 1859`,
		leftOffice: `20 May 1861`,
	},
	{
		countryId,
		name: `Pedro Gual Escandón`,
		party: `Great Liberal Party of Venezuela`,
		leaning: leanings.LEFT,
		tookOffice: `20 May 1861`,
		leftOffice: `29 August 1861`,
	},
	{
		countryId,
		name: `José Antonio Páez`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `29 August 1861`,
		leftOffice: `15 June 1863`,
	},
	{
		countryId,
		name: `Juan Crisóstomo Falcón`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `15 June 1863`,
		leftOffice: `25 April 1868`,
	},
	{
		countryId,
		name: `José Antonio Páez`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `29 August 1861`,
		leftOffice: `15 June 1863`,
	},
	{
		countryId,
		name: `Juan Crisóstomo Falcón`,
		party: `Great Liberal Party of Venezuela`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `15 June 1863`,
		leftOffice: `25 April 1868`,
	},
	{
		countryId,
		name: `Manuel Ezequiel Bruzual`,
		party: `Great Liberal Party of Venezuela`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `25 April 1868`,
		leftOffice: `28 June 1868`,
	},
	{
		countryId,
		name: `Guillermo Tell Villegas`,
		party: `Great Liberal Party of Venezuela`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `28 June 1868`,
		leftOffice: `20 February 1869`,
	},
	{
		countryId,
		name: `José Ruperto Monagas`,
		party: `Great Liberal Party of Venezuela`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `20 February 1869`,
		leftOffice: `16 April 1870`,
	},
	{
		countryId,
		name: `Guillermo Tell Villegas`,
		party: `Great Liberal Party of Venezuela`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `16 April 1870`,
		leftOffice: `27 April 1870`,
	},
	{
		countryId,
		name: `Antonio Guzmán Blanco`,
		party: `Great Liberal Party of Venezuela`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `27 April 1870`,
		leftOffice: `27 February 1877`,
	},
	{
		countryId,
		name: `Francisco Linares Alcántara`,
		party: `Great Liberal Party of Venezuela`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `27 February 1877`,
		leftOffice: `30 November 1878`,
	},
	{
		countryId,
		name: `José Gregorio Valera`,
		party: `Great Liberal Party of Venezuela`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `30 November 1878`,
		leftOffice: `26 February 1879`,
	},
	{
		countryId,
		name: `Antonio Guzmán Blanco`,
		party: `Great Liberal Party of Venezuela`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `26 February 1879`,
		leftOffice: `26 April 1884`,
	},
	{
		countryId,
		name: `Joaquín Crespo`,
		party: `Great Liberal Party of Venezuela`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `26 April 1884`,
		leftOffice: `15 September 1886`,
	},
	{
		countryId,
		name: `Antonio Guzmán Blanco`,
		party: `Great Liberal Party of Venezuela`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `15 September 1886`,
		leftOffice: `8 August 1887`,
	},
	{
		countryId,
		name: `Hermógenes López`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `8 August 1887`,
		leftOffice: `2 July 1888`,
	},
	{
		countryId,
		name: `Juan Pablo Rojas`,
		party: `Great Liberal Party of Venezuela`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `2 July 1888`,
		leftOffice: `19 March 1890`,
	},
	{
		countryId,
		name: `Raimundo Andueza`,
		party: `Great Liberal Party of Venezuela`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `19 March 1890`,
		leftOffice: `17 June 1892`,
	},
	{
		countryId,
		name: `Guillermo Tell Villegas`,
		party: `Great Liberal Party of Venezuela`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `17 June 1892`,
		leftOffice: `31 August 1892`,
	},
	{
		countryId,
		name: `Guillermo Tell Villegas Pulido`,
		party: `Great Liberal Party of Venezuela`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `31 August 1892`,
		leftOffice: `7 October 1892`,
	},
	{
		countryId,
		name: `Joaquín Crespo`,
		party: `Great Liberal Party of Venezuela`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `7 October 1892`,
		leftOffice: `28 February 1898`,
	},
	{
		countryId,
		name: `Ignacio Andrade`,
		party: `Great Liberal Party of Venezuela`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `28 February 1898`,
		leftOffice: `20 October 1899`,
	},
	{
		countryId,
		name: `Cipriano Castro`,
		party: `Armed Forces of Venezuela`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `20 October 1899`,
		leftOffice: `19 December 1908`,
	},
	{
		countryId,
		name: `Juan Vicente Gómez`,
		party: `Armed Forces of Venezuela`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `19 December 1908`,
		leftOffice: `5 August 1913`,
	},
	{
		countryId,
		name: `José Gil Fortoul`,
		party: `Independent`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `5 August 1913`,
		leftOffice: `19 April 1914`,
	},
	{
		countryId,
		name: `Victorino Márquez`,
		party: `Independent`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `19 April 1914`,
		leftOffice: `24 June 1922`,
	},
	{
		countryId,
		name: `Juan Vicente Gómez`,
		party: `Armed Forces of Venezuela`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `24 June 1922`,
		leftOffice: `30 May 1929`,
	},
	{
		countryId,
		name: `Juan Bautista Pérez`,
		party: `Independent`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `30 May 1929`,
		leftOffice: `13 June 1931`,
	},
	{
		countryId,
		name: `Juan Vicente Gómez`,
		party: `Armed Forces of Venezuela`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `13 June 1931`,
		leftOffice: `18 December 1935`,
	},
	{
		countryId,
		name: `Eleazar López Contreras`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `18 December 1935`,
		leftOffice: `5 May 1941`,
	},
	{
		countryId,
		name: `Isaías Medina Angarita`,
		party: `Venezuelan Democratic Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `5 May 1941`,
		leftOffice: `19 October 1945`,
	},
	{
		countryId,
		name: `Rómulo Betancourt`,
		party: `Democratic Action`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `19 October 1945`,
		leftOffice: `17 February 1948`,
	},
	{
		countryId,
		name: `Rómulo Gallegos`,
		party: `Democratic Action`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `17 February 1948`,
		leftOffice: `24 November 1948`,
	},
	{
		countryId,
		name: `Carlos Delgado Chalbaud`,
		party: `Armed Forces of Venezuela`,
		leaning: leanings.CENTRIST,
		tookOffice: `24 November 1948`,
		leftOffice: `13 November 1950`,
	},
	{
		countryId,
		name: `Germán Suárez Flamerich`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `27 November 1950`,
		leftOffice: `2 December 1952`,
	},
	{
		countryId,
		name: `Marcos Pérez Jiménez`,
		party: `Armed Forces of Venezuela`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `2 December 1952`,
		leftOffice: `23 January 1958`,
	},
	{
		countryId,
		name: `Wolfgang Larrazábal`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `23 January 1958`,
		leftOffice: `14 November 1958`,
	},
	{
		countryId,
		name: `Edgar Sanabria`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `14 November 1958`,
		leftOffice: `13 February 1959`,
	},
	{
		countryId,
		name: `Rómulo Betancourt`,
		party: `Democratic Action`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `13 February 1959`,
		leftOffice: `13 March 1964`,
	},
	{
		countryId,
		name: `Raúl Leoni`,
		party: `Democratic Action`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `13 March 1964`,
		leftOffice: `11 March 1969`,
	},
	{
		countryId,
		name: `Rafael Caldera`,
		party: `Copei`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `11 March 1969`,
		leftOffice: `12 March 1974`,
	},
	{
		countryId,
		name: `Carlos Andrés Pérez`,
		party: `Democratic Action`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `12 March 1974`,
		leftOffice: `12 March 1979`,
	},
	{
		countryId,
		name: `Luis Herrera Campins`,
		party: `Copei`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `12 March 1979`,
		leftOffice: `2 February 1984`,
	},
	{
		countryId,
		name: `Jaime Lusinchi`,
		party: `Democratic Action`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `2 February 1984`,
		leftOffice: `2 February 1989`,
	},
	{
		countryId,
		name: `Carlos Andrés Pérez`,
		party: `Democratic Action`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `2 February 1989`,
		leftOffice: `20 May 1993`,
	},
	{
		countryId,
		name: `Octavio Lepage`,
		party: `Democratic Action`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `21 May 1993`,
		leftOffice: `5 June 1993`,
	},
	{
		countryId,
		name: `Ramón José Velásquez`,
		party: `Democratic Action`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `5 June 1993`,
		leftOffice: `2 February 1994`,
	},
	{
		countryId,
		name: `Rafael Caldera`,
		party: `National Convergence`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `2 February 1994`,
		leftOffice: `2 February 1999`,
	},
	{
		countryId,
		name: `Hugo Chávez`,
		party: `United Socialist Party`,
		leaning: leanings.FAR_LEFT,
		tookOffice: `2 February 1999`,
		leftOffice: `12 April 2002`,
	},
	{
		countryId,
		name: `Pedro Carmona`,
		party: `Independent`,
		leaning: leanings.RIGHT,
		tookOffice: `12 April 2002`,
		leftOffice: `13 April 2002`,
	},
	{
		countryId,
		name: `Diosdado Cabello`,
		party: `United Socialist Party`,
		leaning: leanings.FAR_LEFT,
		tookOffice: `13 April 2002`,
		leftOffice: `14 April 2002`,
	},
	{
		countryId,
		name: `Hugo Chávez`,
		party: `United Socialist Party`,
		leaning: leanings.FAR_LEFT,
		tookOffice: `14 April 2002`,
		leftOffice: `5 March 2013`,
	},
	{
		countryId,
		name: `Nicolás Maduro`,
		party: `United Socialist Party`,
		leaning: leanings.FAR_LEFT,
		tookOffice: `5 March 2013`,
		leftOffice: null,
	},
];
